pkg/scalers/kafka_scaler.go

We don't want to scale beyond the number of available partitions, as that would result in pods that don't actually consume events.
This PR sets the lag threshold to not allow for more pods than needed.

kafka - don't scale beyond number of partitions

---

pkg/handler/scale_handler.go

Fixes the issue causing #146 
There's a bug in how the scale handler resolves environment variables that are set using 'valueFrom' instead of 'envFrom' - it tries to resolve using the env var name as the key instead of the specified secret/configmap key.

Use configmap/secret key names instead of env var name in function calls

---

chart/keda/README.md

Provide README for Helm Chart to provide some guidance when displayed on hub.helm.sh.
There are a few things we need to decide on:
- The formal name of the chart (#206)
- Currently a lot of it comes from the README which means duplication
- Are we ok with this?
- We could copy it in, but that means we ship 100% the same, which can be ok or not
- Chart docs are referring to images in the GitHub repo
- If we change those, we break the chart docs. Ok or see if we can move it in chart (and thus make chart bigger)
Relates to #203, #202

Provide README for Helm Chart

---

pkg/handler/scale_handler.go
pkg/provider/provider.go

This change keeps track of the HPAs that failed creation and is retried when handleScale gets called.
The metrics adapter also returns errors when the secret/other deployment info cannot be found so HPA does not end up scaling on CPU incorrectly.
https://github.com/kedacore/keda/issues/236
https://github.com/kedacore/keda/issues/236

HPA creation retry when scaled object validation fails

---

pkg/scalers/rabbitmq_scaler_test.go

The RabbitMQ Scaler is missing tests that check the metadata. These tests are present for all other scalers. Opened an [issue](https://github.com/kedacore/keda/issues/267)

Added test for RabbitMQ

---

chart/keda/templates/deployment.yaml

This is leftover from when this was using a private container registry.

Remove imagePullSecrets

---

pkg/scalers/azure_queue.go

Found during nightly E2E run. https://circleci.com/gh/kedacore/keda/455
the `:=` is defining a new `accountName` var in the `if !usePodIdentity` scope. If we're not using AAD identity, `accountName` will always be an empty string and cause KEDA to log this error 
```
time="2019-07-15T18:43:08Z" level=error msg="error -> github.com/kedacore/keda/vendor/github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClientFactory.func1.1, /go/src/github.com/kedacore/keda/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:234\nHTTP request failed\n\nPut https://.queue.core.windows.net/queue-name?timeout=61: dial tcp: lookup .queue.core.windows.net: no such host\n"
time="2019-07-15T18:43:46Z" level=error msg="error -> github.com/kedacore/keda/vendor/github.com/Azure/azure-pipeline-go/pipelin …
```

Fix variable shadow in azure_queue.go

---

pkg/scalers/azure_queue.go

Using the walrus (:=) in this change doesn't work, since all the
variables are already declared, or are undeclarable (_).
This causes the end-to-end test to fail, since the scalar can't parse
the azure queue credentials, used in the e2e test.

Fixing End-to-End test failure.

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

resolve #89 
Making a WIP PR as there is a big question on how we release this as it will be breaking.

moving rabbitMq host to resolved value

---

chart/keda/templates/hpa-role-binding.yaml

No longer use fixed name for HPA ClusterRoleBinding but use `{{ template "keda.fullname" . }}` like our other objects.
An option would also be to use a fixed prefix with the name at the end such as `hpa-controller-custom-metrics-keda-{{ .Release.Name }}`
Relates to #371
:warning: This has not been tested due to #369

Helm - No longer use fixed name for HPA ClusterRoleBinding

---

README.md
docs/scalers.md

This change will add more explanation on how the scalers work, specifically explaining the idea that Kubernetes HPA will poll GetMetrics function in scalers.

Add more info about scalers and GetMetricsin README.md

---

chart/keda/templates/hpa-role-binding.yaml

* if you enabled rbac for this helm chart it resulted creation of 2 ClusterRoleBinding's with the same name
* converted hpa-role-binding.yaml to Unix EOL

Fixed ClusterRoleBinding for HPA and fixed EOL

---

pkg/scalers/azure_queue_scaler.go

parseAzureQueueMetadata was not returning the podAuth setting, which was overriding podIdentity, and then getting set as part of the azureQueueMetadata{} object.
@ahmelsayed for visibility / review

Returning podAuth so it doesn't get overridden

---

build/Dockerfile.adapter

This change allows us to use [generate certs function in Operator Lifecycly Manager](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#your-api-services), if operator is deployed through OLM.
This is not a breaking change for other deployment types.

Metrics adapter: change location where certs are stored

---

.gitignore

Merge once  #412 is merged.
`vendor` directory should be ignored, if is accidentaly generated locally.

ignore vendor directory

---

tests/setup.test.ts

When KEDA was refactored to use operator-sdk, deploying KEDA was changed from deploy/KedaScaleController.yaml to 
```
kubectl apply -f deploy/crds/keda.k8s.io_scaledobjects_crd.yaml
kubectl apply -f deploy/crds/keda.k8s.io_triggerauthentications_crd.yaml
kubectl apply -f deploy/
```
Looks like the e2e tests were missed during the refactor - I've changed them to reflect that, since they're still trying to deploy KedaScaleController.yaml, which does not exist anymore.

fix e2e tests

---

README.md
docs/scalers.md

This PR originated from #395, 395 became obsolete because it was created before KEDA embraced the Operator model. Now this PR changes the README.md so that it explains how to build and deploy KEDA locally correctly.
I am aware that @lawrencegripper created a beautiful PR #429 to use docker for local builds, but I believe it doesn't hart to have both.
This also includes the beginning of a documentation on how to create scalers (still not the new external ones), issue #422 mentioned that we need more documentation around that. I have created this content  before knowing about this issue, so if @jeffhollan and @tomkerkhove are happy with it then it can be the beginning for the docs, otherwise I am happy with whatever they have on mind :).

Explain "how to build and deploy locally", and the start of "how to build a scaler".

---

examples/azurequeue_scaledobject_jobs.yaml

I am proposing a fix to the sample for a job ScaledObject (it was missing the template.spec element).
It also now points to a working sample container image that reads one message from the queue.

Fix sample for job ScaledObject

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Suggest_scaler.md

Proposal for issue templates that would help customers request certain features or report defects.
Experience would be similar to [Promitor](https://github.com/tomkerkhove/promitor/issues/new/choose), although a bit adapted:
Would also suggest to install the [`triage-new-issues`](https://github.com/apps/triage-new-issues) GitHub App for the  keep the "Open a blank issue" option.
Security is left out but tracked in #455

Proposal for issue templates

---

Makefile

The `operator-sdk build` command defaults to building a pkg that matches the folder name. 
Normally if you fork the keda repo and clone it to your machine, the folder name would be `keda`, so when building the Controller in `Makefile`, the pkg will be `keda` and there will be no problem. 
But if you rename the folder to something else (like I did :face_palm:) then the pkg will match the folder name and it won’t be `keda`. 
This breaks the `docker build` command in the Controller's Dockerfile, because it’s expecting the pkg name to be `keda`.
This PR makes the output pkg explicitly `keda` rather than matching the folder name.
Not a huge thing as not so many people will rename the repo folder, but it's better be explicit just like we are explicit in building the `keda-adapter`

Make keda pkg output name explicit

---

deploy/crds/keda.k8s.io_scaledobjects_crd.yaml
pkg/apis/keda/v1alpha1/scaledobject_types.go
pkg/apis/keda/v1alpha1/zz_generated.openapi.go

ScaledObject Status fields clean up

---

README.md

Provide capability to subscribe for standup meetings via Google Calendar.
This allows folks to just pull in the agenda in their calendar client and see if there is a meeting or not, for example when it's cancelled due to Thanksgiving.
Relates to #472

Provide capability to subscribe for standup meetings via Google Calendar

---

go.mod
go.sum
pkg/handler/scale_handler.go
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go
pkg/scalers/kafka_scram_client.go

add support sasl auth(sasl_plaintext,sasl_ssl,  sasl_scram_sha256, sasl_scram_sha512) for kafka scaler.

add kafka scaler sasl

---

.github/workflows/release-build.yml
Makefile
tests/setup.test.ts

Closes #489
This PR: 
- updated CI to push to `:master` instead of the current latest version
- updates e2e tests to use that image
- adds a new github workflow for version tags. When you create a `v2.0.0` tag, this workflow will create a corresponding `docker.io/kedacore/keda:2.0.0` and `docker.io/kedacore/keda-metrics-adapter:2.0.0`
note: versions in `deploy/operator.yml` and `version/version.go` still need to be updated manually when we want to have a release

Update CI and test to build/test master tag

---

go.mod
go.sum
pkg/handler/scale_handler.go
pkg/scalers/huawei_cloudeye_scaler.go
pkg/scalers/huawei_cloudeye_test.go

add support for huaweicloud cloudeye scaler.

Provide support for Huawei Cloud CloudEye scaler

---

deploy/operator.yaml

Adding default log level to deployment.yaml. So users can easily find the right place, in case they would need to change the log level.
Fixes https://github.com/kedacore/keda/issues/467

add default log level for operator

---

pkg/scalers/azure_eventhub.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_test.go

Solves #516 
- Made changes to azure_eventhub.go, azure_eventhub_scaler.go, azure_eventhub_test.go
- Added compatibility for reading azure blob store uri for Java applications using EventProcessorHost SDK for Event Hubs

Event Hub scalar expansion to work with Java and C# applications

---

pkg/handler/scale_deployments.go

scale from zero when minReplicaCount is > 0

---

pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/azure_servicebus_scaler_test.go

In the case of using the podIdentity settings,  namespace was redeclared in inner block, and have not changed the original value of  the namespace outside the block.
Remove short variable declaration in inner block

Service bus scaler pod identity fix 

---

pkg/handler/scale_handler.go
pkg/scalers/aws_iam_authorization.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_kinesis_stream_test.go

* Reason for Kinesis scaler: 
for any running Kinesis Client Library (KCL) application, a shard only has one owner. The pod# can't be scaled larger than open shard count for a KCL application. This scaler is to export current open shard count as scaling metrics, so users can decide how many shards that one consumer handles. 
* Doc [kedacore/keda-doc#61](https://github.com/kedacore/keda-docs/pull/61)
* This PR also includes the fix of the key mismatch (`awsAccessKeyId` and `awsAccessKeyID`) between docs, authParams and UTs.

add kinesis stream scaler

---

pkg/scalers/stan_scaler.go

Makes a change for #520 and adds additional logging to help diagnose connection issues.

Change how number of pending messages is calculated and add more error handling.

---

pkg/handler/scale_jobs.go

This PR is to honor the `queueLength` taking into account the number of running Jobs.  
In short, total running Jobs will be `queueLength - runningJobs`.
Running jobs are those jobs which are not in `Completed` or `Failed` Status.
This should address issue https://github.com/kedacore/keda/issues/525

Total running Jobs must not exceed maxScale - Running jobs

---

pkg/controller/scaledobject/scaledobject_controller.go

Fixes #504 
Improved check and error messages

Improve check of deploymentName definition in ScaledObject

---

pkg/scalers/kafka_scaler.go

For Issue #543.
Updated the Kafka scaler to add `config` parameters for Sarama client corresponding to SASL plaintext auth mode

Kafka scaler fix for SASL plaintext auth

---

CREATE-NEW-SCALER.md
README.md

As discussed in issue #531 the documentation about deployin custom keda is not actually working, this PR should contain the correct command to instruct helm on using the custom build instead of the stable one.

Fix custom keda deployment documentation

---

pkg/handler/scale_handler.go
pkg/scalers/azure_blob.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_blob_test.go
tests/scalers/azure-blob.test.ts

Relates to https://github.com/kedacore/keda/issues/154
Docs via https://github.com/kedacore/keda-docs/pull/58

Add azure blob scaler

---

deploy/operator.yaml

Updated the image tags for keda and keda-metrics-adapter to 1.1.0 to allow for the use of the azure-blob scaler to address #548

update the image tags for keda and keda-metrics-adapter to 1.1.0

---

pkg/scalers/postgres_scaler.go

Allow users to determine sslmode for postgres

remove manually adding sslmode to connection string

---

go.mod
go.sum
pkg/handler/scale_handler.go
pkg/scalers/mysql_scaler.go
pkg/scalers/mysql_scaler_test.go

This scaler works similarly to Postgres scaler added by @dimberman

Add MySQL scaler

---

pkg/handler/scale_handler.go
pkg/handler/scale_handler_test.go

I am working on tests, but it might take some time :) I am new here.
#555

Respect optional param for ConfigMaps and Secrets

---

README.md

With Operator SDK we can run the operator locally oustide cluster, which is helpful for development and debugging.
Adding instructions on how to achieve that.  
Fixes: https://github.com/kedacore/keda/issues/531

add instructions on local development and debugging

---

pkg/handler/scale_handler.go

Some ScaledObject changes like editing or adding a label don't change generation, therefore the resource will become stale, if we try to update it's Status in the ScaleLoop.
This adds a check on this particullar situation and try to re-fetch the ScaledObject if necessary.
Fixes https://github.com/kedacore/keda/issues/512

ScaledObject.Status update should handle stale resource

---

pkg/controller/scaledobject/scaledobject_controller.go
pkg/controller/scaledobject/scaledobject_finalizer.go

- watch changes on HPAs
- improvents on reconcile loop to check resources properly and not start ScaleLoop on each change
Partially solves issue in https://github.com/kedacore/keda/issues/511

Improve reconcile loop

---

Makefile

This PR adds a new `checkenv` target that could be useful to check some env vars.
For example, related to #599, it checks that the `GOROOT` is set otherwise the error from #599 happens.

Add a checkenv target

---

CREATE-NEW-SCALER.md

This PR adds links to the scaler interface documentation.

Added links to the scaler interface documentation

---

RELEASE-PROCESS.MD

- note about updating `version/version.go`
- correct yamls after Deployment split
- minor fixes
relates: #580

correcting release process doc

---

README.md

minor corrections in the instructions on local deployment

Local deployment minor fix

---

Makefile

This PR fixes #604 just printing a warning when GOROOT is not defined instead of exiting.

Changed exiting in a warning when GOROOT is not defined

---

README.md

This PR fixed a duplicate command which shows the keda metrics apiserver log twice instead of the keda operator one.

Fixed command to log keda-operator

---

pkg/handler/scale_handler.go
pkg/scalers/azure_monitor.go
pkg/scalers/azure_monitor_scaler.go
pkg/scalers/azure_monitor_test.go

Fixes #155 
Majority of the code in `azure_monitor.go` taken from [azure-k8s-metrics-adapter](https://github.com/Azure/azure-k8s-metrics-adapter/tree/master/pkg/azure/externalmetrics).
ScaledObject I used for testing authentication from metadata (minus the credentials)
```yaml
apiVersion: keda.k8s.io/v1alpha1
metadata:
name: order-processor-scaler
labels:
app: order-processor
deploymentName: order-processor
spec:
scaleTargetRef:
deploymentName: order-processor
minReplicaCount: 1 # Change to define how many minimum replicas you want
maxReplicaCount: 10
triggers:
- type: azure-monitor
metadata:
resourceURI: Microsoft.ContainerService/managedClusters/melconeKeda # Required. URI to the Azure resource
tenantId: xxxx # Required. Used for authentication
subscriptionId: xxxx # …
```

Add Azure monitor scaler

---

pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

This PR fixes #608 in order to add `bootstrapServers` and deprecate `brokerList` to specify the bootstrap brokers to use for connecting the Kafka client (inside the related scaler) to the Kafka cluster.
Fixes #

Added bootstrapServers to deprecate brokerList

---

README.md

Document logging levels for Operator and Metrics Server and small minor info on local deployment `operator-sdk` cli.
Fixes https://github.com/kedacore/keda/issues/618

document logging levels for Operator and Metrics Server

---

.github/ISSUE_TEMPLATE/Support.md

Provide "Support" issue template which applies `support` label.
We have a lot of issues open with `bug` while often it's just to ask a question or need help.

Provide "Support" issue template

---

pkg/scalers/postgresql_scaler.go

make targetQueryValue configurable in postgreSQL scaler

---

pkg/controller/scaledobject/scaledobject_controller.go

This PR fixes #545 removing the need for the `deploymentName` label on a `ScaledObject`.
Of course, it can still be there but there are no restrictions or checks anymore, the only mandatory one is the `spec.scaleTargetRef.deploymentName` field.
Fixes #

Removed the need for deploymentName label

---

pkg/controller/scaledobject/scaledobject_controller.go

Check presence of scaleTargetRef or jobTargetRef in ScaledObject and log appropriate message.
Fixes #646

check presence of scaleTargetRef or jobTargetRef

---

CHANGELOG.md
RELEASE-PROCESS.MD

Introduce changelog for KEDA to report new features & deprecations.
Closes #614 
FYI @kedacore/keda-owners, when doing releases these need to be updated.

Introduce changelog for KEDA

---

pkg/scalers/kafka_scaler.go

This PR fixes the connection issue to a Kafka broker in **SASL_SSL** mode.
In this mode, the user authenticates with the broker with its client certificate. There is no need for a user name or password.
The sarama **config.Net.SASL** must also be disabled in this mode.
Fixes #669

Fix a connection issue to a Kafka broker in SASL_SSL mode

---

CHANGELOG.md
deploy/00-namespace.yaml
deploy/01-service_account.yaml
deploy/10-cluster_role.yaml
deploy/11-role_binding.yaml
deploy/12-operator.yaml
deploy/20-metrics-cluster_role.yaml
deploy/21-metrics-role_binding.yaml
deploy/22-metrics-deployment.yaml
deploy/23-metrics-service.yaml
deploy/24-metrics-api_service.yaml
version/version.go

Scalers:
Add Azure monitor scaler (#584)
Scalers improvments:
Make targetQueryValue configurable in postgreSQL scaler (#643)
Added bootstrapServers to deprecate brokerList (#621)
Misc:
Changed exiting in a warning when GOROOT is not defined (#607)
Adding Kubernetes recommended labels to resources (#596)
Create make release target to update versions (#610)
Update release-build.yml (#612)
Added successful tests (#619)
Fixed command to log keda-operator (#622)
Update documentation to link to new Openshift 4 sample (#625)
Change 'create' to 'push' in release action (#627)
Document logging levels for Operator and Metrics Server (#633)
Provide "Support" issue template (#634)
Removed the need for deploymentName label (#644)
Check presence of scaleTargetRef or jobTargetRef (#648)
Add AWS pod …

KEDA release 1.3.0

---

CHANGELOG.md
RELEASE-PROCESS.MD

Cleanup v1.3 in changelog to only focus on the features that changed and not the internal working such as labels, etc.
Deprecations were moved back to an h2 as it is a general section.

Cleanup v1.3 in changelog

---

pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_cloudwatch_test.go
pkg/scalers/aws_iam_authorization.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_kinesis_stream_test.go
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/aws_sqs_queue_test.go

Added `podIdentity` boolean property in the ScaledObject resource under Triggers.Metadata to AWS scalers which tells to Keda operator if use the pod identity or the permissions are assigned on KEDA operator itself (without AssumeRole permissions). If set false use permissions are assigned on KEDA operator itself, if true the behavior will remain as it is today with pod identity. True is default.
example
```
apiVersion: keda.k8s.io/v1alpha1
spec:
triggers:
- metadata:
**podIdentity: false**
awsRegion: <REGION>
queueLength: <LENGTH>
queueURL: <URL>
type: aws-sqs-queue
```
Fixes #651

Authenticate to AWS with dedicated role without AssumeRole permissions

---

pkg/scalers/azure_monitor.go
pkg/scalers/azure_monitor_test.go

Handles nil pointers properly and adds checks for empty arrays which happens on some Azure Metric values.  Adds test for extracting the values from the Azure Monitor request. 
Fixes #679

Handle nil pointers and empty arrays properly in Azure Monitor Scaler

---

pkg/handler/scale_handler.go

We are using Keda with RabbitMQ, after 30 days running of `keda-operator` pod we have more than 1000 open connections in RabbitMQ console. It wasn't our app or something else, we checked it by restarting step by step. Connections were dropped only after `keda-operator` restart.
Fixes:
In case of error `GetDeploymentScalers` and `getJobScalers` returns acquired scalers, but callers of these methods doesn't use them or close them. So it doesn't make sense to return scalers at all in case of error, and it should close all already opened scalers to avoid leaking.

Fix scalers leaking

---

pkg/scalers/kafka_scaler.go

return if kafka offset response is nil

---

pkg/scalers/prometheus.go

~~- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs~~
~~- [ ] Tests have been added~~
Open to adding unit tests for the prometheus scaler, but I'm assuming that's better done as a separate dedicated work item rather than shoving it into the scope of this fix? There were tests for the scaler already, but they were just for metadata validation and not for any functionality. 
Fixes #657

Update zero result return to be non-error inducing

---

GOVERNANCE.md

Relates to #660
Relates to #663

Provide project governance

---

pkg/controller/scaledobject/scaledobject_controller.go

Fixing regression brought by https://github.com/kedacore/keda/issues/545
If there's no `deploymentLabel` on `ScaledObject`, KEDA creates one.
Fixes #708

add deploymentName label if needed

---

pkg/controller/scaledobject/scaledobject_controller.go

Labels can have maximum 63 characters, longer ones cause reconciliation failure during a creation of HPA. 
See: #704

HPA: label can have max 63 chars

---

pkg/apis/addtoscheme_keda_v1alpha1.go

There is MIT license left in one file, removing it to follow CNCF.

remove mit license

---

go.mod

go micro verision in go.mod could cause problems when building the project or using it as a dependency
Potentional fix for #713

remove go micro version

---

pkg/scalers/redis_scaler.go
pkg/scalers/redis_scaler_test.go

This should implement #694
(same code as PR #710 )
How does it works:
now the redis scaler accept 2 new parameters: host and port in addition of the already existing.
If address is specified it use the address, otherwise it checks the host and port parameters, they must be difned both, otherwise an error will be returned.
If address and host and port are all specified, address will get priority.
Fixes #

Add redis host and port parameter to the scaler with tests

---

pkg/provider/provider.go

Signed-off-by: ycabrer <43866176+ycabrer@users.noreply.github.com>
Filter Metrics case insensitive based on metric name. 
Fixes #702

Filter returned metrics from api server based on queried name. Issue # 702

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

Add settings which allows to count total messages count in queue (ready + unacked) to do not scale worker down if some long time processing is going.
By default `countUnacked = false` and it keeps old behaviour via AMQP protocol, if `countUnacked = true` it requires also `apiHost` to be set and uses HTTP management API to get queue info.
AMQP protocol doesn't allow to fetch unacked messages count, that is we need management API here. Technically we an completely switch to management API but as I understand not all servers have it enabled, that is why backward compatibility is saved and `countUnacked` is optional. 
It was tested in our Kubernetes cluster
Fixes https://github.com/kedacore/keda/issues/356

Extend RabbitMQ scaler to support count unacked messages

---

deploy/24-metrics-api_service.yaml
pkg/controller/scaledobject/hpa.go
pkg/controller/scaledobject/scaledobject_controller.go
pkg/controller/scaledobject/scaledobject_finalizer.go
pkg/handler/scale_handler.go
pkg/handler/scale_loop.go
pkg/handler/scale_scaledobjects.go
pkg/provider/provider.go
pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_monitor_scaler.go
pkg/scalers/azure_queue_scaler.go
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/external_scaler.go
pkg/scalers/gcp_pub_sub_scaler.go
pkg/scalers/huawei_cloudeye_scaler.go
pkg/scalers/kafka_scaler.go
pkg/scalers/liiklus_scaler.go
pkg/scalers/mysql_scaler.go
pkg/scalers/postgresql_scaler.go
pkg/scalers/prometheus_scaler.go
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/redis_scaler.go
pkg/scalers/scaler.go
pkg/scalers/stan_scaler.go

- changing autoscaling version from `v2beta1` to `v2beta2`, in fact it is an API change, shouldn't affect functionality.
- minor refactoring of finalizer on ScaledObject
- updating apiregistration/APIService used by Metrics server to `v1` (`v1beta1` was used previously and could be potentionaly deprecated soon, `v1` is supported on kubernetes >= v1.11, so no problems on this side wrt compatibility).
Fixes #721

[v2] autoscaling v2beta1 -> v2beta2 and minor refactoring

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go
tools/build-tools.Dockerfile

- pulling latest RabbitMQ scaler fix from master
- updating operator-sdk version in the build tool. This should make the validation work because previous verison of operator-sdk cli was using command `openapi`, but the new one (and the one used in Makefile) uses command `crds`
This PR should be **rebased and not squashed** to preserve history (ie to push this change as 2 commits instead of one squashed).

[v2] Sync with master and update operator-sdk version

---

Makefile
RELEASE-PROCESS.MD

This PR suggests a solution for #739

Provide installation YAML in the release

---

deploy/12-operator.yaml

The metrics service that is being created by the Operator SDK uses a the name label of the Operator https://github.com/operator-framework/operator-sdk/blob/f50d3f0f8e7d269e583116a666a354f5d931d8a1/pkg/metrics/metrics.go#L112.  Since this label is not currently being added to the pod the service does not have any matching endpoints so metrics would not be able to be scraped from the service.

Adding label for metrics service selection

---

Makefile
pkg/scaling/executor/scale_executor.go
pkg/scaling/executor/scale_scaledobjects.go
pkg/scaling/resolver/scale_resolvers.go
pkg/scaling/scale_handler.go

Minor fixes and refactoring:
- `getPods()`  return value was changed to `*corev1.PodTemplateSpec`
- fixed `ObjectMeta` and `TypeMeta` in `asDuckWithTriggers()`
- fixed logging in scale_scaleobjects.go

[v2] Refactor scaleHandler cont.

---

.github/workflows/pr-validation.yml

Signed-off-by: Ahmed ElSayed <ahmed@elsayed.io>
This change sets the image used for PR validation to `kedacore/build-tools:v2`, which is built from the `build-tools.Dockerfile` in the v2 branch

[v2] Update PR build action for v2

---

go.mod
go.sum

operator-sdk v0.17.0 was realeased (we have used pre-release version before).

[v2] update to operator-sdk v0.17.0

---

pkg/controller/scaledobject/scaledobject_controller.go

[v2] minor log messages improvements

---

Makefile
cmd/adapter/main.go
cmd/manager/main.go
version/version.go

Minor improvement for Metric Server -  let's print version info during startup, the same way KEDA Operator is doing currently

Metrics Server: print versions during startup

---

pkg/scaling/executor/scale_executor.go
pkg/scaling/executor/scale_jobs.go
pkg/scaling/executor/scale_scaledobjects.go

if we use `client.Status().Patch()` instead of `client.Status().Update()` we shouldn't hit the issue with modifying old resource anymore. Pach is merging only those fields that were updated. I have tested it and it seems like it is working correctly. We can revert back to the loop mechanism if there are going to be any issues.

[v2] use patch to update Status.LastActiveTime

---

README.md
deploy/12-operator.yaml

This argument allows for changing of the timestamp date format in the logging of the KEDA Operator.  This corresponds to the PR I have for the KEDA Helm Chart - https://github.com/kedacore/charts/pull/41. I have left the `zap-time-encoding-format` at the default of the Operator SDK - `epoch`.

Adding zap-time-encoding argument to the KEDA Operator Deployment

---

pkg/scalers/prometheus.go

This PR https://github.com/kedacore/keda/pull/695 brought regression in Prometheus scaler -> it marks the scaler as active even if there's no metrics in Prometheus, see the issue for details.
Fixes https://github.com/kedacore/keda/issues/770

IsActive() should return true only for val > 0

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

Fixes https://github.com/kedacore/keda/issues/768

Support vhost=/ for HTTP mode in RabbitMQ scaler

---

RELEASE-PROCESS.MD

Release Process - Upload release packages before Helm rollout

Release Process - Upload release packages before Helm rollout

---

deploy/crds/keda.sh_scaledjobs_crd.yaml
deploy/crds/keda.sh_scaledobjects_crd.yaml
deploy/crds/keda.sh_triggerauthentications_crd.yaml
pkg/apis/keda/v1alpha1/scaledjob_types.go
pkg/apis/keda/v1alpha1/scaledobject_types.go
pkg/apis/keda/v1alpha1/triggerauthentication_types.go

Generate CRD shortnames so they can be used with `kubectl get`
scaledObject -  so
scaledJob - sj
triggerAuthentication - ta, triggerauth
Fixes #774

[v2] generate CRD shortnames

---

deploy/crds/keda.sh_triggerauthentications_crd.yaml
pkg/apis/keda/v1alpha1/triggerauthentication_types.go

`kubect get ta` prints these columns:
```bash
NAME     PODIDENTITY   SECRET   ENV
taname   azure                  
```
Fixes #778

[v2] triggerauth CRD: show configured parameters

---

cmd/manager/main.go
deploy/12-operator.yaml
deploy/22-metrics-deployment.yaml

Adding liveness and readiness probes for KEDA Operator and Metrics Server
Fixes #788

[v2] adding liveness and readiness probes

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

When using the RabbitMQ Scaler's `includeUnacked` setting to `true` I noticed the message count appeared to be off when I added some logging of the value of the external metric (the total message count).  The value (message count) appeared to be double counting the unacknowledged message count. The current logic (before this PR) is to include the `messages` (count) in addition to the `messages_unacknowledged` (count). It appears that the HTTP Management URI `messages` attribute already includes the unacknowledged messages in it's value. Here is an example of some  json from the HTTP Management URI:
```
"messages": 498,
"messages_details": {
"rate": 0
},
"messages_paged_out": 0,
"messages_persistent": 498,
"messages_ram": 498,
"messages_ready": 496,
"messages_ready_details": {
"rate": 0
}, …
```

Adjusting the message count logic when using includeUnacked

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

Fix support of blank path without trailing slash for RMQ HTTP scaler

---

README.md

Looks like the deployment docs link changed on keda.sh. Updating to fix broken link.

Fixing link to deployment documentation

---

README.md

The link get's resolved as https://github.com/kedacore/keda/blob/master/kubernetes.slack.com/messages/CKZJ36A5D instead of https://kubernetes.slack.com/messages/CKZJ36A5D

fix link to keda slack channel

---

deploy/crds/keda.sh_scaledobjects_crd.yaml
pkg/apis/keda/v1alpha1/scaledobject_types.go
pkg/apis/keda/v1alpha1/zz_generated.deepcopy.go
pkg/controller/scaledobject/hpa.go
pkg/controller/scaledobject/scaledobject_controller.go
pkg/util/k8sversion.go

Adding support for configurable scaling behavior in HPA which was introduced in v2beta2 in kubernetes 1.18
On kubernetes < 1.18 is this option ignored
Fixes #802

[v2] support HPA configurable scaling behavior on k8s >= 1.18

---

README.md

Update links to keda.sh to go to latest docs.
Relates to https://github.com/kedacore/keda-docs/issues/174

Update links to keda.sh to go to latest docs

---

tests/scalers/prometheus.test.ts

Adding a Prometheus End to End Test file using the `http_requests_total` metric (similar to what is provided in the documentation).  The test will generate two test deployments of the same image - one deployment to remain up (static 1 replica) at all times so metrics can be scraped, the other deployment is tied directly to the KEDA HPA and can be scaled to zero. The test that scales up will then use Apace Bench to generate requests that are tied to the ScaledObject trigger for Prometheus and should max out the HPA then cooldown to zero.

Prometheus e2e

---

tests/scalers/prometheus-deployment.yaml
tests/scalers/prometheus.test.ts

Fixes #
Failed e2e Prometheus test due to Helm failure. The Prometheus e2e test file is now using a file reference for the Prometheus deployment. @ahmelsayed Does this look good?

Changing the Prometheus e2e to use a file for the Prometheus deployment

---

tests/scalers/prometheus.test.ts

Fixes #
Prometheus e2e - Giving time for the test-app container to pull and load before the tests start. I believe this is why the assertion failed in the prior PR - the pod was not ready because the container was still pulling.

Adding a wait for the test app deployment to start up on initialization

---

tests/setup.test.ts

The issue prevents KEDA Operator to start -> to run e2e correctly

[v2] fix e2e - deploy ScaledJob CRD

---

tests/cleanup.test.ts

Cleanup script shouldn't try to delete `keda-auth-reader` role in `keda` namespace, it is correctly deleted later in the script in `kube-system` namespace

Minor e2e fix: keda-auth-reader role is deleted in kube-system namespace

---

deploy/10-cluster_role.yaml

In case we are scaling a CustomResource (eg. Argo Rollout), we need to get environment variables from containers that are inside. To allow that we need to modify RBAC.

[v2] rbac: allow get on any object

---

Makefile

`keda-nightly-run` got sick during an upgrade for some reason. I created another one (`keda-nightly-run-2`) to use for now until I can follow up with support about what happened there. This PR allows that setting to overridden through environment variables
- [ N/A] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ N/A ] Tests have been added

Allow setting test cluster name through env

---

tests/scalers/prometheus-deployment.yaml
tests/scalers/prometheus.test.ts

Fixes:
I noticed that I was not validating that the Prometheus server was up and running so I have added an assertion for it's deployment. The Prometheus deployment itself was incorrectly using a PVC so that was removed from the deployment in case that is causing an issue on the remote cluster the End to End tests are running in.  Additionally, I changed the HTTP request generation to be less impactful load at once and more spread out over time so there is more consistent and steady load for Prometheus to scrape.

Prometheus Server Deployment and Load Generation Changes

---

pkg/scalers/azure/azure_eventhub.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go

eventhub-scaler can scale even when no storage checkpoint exists. 
To scale up without checkpoint, the first calculation based only on eventhub partition infos. The tricky part was to differentiate between a partition without messages and exactly 1 unprocessed message. 
Fixes #797

eventhub-scaler works on new hubs where initially no storage checkpoint exists

---

.github/workflows/release-build.yml
RELEASE-PROCESS.MD

Automatically attach packaged deployment YAMLs to GitHub Release as part of our release workflow.
Fixes #764

Automatically attach packaged deployment YAMLs to GitHub Release

---

tests/setup.test.ts

ScaledJob CRD validation errors on some k8s version prevents KEDA operator to start before e2e tests. We can ingore those errors because ScaledJob is not implemented yet.

[v2] during installation ignore ScaledJob CRD validation erros

---

build/Dockerfile.tz
build/bin/user_setup
go.mod
go.sum
pkg/handler/scale_handler.go
pkg/scalers/cron_scaler.go
pkg/scalers/cron_scaler_test.go

Signed-off-by: Chaitanya Kuduvalli Ramachandra <chaitanya.r@ETC02Y77ZVJG5H.local>
Addition of Cron Scaler to KEDA to scale based on a particular cron schedule.
Fixes #812

Adding Cron Scaler to KEDA

---

.github/workflows/fossa.yml
pkg/scalers/mysql_scaler.go
tools/build-tools.Dockerfile

Fixes https://github.com/kedacore/keda/issues/808
Signed-off-by: Ihor Dvoretskyi ihor@linux.com

FOSSA license scanning GitHub Action added

---

go.mod
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

[RabbitMQ Scaler documentation ](https://keda.sh/docs/1.4/scalers/rabbitmq-queue/#trigger-specification) mentiones that `queueLength` should be optional with default value `20`, but the actual code doesn't reflect this.
Fixes #880

RabbitMQ: make queueLength optional

---

pkg/scalers/gcp_pub_sub_scaler.go
pkg/scalers/stackdriver_client.go

GCP Pub Scaler should not panic on invalid credentials
Fixes #616

GCP Pub Scaler should not panic

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Fixes: #632 
Signed-off-by: Samuel Macko <samuel.macko.sm@gmail.com>
Fixes #

[v2] removed deprecated brokerList

---

pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go

As mentioned by @ericbottard in issue #373, the kafka- and liiklus-scaler cap the number of replicas based on the number of partitions.
I think this is also important for the eventhub-scaler, which acts very similar like kafka. I suggest to adopting the same logic here.

eventhub-scaler calculate total metric count related to partitions like kafka scaler

---

deploy/12-operator.yaml
deploy/22-metrics-deployment.yaml

Setting default resource requests and limits, we can use this as a base and modify later, if we have a better value.
There should be limits set to avoid draining node resources etc. As discussed in https://github.com/kedacore/keda/issues/53

[v2] set default resource requests and limits

---

Makefile
deploy/crds/keda.sh_scaledjobs_crd.yaml
deploy/crds/keda.sh_scaledobjects_crd.yaml
deploy/crds/keda.sh_triggerauthentications_crd.yaml

Operator-sdk by default generates CRDs in `v1` since operator-sdk v0.18. We should stick to `v1beta1` until we decide that we want to move to `v1` as it is discussed in https://github.com/kedacore/keda/issues/701

[v2] enforce generation of CRDs in v1beta1 version

---

deploy/crds/keda.sh_scaledjobs_crd.yaml

We need to manually modify generated ScaledJob CRD, to be able to deploy it on k8s v 1.18. 
There were validation improvements brought in k8s 1.18 and operator-sdk is not able to generate the CRD correctly. 
Issue details: https://github.com/kedacore/keda/issues/927
This should help with e2e tests failures on v2 branch

[v2] temporary fix to be able to deploy ScaledJob on k8s 1.18

---

.devcontainer/Dockerfile

When I tried DevContainer, It failed. I investigate the root cause is the `golangci-lint` install failed.
According to the official documentation, they don't recommend to install with `go get` instead they recommend, binary install. so that I change it to the binary install now it works fine. 
https://golangci-lint.run/usage/install/
- [-] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [-] Tests have been added
This is a PR for the bug fix of Dockerfile. these are N/A. I don't know if I satisfy DCO. I'll try to create a PR and have a look at the test.
Fixes #
No issue written. Small fix.

Fix DevContainer Build issue

---

pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Signed-off-by: grassiale <alessandro.grassi01@gmail.com>
This PR is aimed at solving how Keda Kafka scaler handles the absence of committed offset with relation to the offset policy the consumer is following.
At the moment, if you create a scaledobject for a new consumer group having no committed offset, keda scaler will return a lag value equal to the latest offset in the topic it is consuming from. This often causes the scaler to scale relative deployment replicas to the max, because the latest offset in the topic is probably higher than the lagTreshold. This is fine for consumers having auto.offset.reset=earliest, since they will start to consume right-away all the messages in the topic; but is wrong for 
auto.offset.reset=latest consumers, that will only consume new messages on the …

[v2]adds consumer offset reset policy option to keda kafka scaler

---

pkg/apis/keda/v1alpha1/scaledjob_types.go
pkg/apis/keda/v1alpha1/zz_generated.deepcopy.go

Remove MinReplicaCount and CooldownPeriod since it is not necessary for the scaled job. 
- [-] Tests have been added (run existence test and works fine)
Fixes #
https://github.com/kedacore/keda/issues/955

[v2] Remove  MinReplicaCount and CooldownPeriod from scaled job

---

README.md

CNCF logo should be smaller in README

CNCF logo should be smaller in README

---

pkg/scalers/redis_scaler.go
pkg/scalers/redis_scaler_test.go
tests/scalers/redis-lists.test.ts

Adding the ability to specify the `address` or `host` and `port` attributes as values in a secret via the TriggerAuthentication resource for the Redis Lists scaler.  This avoids having to specify them as env vars in the deployment itself. I have added additional e2e tests for the uses of these parameters.
Added documentation updates in https://github.com/kedacore/keda-docs/pull/216

Redis Lists - Connection Parameters

---

.github/workflows/v2-build.yml
deploy/crds/keda.sh_scaledjobs_crd.yaml

The current e2e running on v2 as part of build action [is failing](https://github.com/kedacore/keda/runs/954078597), because before the e2e tests, ScaledJob CRD is regenerated and this generated CRD can't be deployed on k8s v1.18 #927 
We need to manually add some properties to in order to deploy this CRD on cluster. 
For now I am replacing the generated CRD with the original one to enable the deployment, till #927 is fixed.

[v2] don't use generated ScaledJob CRD in e2e tests

---

CHANGELOG.md
deploy/crds/keda.sh_scaledobjects_crd.yaml
pkg/apis/keda/v1alpha1/scaledobject_types.go
pkg/apis/keda/v1alpha1/zz_generated.deepcopy.go
pkg/controller/scaledobject/scaledobject_controller.go
pkg/controller/scaledobject/scaledobject_finalizer.go
tests/scalers/azure-queue-restore-original-replicas.test.ts

Adding option to enable restoring to the original replica count after ScaledObject is deleted. The default behavior is the same as the current one, ie. the replicas count remain on the same number.
Fixes #947

[v2] add option to restore to original replica count after ScaledObject's deletion

---

pkg/scalers/cron_scaler.go
pkg/scalers/postgresql_scaler.go
pkg/scalers/rabbitmq_scaler.go

Signed-off-by: Nikhil Bhargava <993682+nbhargava@users.noreply.github.com>
Jobs are only created and scaled based on the value of the metric with name "queueLength". In most Scalers, the metric is calculated and assigned the inputted name, but this is not the case for all Scalers. This PR makes this consistent across scalers.
Fixes #974

[v2] Use input metric name consistently when reporting Job metrics

---

Makefile
tests/package.json
tests/scalers/azure-blob.test.ts
tests/scalers/kafka.test.ts
tests/scalers/mysql.test.ts
tests/scalers/redis-lists.test.ts
tests/setup.test.ts

This fixes a couple of tests for v2, however the following tests are still failing. 
I think this is failing because of the changes from https://github.com/kedacore/keda/pull/925. The scaler is always returning false. I spent sometime debugging it, but I'm not sure I understand the reasoning [behind this part?](https://github.com/kedacore/keda/blob/ff053e03261148d8005fc40b39b61bf9e3725d9c/pkg/scalers/kafka_scaler.go#L304-L328)
I think these 2 are failing because of the change in #966 (/cc @samuelmacko)
```json
{
"level":"error",
"ts":1597102313.4967065,
"logger":"controller",
"msg":"Reconciler error",
"controller":"scaledobject-controller",
"name":"prometheus-scaledobject",
"namespace":"prometheus-test",
"error":"HorizontalPodAutoscaler.autoscaling \"keda-hpa-prometheus-scaledobject\" is …
```

update tests for v2

---

pkg/scalers/artemis_scaler.go
pkg/scaling/scale_handler.go

This PR has fixes for a bugs I faced with during deployment and setting up a scaler.
Also, I want to introduce additional metadata parameter "restApiTemplate" that address the following problem:
As of now, REST API url to get a queue size is hardcoded and looks like this:
`"http://<<managementEndpoint>>/console/jolokia/read/org.apache.activemq.artemis:broker=\"<<brokerName>>\",component=addresses,address=\"<<brokerAddress>>\",subcomponent=queues,routing-type=\"anycast\",queue=\"<<queueName>>\"/MessageCount"`
But there can be a cases, when a template is different. As an example, my endpoint looks like this:
`"http://<<managementEndpoint>>/api/jolokia/read/org.apache.activemq:type=Broker,brokerName=<<brokerName>>,destinationType=Queue,destinationName=<<queueName>>/QueueSize"`
There is other …

[v2] BugFix and Updates for Artemis ActiveMQ scaler

---

Makefile
tests/cleanup.test.ts
tests/setup.test.ts

Use `make deploy` and `make undeploy` in e2e tests setup/cleanup.

[v2] fix e2e tests to use the new deployment style

---

tests/cleanup.test.ts
tests/setup.test.ts

Quick fix, I overlooked that the setup files are called from `./tests` directory, ie. `make deploy` from this dir is not working. We need to call the Makefile from the project root directory.

[v2] e2e fix: run Makefile from the project root directory

---

CHANGELOG.md
pkg/scalers/redis_scaler.go

added support for multiple redis "list" types scaling, including : zset,hash,set and list
Fixes #

[v2] add support for multiple redis list types in redis list scaler 

---

pkg/scaling/scale_handler.go

Minor optimization, in case there are multiple scalers in ScaledObject, we can end the loop for checking scaler's status after the first Active one.

[v2] don't inspect other scalers if one is active

---

Dockerfile
Dockerfile.adapter
go.mod
pkg/scaling/executor/scale_jobs.go
tools/build-tools.Dockerfile

Go 1.15 was [released](https://blog.golang.org/go1.15) and brings some nice internal optimizations, I think it is good time to move to the new version

[v2] use go 1.15

---

config/rbac/role.yaml
controllers/scaledobject_controller.go

RBAC we have recently introduced was too strict, the operator couldn't create events:
```
E0828 08:58:41.025190       1 event.go:260] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"operator.keda.sh.162f62e346a5faf6", GenerateName:"", Namespace:"keda", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, …
```

[v2] fix RBAC to allow creating events

---

controllers/hpa.go

In hpa.go, line 109, 122, and old hpa definition is used in update function. Changed to new definition.
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>

[v2] BugFix: HPA doesn't change during reconciling

---

Makefile

Minor fixes:
- cleaning temp file introduced by https://github.com/kedacore/keda/pull/1071
- correcting the sed regex pattern
- cleaning temp file in clientset-generate target as well

[v2] Correcting set-version target & removing temp files produced by sed

---

CHANGELOG.md
pkg/scalers/aws_iam_authorization.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go
pkg/scalers/azure_monitor_scaler.go
pkg/scalers/azure_queue_scaler.go
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/external_scaler.go
pkg/scalers/external_scaler_test.go
pkg/scalers/gcp_pub_sub_scaler.go
pkg/scalers/gcp_pubsub_scaler_test.go
pkg/scalers/mysql_scaler.go
pkg/scalers/mysql_scaler_test.go
pkg/scalers/postgresql_scaler.go
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go
pkg/scalers/redis_scaler.go
pkg/scalers/redis_scaler_test.go
pkg/scalers/redis_streams_scaler.go
pkg/scalers/redis_streams_scaler_test.go
pkg/scaling/scale_handler.go

| Scaler | values | update |
|--------|--------|--------|
| `azure-blob` | `connection` (**Default**: `AzureWebJobsStorage`) | `connectionFromEnv` |
| `azure-monitor` | `activeDirectoryClientId` <br /> `activeDirectoryClientPassword` | `activeDirectoryClientIdFromEnv` <br /> `activeDirectoryClientPasswordFromEnv` |
| `azure-queue` | `connection` (**Default**: AzureWebJobsStorage) | `connectionFromEnv` |
| `azure-servicebus` | `connection` | `connectionFromEnv` |
| `azure-eventhub` | `storageConnection` (**Default**: `AzureWebJobsStorage`) <br /> `connection` (**Default**: `EventHub`) | `storageConnectionFromEnv` <br /> `connectionFromEnv` |
| `aws-sqs-queue` <br /> `aws-cloudwatch` <br /> `aws-kinesis-stream` | `awsAccessKeyID` …

[v2] add FromEnv suffix to metadata resolved from env

---

pkg/scalers/kafka_scaler.go
tests/scalers/kafka.test.ts

Hello, while implementing the e2e tests requested here: https://github.com/kedacore/keda/pull/985
I've come across a new issue that is not making the scaler behave correctly when the offset reset policy is set to latest (default).
When a new consumer is created, meaning it has no offsets committed, the sarama offset fetch will return a value of -1 for all the partitions of the topic it consumes from. If we set the lag to 0, as in the previous solution, the isActive method will always return false resulting in the scaling to never occur even if new messages are written in the topic.
In order to fix this, I propose the following: 
1. return sarama.OffsetNewest (-1) when the new consumer with latest policy has no committed offset, for every partition.
2. This will result to have a negative …

[v2] Kafka scaler isactive latest

---

CONTRIBUTING.md

It seems that the GOVERNANCE.md file is not linked anywhere in
common files like README or CONTRIBUTING.
Fixes #

Add link to GOVERNANCE.md in CONTRIBUTING.md

---

.github/workflows/pr-validation.yml
.pre-commit-config.yaml
Makefile
go.mod
go.sum
revive.toml

The golint linter is an abandoned project. Also, it is highly opinionated thus it does not allow any configuration. As discussed in https://github.com/kedacore/keda/pull/1088#discussion_r484253257, I would like to propose to migrate to https://github.com/mgechev/revive why?
- it allows configuration via .toml file
- it allows inline disables of checks
- is used by other projects: https://github.com/mgechev/revive#who-uses-revive (including grafana)
Relates to:
#1057
#1056
#1054

Use revive instead of golint

---

README.md

No strong opinion here but I think centering CNCF logo may look slightly better:
Before
After
Fixes #

Center CNCF logo in README

---

Makefile

`vendor` dir is sometimes populated during a build. It is being ignored by git, but `revive` should ignore it as well, to prevent failures from vendored packages.

[v2] revive should ignore vendor dir

---

CHANGELOG.md
pkg/scalers/gcp_pub_sub_scaler.go
pkg/scalers/gcp_pubsub_scaler_test.go

Small fix: closing StackDriver client in the GCP PubSub scaler. 
Fixing issue raised in https://github.com/kedacore/keda/issues/1062#issuecomment-686367321

[v2] Improved GCP PubSub Scaler performance by closing the client correctly

---

Makefile

We don't need to generate protobuf code for LiiklusService in each `make build`.
The building of LiiklusService might be obsolete anyway, I have created a separate issue to update this: https://github.com/kedacore/keda/issues/1097

[v2] Don't generate LiiklusService in each build

---

Dockerfile
Dockerfile.adapter

Refactoring Dockerfiles, that they can share layers between KEDA Operator and Metrics Server image, this should speed up the build a little bit (which is currently quite slow, due to the multistage build & builder image use).

[v2] refactor Dockerfiles that they can share layers

---

.github/workflows/pr-validation.yml
Dockerfile
Dockerfile.adapter
go.mod
go.sum
tools/build-tools.Dockerfile

- go 1.15.1 was released (CGI related security fixes) https://golang.org/doc/devel/release.html#go1.15
- updating deps

[v2] go 1.15.1 & bump deps

---

pkg/scaling/executor/scale_scaledobjects.go

Minor bugfix.
If `e.getScaleTargetScale(ctx, scaledObject)` returns error, we should return from this function, to not operate on a possibly not initialized `currentScale` property -> that would result in panic.

[v2] return from RequestScale() in case of error

---

controllers/scaledjob_controller.go
controllers/scaledobject_controller.go

Minor improvement, changing the Controllers log messages, originally they contain `Request.Namespace` and`Request.Name` which is being changed to `ScaledObject/ScaledJob.Namespace` and `ScaledObject/ScaledJob.Name`
Example:
`controllers.ScaledObject	Reconciling ScaledObject	{"Request.Namespace": "default", "Request.Name": "test-scaledobject"}`
->
`controllers.ScaledObject	Reconciling ScaledObject	{"ScaledObject.Namespace": "default", "ScaledObject.Name": "test-scaledobject"}`

[v2] improving controllers log msgs

---

pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/redis_scaler.go
pkg/scalers/redis_scaler_test.go

Signed-off-by: aman-bansal <bansalaman2905@gmail.com>
This PR fixes the performance issues in scalers implementations. The thing is many scalers client's implementation hasn't been closed properly. 
Fixes #1096

fix[v2]:fixing performance issues in scaler where clients are not closed properly

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Splitting Kafka Auth mode to a separate sections for SASL and TLS. This is IMHO more convenient.
Fixes https://github.com/kedacore/keda/issues/1043

[v2] Kafka: split metadata and config for SASL and TLS

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go
tests/scalers/rabbitmq-queue-http.test.ts

Consolidate apiHost & host for RabbitMQ scaler
Relates to #711

[v2] Consolidate apiHost & host for RabbitMQ scaler

---

CHANGELOG.md
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/azure_servicebus_scaler_test.go

Rename `queueLength` to `messageCount` for Azure Service Bus scaler since this is confusing when using topics.
I'll open a doc PR when this is agreed and merged. ([depends on this PR as well](https://github.com/kedacore/keda-docs/pull/251))
Relates to #1109

Rename `queueLength` to `messageCount` for Azure Service Bus scaler

---

Makefile

When we are doing release (ie. `make release`), a version in version.go wasn't updated, because the proper make target wasn't called. Therefore the version displayed in pods logs wasn't correct (it shows `v2` instead of `2.0.0-beta` for the Beta release).

update version.go properly during make release

---

.golangci.yml
Makefile
pkg/scalers/artemis_scaler.go
pkg/scalers/azure/azure_monitor_test.go

enable gofmt,golint for golangci, and fix lint errors. 
gofmt  file `pkg/scalers/azure/azure_monitor_test.go`
```
gofmt -w -s pkg/scalers/azure/azure_monitor_test.go 
```
Fixes #

enable gofmt,golint and fix lint errors

---

.github/workflows/master-build.yml
.github/workflows/nightly-e2e.yml

This fix is related to this bug: https://github.com/kedacore/keda/issues/1150
The problem is that "TEST_LOG_ANALYTICS_WORKSPACE_ID" env. variable not exposed in "nightly-e2e.yml" and "master-build.yml"
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>

BugFix: Azure Log Analytics E2E test failed.

---

CHANGELOG.md
tools/build-tools.Dockerfile

operator-sdk v1.0.1

---

tests/package-lock.json
tests/package.json

Update test dependencies to mitigate security vulnerabilities (CVE-2020-7720 & GHSA-p9pc-299p-vxgp).
I haven't run the tests so will rely on the CI

Update test dependencies to mitigate security vulnerabilities (CVE-2020-7720 & GHSA-p9pc-299p-vxgp)

---

controllers/scaledobject_controller.go
pkg/util/k8sversion.go
pkg/util/k8sversion_test.go

k8s version wasn't correctly resolved if `len(Minor) <= 2` 
For example: `18+` vs `19` or `18`
Adding tests
Fixes #1176

resolve k8s Minor version correctly

---

CHANGELOG.md
Makefile
config/crd/bases/keda.sh_scaledjobs.yaml
config/crd/bases/keda.sh_scaledobjects.yaml
config/crd/bases/keda.sh_triggerauthentications.yaml

Moving the KEDA CRDs to v1, that means supporting only Kubernetes >= 1.16
Fixes https://github.com/kedacore/keda/issues/701

CRDs: use apiextensions.k8s.io/v1

---

pkg/scaling/resolver/scale_resolvers.go
pkg/scaling/scale_handler.go

Signed-off-by: Ang Gao <ang.gao87@gmail.com>
Patches to avoid exception when CRD doesn't follow Pod spec shape
Fixes #1194

Avoid exception when CRD doesn't follow Pod spec shape

---

pkg/scaling/scale_handler.go

I discuss with @ahmelsayed , There is no usecase for ScaledJob to enalbe Extrenal Push Scalers. 
So we decided to go with just add warning in case customer set it. 
Fixes #
https://github.com/kedacore/keda/issues/1035

Set warning for External Push Scaler for ScaledJob

---

pkg/scalers/azure_log_analytics_scaler.go
pkg/scalers/azure_log_analytics_scaler_test.go
pkg/scaling/scale_handler.go

This PR to address an AAD throttling limitation (200 AAD requests per 30 secs).
in memory cache to store AAD tokens has been introduced. So now, tokens will not be requested for each pooling interval. Instead, they will be stored in memory and refreshed once expired.
Also, log messages has been updated to follow the same messaging pattern and provide more information on error occured.
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>

[v2]. Azure Log Analytics scaler: solve AAD throttling limitation. Changed log messages.

---

pkg/scalers/kafka_scaler.go
pkg/scalers/metrics_api_scaler.go
pkg/scalers/metrics_api_scaler_test.go
pkg/util/tls_config.go

Signed-off-by: aman-bansal <bansalaman2905@gmail.com>
This PR is to add authentication for metric_api_scaler. Three methods have been added. They will be identified on the basis of `authMode` parameter.
1. API Key Based auth: auth mode would `apiKeyAuth`. API key needs to be provided. Default behaviour would be to send it in headers. This can be changed via method and header/query param keys can be changed via keyParamName.
2. Basic Auth: auth mode would `basicAuth`. Username is compulsory. Password isn't. This is based on experience over basic auth. Some people just put api key as the username to ease out authentication at their end.
3. Client Certification: auth mode would `tlsAuth`. cert, cacert and key needs to be provided.
Relates to #1082 #1083 #1084 
[Edit]
Docs PR attached …

feature[v2]: enabling authentication for metric api scaler

---

pkg/scaling/scale_hander_test.go
pkg/scaling/scale_handler.go

Thank you for the bug report on slack. 
https://kubernetes.slack.com/archives/CKZJ36A5D/p1602028423055600
Target Average Value was wrong for the Scaled Jobs if they use multiple triggers. 
I tested by ServiceBus scaler. 
https://github.com/TsuyoshiUshio/sample-go-servicebus-queue
- [-] Tests have been added

fix: ScaledJob Target Average Value

---

.golangci.yml
api/v1alpha1/triggerauthentication_types.go
pkg/scalers/artemis_scaler.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_log_analytics_scaler.go
pkg/scalers/liiklus_scaler.go
pkg/scaling/resolver/hashicorpvault_handler.go
pkg/scaling/scale_handler.go

Adding ineffassign and staticcheck linter together because they both have some overlapping checks.
Looks like `PodIdentityProvider*` constants were all meant to be of `PodIdentityProvider` type, but this was missed. For now I worked around this by adding a couple of type casts. Should I instead propagate this change and use `PodIdentityProvider` instead of `string` for pod identity everywhere?
Part of #1158

Enable gloangcilint: ineffassign, staticcheck

---

CHANGELOG.md
tests/README.md
tests/package.json
tests/scalers/argo-rollouts.test.ts

Signed-off-by: Ang Gao <ang.gao87@gmail.com>
Add Argo Rollouts e2e test, followed prometheus.test.ts as an example
Fixes #1234

Add Argo Rollouts e2e test

---

.golangci.yml
controllers/util/status.go
pkg/scaling/scale_handler.go

Signed-off-by: akartasov <agneum@gmail.com>
Enables golangci-lint for interfacer and staticcheck.
Fixes #1158

enable golangci-lint: interfacer, staticcheck (#1158)

---

pkg/scalers/gcp_pub_sub_scaler.go

With the help of @OrenLederman , we found the root cause of the memory leak of https://github.com/kedacore/keda/issues/1257
The root cause is GCP scaler instantiate client for every `GetMetrics()` call.  
I avoid to instantiate every time, then the big memory leak has gone. 
However, there is tiny memory leak happens probably not on GCP Scaler. 
I'll test by running keda several days and see if it is harmful or not with a Profiler.  
Fixes #
https://github.com/kedacore/keda/issues/1257

Fix Memory Leak Issue of GCP PubSub

---

pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

This PR removes some validations from the TriggerAuthentication derived config for kafka. This allows you to use TLS without needing to specify a CA/cert/key. It was tested with an AWS MSK Kafka cluster. I haven't yet completed the checklist, but happy to do so.
Later validations in the shared TLS config allow us to just pass through the empty strings here when not specified.

Remove Kafka scaler requirement for CA/cert/key

---

CHANGELOG.md
pkg/scalers/gcp_pub_sub_scaler.go
pkg/scalers/gcp_pubsub_scaler_test.go

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>
Relates to #1273

Adding auth trigger to pubsub

---

README.md

Move community standup to bi-weekly Tues 16:00 UTC which takes affect as of Nov 9th with our first standup on Nov 10th.
Relates to https://github.com/kedacore/keda/issues/1269

Move community standup to bi-weekly Tues 16:00 UTC

---

.github/workflows/release-build.yml

We should make the release and change version string in the [code](https://github.com/kedacore/keda/blob/a9e118f76d846a87d19d224a858009e7650f2fc5/version/version.go#L5) before publishing the images (so they contain the updated version string, which is then shown in the KEDA logs)

make release+set version before publishing images

---

CHANGELOG.md
pkg/scalers/aws_iam_authorization.go

When getting the ACCESS_KEY_ID for AWS from Environment variables (which is currently the only working option), the `aws_iam_authorization` scaler would check if metadata.awsAccessKeyIDFromEnv was set, but it would then utilize the metadata.awsAccessKeyId for the name... while in the secretAccessKey it would then use the `FromEnv` one. This fixes that
Fixes #

Wrong aws_iam_authorization access key id setting

---

CHANGELOG.md
pkg/scaling/executor/scale_jobs.go

Signed-off-by: mosesyou <mosesyou1994@gmail.com>
This PR is about to add ScaledJob's label to its job.
Fixes #1311

add ScaledJob's label to its job

---

.devcontainer/devcontainer.json

Signed-off-by: Girish Ramnani <girishramnani95@gmail.com>
As part of https://github.com/kedacore/keda/issues/1114, use the latest `golang.go` id for golang plugin for vscode in the devcontainer.json
Fixes https://github.com/kedacore/keda/issues/1114

use the latest extension id for golang in devcontainer.json

---

CONTRIBUTING.md

Signed-off-by: Girish Ramnani <girishramnani95@gmail.com>
The current link to community standup in `contributing.md` seems to be pointing to a non-existent section in `README.md`, so changed that.
- link https://github.com/kedacore/keda-docs/pull/308 
No issue

resolve broken link to community standup section in contributing.md

---

.github/workflows/pr-validation.yml

Signed-off-by: Girish Ramnani <girishramnani95@gmail.com>
Currently observing this error in the `Static Checks` CI step due to use of `v2-beta` setup-go version. Updating that to `v2`
CI should pass

update the setup-go step from v2-beta to v2

---

CHANGELOG.md
go.mod
go.sum
pkg/scalers/azure/azure_eventhub.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go

This PR adds support for Pod Identity for Event Hub. Users will be able to use Pod Identity instead of depending on supplying a connection string. But this also means that they have to supply EventHubNamespace and EventHubName explicitly. 
- [ ✅] Commits are signed with Developer Certificate of Origin (DCO)
- [ ✅] Tests have been added
- [ ✅] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ ✅] Changelog has been updated

Eventhub podidentity

---

pkg/scaling/scale_handler.go

Signed-off-by: Lionel Villard <villard@us.ibm.com>
When `scaleTargetRef` references a CRD, the `secretTargetRef` section in `TriggerAuthentication` is ignored. This PR fixes it by not ignoring it.

Resolve authenticationRef for CRD target ref

---

.golangci.yml

Signed-off-by: Shubham82 <shubham.kuchhal@india.nec.com>
This PR enable depguard and  dogsled linters in golangcli.yml.
PartiallyFixes #1158

Enbale depguard and dogsled Linters in .golangcli.yml

---

CHANGELOG.md
pkg/scalers/postgresql_scaler.go
pkg/scalers/postgresql_scaler_test.go
pkg/util/normalize_string.go

Added `metricName` as an optional meta field to the Postgres scaler. When not provided one is generated as before but with passwords masked as `xxx`
Issue #1200

Postgres: optional metricName & mask passwords

---

.pre-commit-config.yaml
Dockerfile
Dockerfile.adapter
Makefile

Since we have code quality checks on the `v2` branch, they will run prior to any docker build operation. That means that the `go fmt` and `go vet` calls inside the Dockerfile are redundant. This change removes them by creating two new makefile targets: `adapter-dockerfile` and `manager-dockerfile`, and changing the adapter and manager dockerfiles to call those two targets, respectively. 
This patch also adds `go vet` to the pre-commit config file.
**Question: should we add go vet to the golangci config file? This way, we can avoid running `go fmt` and `go vet` explicitly in the pre commit file, as it'll be done automatically by the pre-commit golangci hook**
Fixes #1070
Notes about TODOs:
- Tests don't need to be added here
- No docs updates needed as well
**Not sure about the changelog**

Not running govet or gofmt in Dockerfile builds

---

CHANGELOG.md
pkg/scaling/executor/scale_jobs.go
pkg/scaling/executor/scale_jobs_test.go

Signed-off-by: Thomas Lamure <thomas.lamure@eridanis.com>
When using the accurateScalingStrategy, if a job's pod takes time to be created or started, this PR will prevent multiple jobs to be requested instead of one.
The reason for the pod start delay may be multiple, pulling new image, scaling cluster...
This PR is a port of the code from #639 that I have been using in Keda V1 since the mentioned PR.
- (NOT NEEDED)A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
Fixes kedacore/keda#1323

Implements PendingJobCount to fix kedacore/keda#1323

---

.github/ISSUE_TEMPLATE/Bug_report.md

Add section on KEDA operator logs for bug template.

Add section on KEDA operator logs for bug template

---

CHANGELOG.md
pkg/scaling/scale_handler.go

Signed-off-by: Maxence Boutet <mboutet@explorance.com>
In [`checkScaledObjectScalers`](https://github.com/kedacore/keda/blob/76fb858175075ab21328ebdf3726d6d1f7af064c/pkg/scaling/scale_handler.go#L200), as soon as one active scaler is encountered, all the remaining scalers are not closed leading to ever increasing memory usage. This PR ensures that all the remaining scalers are closed after one active scaler has been found.
Fixes #1413

Ensure that all scalers are closed

---

pkg/metrics/prometheus_metrics.go
pkg/scalers/artemis_scaler.go
tests/scalers/influxdb.test.ts

I added some comments below to explain the changes. However, influxdb test is still failing. It's failing to scale beyond 1 replica, and I see this error from the metrics server
```
E1215 07:57:59.134382       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"No matching metrics found for influxdb-my-org-1608019063"}
E1215 07:58:14.170619       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"No matching metrics found for influxdb-my-org-1608019079"}
```
not sure if it's related, but haven't looked further into this one yet. 
- [N/A ] Changelog has been updated

fixes for tests

---

pkg/scalers/influxdb_scaler.go
pkg/scalers/influxdb_scaler_test.go

Before the organization name suffix was added even if the metric name was specified by user.

influxdb: fix metric name generation

---

CHANGELOG.md
controllers/scaledobject_controller.go

Adds an in-memory cache to speed up reconciles. With large numbers of scaled objects I'm seeing a ton a request throttling (#1449) that I _think_ (but won't be sure until I try deploying this and seeing if it goes away) is related to these scale requests on every reconcile. The better solution would be for controller-runtime to support access to the scale subresource (https://github.com/kubernetes-sigs/controller-runtime/issues/172) so these requests could hit the local informer cache or something, but that's got a lot of problems itself so I think this solution is a good step for now.

Add a cache for what resource types are scalable so not every reconcile has to do a GET to the /scale endpoint

---

.github/dependabot.yml

Weekly candence was imho too much, monthly is sufficient for us, as we do not release that often.

Change dependabot check interval to monthly

---

CHANGELOG.md
main.go

Signed-off-by: Colton Herinckx <herinckc@gmail.com>
This PR adds operator support for the `WATCH_NAMESPACE` environment variable; while the adapter currently supports this env var it seems as though the operator itself does not
Let me know if I need to update any tests or docs along with this PR. I didn't see any operator-specific tests or any mention of the `WATCH_NAMESPACE` env var in the keda-docs repo so I haven't done anything for either of those tasks but I'm happy to make more changes if I've missed anything
Addresses https://github.com/kedacore/keda/issues/601#issuecomment-750534901

Update operator to support the WATCH_NAMESPACE env var

---

pkg/scalers/azure_log_analytics_scaler.go
tests/run-all.sh
tests/scalers/azure-queue-restore-original-replicas.test.ts
tests/scalers/azure-queue-trigger-auth.test.ts
tests/scalers/azure-queue.test.ts
tests/scalers/mysql.test.ts

- Fix the image name used for azure queue tests
- Fix a nil dereference error in azure_log_analytics_scaler.go 
- limit concurrent test runs to 10

Limit concurrent e2e tests to 10

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

And support setting the protocol via TriggerAuthentication since if overriding host, you will probably want that too at some point (if the new auto-detection doesn't handle it for you).

Automatically determine the RabbitMQ protocol when possible

---

tests/run-all.sh
tests/scalers/argo-rollouts.test.ts

- argo rollout test -  no need to log Argo installation resources, they are pretty huge and making the log unnecessary long
- minor edit in the result print message

minor e2e tests tweaks

---

CHANGELOG.md
pkg/scaling/scale_handler.go

In https://github.com/kedacore/keda/pull/1457 we have overlooked a small problem, Kubernetes Resource was used to reference the name of the target workload. ie. if we were scaling `Deployment` a string `deployments` was used to reference the name.
Thus scaling is not working, see the log:
```
keda-operator-84f7687cfc-qtkch keda-operator 2021-01-06T11:36:51.713Z	INFO	controllers.ScaledObject	Detected resource targeted for scaling	{"ScaledObject.Namespace": "default", "ScaledObject.Name": "hello-scaledobject", "resource": "apps/v1.Deployment", "name": "hello-keda"}
keda-operator-84f7687cfc-qtkch keda-operator 2021-01-06T11:36:51.713Z	INFO	controllers.ScaledObject	Creating a new HPA	{"ScaledObject.Namespace": "default", …
```

Fix scaleTarget name reference when resolving pods

---

CHANGELOG.md
pkg/scalers/openstack/keystone_authentication.go
pkg/scalers/openstack_swift_scaler.go
pkg/scalers/openstack_swift_scaler_test.go
pkg/scaling/scale_handler.go

Signed-off-by: Pedro Dominguite p.dominguite@sidi.org.br
This PR adds a new scaler for the Swift OpenStack object-store.
We are committed to delivering end to end test for this scaler soon.
Related to #1342.

Add OpenStack Swift scaler

---

tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts

Signed-off-by: Deepak <sah.sslpu@gmail.com>
This adds graceful clean-up of redis cluster for `redis-cluster` and `redis-cluster-streams` scalers e2e tests.
Also, fixes names of unavailable resources inside `redis-cluster-lists.test.ts` .

Add graceful cleanup for redis cluster e2e test

---

hack/update-codegen.sh
hack/verify-codegen.sh

At some environments (eg. GitHub Actions), due to $GOPATH setting, the codegen output might not be at the expected path in the project repo, therefore we should force the output to the specific directory (see --output-base) we need to handle (move) the generated files to the correct location in the repo then.
Without this change, we weren't able to catch neccessary updates in the generated code (for example as in #1486).

fix codegen generation a verification on GH Actions

---

CHANGELOG.md
pkg/scalers/prometheus_scaler.go

Signed-off-by: Suresh Kumar <sureshkumar.pp@gmail.com>
When there is a typo or some other error in prometheus query, prometheus server returns
non-2xx response, which is being ignored silently. This checks for response
code and returns appropriate error

prometheus scaler: handle errors from Prometheus server

---

go.mod
go.sum
pkg/scalers/mongo_scaler.go
pkg/scalers/mongo_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/mongodb.test.ts

Signed-off-by: carson <carson_192@163.com>
_This PR adds a new scaler for the mongo._
Related to #1465.

Add MongoDB scaler

---

pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/cpu_memory_scaler.go
pkg/scalers/redis_scaler.go
pkg/scalers/redis_streams_scaler.go

As per [CodeQL checks](https://github.com/kedacore/keda/security/code-scanning/8?query=ref%3Arefs%2Fheads%2Fmain) there are a couple of incorrect conversions between integer types, I don't think that these parts of the code actually caused any errors (as the parsed int's aren't big enough to overflow the 32bits), but I think that it is proper to fix that.

Fix conversion between integer types

---

Makefile

Very minor nit: Let's cleanup `vendor` after clientset generation/verification, as it is not used anywhere else and may cause problems in other steps.
Related to https://github.com/kedacore/keda/pull/1512#discussion_r560910942

Makefile: cleanup vendor because it is needed only for clientset

---

Makefile

Minor nit related to https://github.com/kedacore/keda/pull/1512
Let's generate the OpenAPi only when running Makefile target related to Metrics Adapter.

Makefile: Generate OpenAPI only when building Metrics Adapter

---

.golangci.yml
pkg/scalers/stackdriver_client.go

` SA1019: package cloud.google.com/go/monitoring/apiv3 is deprecated: Please use cloud.google.com/go/monitoring/apiv3/v2.`

Updating deprecated Stackdriver dependency

---

pkg/scaling/resolver/scale_resolvers.go

logr expects key,value pairs.
Signed-off-by: Suresh Kumar Ponnusamy <suresh.ponnusamy@freshworks.com>
Fix a typo in the log printing, getting below kinds of errors when debug log mode is enabled:
```
2021-01-25T11:05:32.527Z        DEBUG   scalehandler    cannot resolve env %s to a value. fieldRef and resourceFieldRef env are skipped {"type": "ScaledObject", "namespace": "freshcaller", "name": "envoy-blue"}
2021-01-25T11:05:32.527Z        DPANIC  scalehandler    odd number of arguments passed as key-value pairs for logging   {"type": "ScaledObject", "namespace": "freshcaller", "name": "envoy-blue", "ignored key": "NODE_IP"}
github.com/go-logr/zapr.handleFields
/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106
github.com/go-logr/zapr.(*infoLogger).Info …
```

Fix typo in log

---

CHANGELOG.md

Fixed the link for `Automatically determine the RabbitMQ protocol when possible` in CHANGELOG.md under unreleased.

Fix link: Automatically determine the RabbitMQ protocol when possible.

---

config/crd/kustomization.yaml

ClusterTriggerAuthentication CRD was missing in kustomization config, therefore it wasn't generated

Produce ClusterTriggerAuthentication CRD

---

CHANGELOG.md
controllers/hpa.go

Under some conditions (when there was Resource based Trigger with some other Trigger defined in ScaledObject in a specific order) KEDA operator was frequently updating HPA, even when it wasn't needed. See the issue for details
Fixes #1531

Fix unnecessary HPA updates when Resource based Trigger is used

---

Makefile

`ldpath` that's being used for setting KEDA version and Git Commit during the build was pointing to the old path (v1 path), therefore KEDA version and GitCommit wasn't displayed in KEDA Operator/Metrics Server logs. 
This PR is setting the correct path (v2 module).

Use correct v2 module path in Go ldflags

---

tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts

Signed-off-by: Deepak <sah.sslpu@gmail.com>
This adds a delay in redis cluster streams consumer to allow pods to scale. Also, adds a retry loop in case
redis cluster creation fails.
Fixes #1491

Improve redis cluster e2e tests stability

---

CHANGELOG.md
controllers/scaledjob_controller.go
controllers/scaledobject_controller.go
main.go

This was already done in adapter but was missed in manager. Since manager
calls scaler.IsActive() with 0 timeout, it is erring out with "context
deadline exceeded" errors when connection latency is high (like prometheus
scaler trying to contact a prometheus server running in different region)
Signed-off-by: Suresh Kumar Ponnusamy <suresh.ponnusamy@freshworks.com>

Add global http timeout for manager

---

CHANGELOG.md
api/v1alpha1/scaledjob_types.go
config/crd/bases/keda.sh_scaledjobs.yaml

Removed **MIN** field from `kubectl get scaledjob`or` kubectl get sj`
Fixes #1552

Removed MIN field for scaledjob.

---

tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts

Signed-off-by: Deepak <sah.sslpu@gmail.com>
Increase timeout for redis cluster to start up properly during e2e tests.
This also introduces some increased delay while reading/writing redis lists during e2e tests.
Fixes #1491

Increase timeout for redis cluster in e2e tests

---

CHANGELOG.md
go.mod
pkg/scalers/scaler.go
pkg/scaling/scale_handler.go

| before | after |
|--------|-------|
|![before](https://user-images.githubusercontent.com/645740/107080538-497b9500-67a6-11eb-8dd2-0a2851da8d46.png) | ![after](https://user-images.githubusercontent.com/645740/107080554-50a2a300-67a6-11eb-93ec-565d6380fb07.png) |
_after 500 reconciliations for a kafka ScaledObject_
This https://github.com/Shopify/sarama/issues/1321 was the main culprit, though tbh I'm not sure what turning off those metrics affects, I verified that the kafka tests still pass. I also noticed a place where some scalers weren't being closed.  …

Disable sarama metrics and close scalers

---

CHANGELOG.md
adapter/main.go
api/v1alpha1/condition_types.go
controllers/scaledjob_controller.go
controllers/scaledjob_finalizer.go
controllers/scaledobject_controller.go
controllers/scaledobject_finalizer.go
controllers/triggerauthentication_controller.go
go.sum
main.go
pkg/eventreason/eventreason.go
pkg/scaling/executor/scale_executor.go
pkg/scaling/executor/scale_jobs.go
pkg/scaling/executor/scale_scaledobjects.go
pkg/scaling/scale_handler.go

This PR adds the following events:
For both `ScaledObjects` and `ScaledJobs`:
- `Ready`
- `CheckFailed`
- `Deleted`
- `ScalersStarted`
- `ScalersRestarted`
- `ScalersStopped`
For `ScaledObjects`:
- `ScaleTargetActivated`
- `ScaleTargetDeactivated`
- `ScaleTargetActivationFailed`
- `ScaleTargetDeactivationFailed`
For `ScaledJobs`:
- `JobsCreated`
If this list looks okay, I'll open a docs PR to list them in there. 
Fixes #530

Emit kubernetes events from KEDA

---

pkg/scaling/executor/scale_scaledobjects.go

I found keda-operator crash when my scaleTarget's replicas count is less than minReplicaCount and operater try to reset the replicas to minReplicaCount. Here is the panic logs.
```
2021-02-04T09:32:06.887Z	INFO	controllers.ScaledObject	Updated HPA according to ScaledObject	{"ScaledObject.Namespace": "default", "ScaledObject.Name": "nginx-deployment", "HPA.Namespace": "default", "HPA.Name": …
```

Fix nil pointer panic

---

CHANGELOG.md
config/manager/manager.yaml

Add container port for Prometheus on operator YAML exposed by operator SDK.
Relates to https://github.com/kedacore/charts/pull/118

feat: Add container port for Prometheus on operator YAML

---

go.mod
go.sum
pkg/scalers/azure/azure_eventhub.go

Supersedes https://github.com/kedacore/keda/pull/1596 since 0.13.0 has a an API breaking change

Update github.com/Azure/azure-storage-blob-go from 0.11.0 to 0.13.0

---

CHANGELOG.md
controllers/hpa.go

Fix KEDA generated hpa label

---

CREATE-NEW-SCALER.md

I've fixed the failing link in https://github.com/kedacore/keda/blob/main/CREATE-NEW-SCALER.md which refers "the guide for local deployment" under Developing a Scaler.
This fixed link gives the correct page now.

Fix failing link in CREATE-NEW-SCALER.md

---

CHANGELOG.md
controllers/hpa.go
controllers/scaledobject_controller.go
controllers/scaledobject_controller_test.go
pkg/scalers/postgresql_scaler_test.go

- [ N/A] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
Fixes #
Potential fix for #1636 
Scalers were not being closed properly after use.

Fix memory leak by checking triggers uniqueness properly

---

CHANGELOG.md
pkg/scaling/executor/scale_scaledobjects.go

Print correct ScaleTarget Kind in Events

---

pkg/scalers/mssql_scaler.go

Signed-off-by: Chris Gillum <cgillum@microsoft.com>
The MSSQL scaler would raise an error if a query result returned zero rows. This PR changes the behavior to instead return a metric value of `0` if a query results in zero rows.

MSSQL Scaler: Handle zero row query results

---

CHANGELOG.md
config/rbac/role.yaml

Signed-off-by: mlushpenko <mlushpenko@eclecticiq.com>
Based on https://github.com/kedacore/charts/pull/126

Fix clusterrole for clusterauthentication

---

CHANGELOG.md
pkg/scalers/openstack/keystone_authentication.go
pkg/scalers/openstack/utils/serviceTypes.go
pkg/scalers/openstack_swift_scaler.go
pkg/scalers/openstack_swift_scaler_test.go

Signed-off-by: Pedro Felipe Dominguite (<p.dominguite@sidi.org.br>)
- The `swiftURL` is now an optional parameter since it can be retrieved from the catalog.
- The optional parameter `regionName` was added.
- Now, the Keystone module can retrieve the service URL dynamically for any OpenStack service, by searching into the OpenStack catalog within the given authorization scope.
- Add serviceTypes helper which retrieves all the service types historically used by an OpenStack project.
- Update OpenStack Swift scaler unit tests

Update OpenStack Swift scaler

---

CHANGELOG.md
adapter/main.go

Set logger for controller-runtime in keda-adapter
Fixes #1639
- memory leak of keda-adapter
- https://github.com/kedacore/keda/issues/1639
- https://github.com/kubernetes-sigs/controller-runtime/issues/1122
- https://github.com/kubernetes-sigs/controller-runtime/pull/1309

fix memory leak by setting logger for controller-runtime in keda-adapter

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

Signed-off-by: Ryan Karg <rwkarg@gmail.com>
Added an additional trigger for RabbitMQ scaling on `publishRate`.
This allows for higher throughput workloads to scale based on the incoming message rate. This is useful because the message backlog does not often correlate with the desired instance count.
Both `publishRate` and `queueLength` triggers can be specified on a single ScaledObject. I would imagine the normal case would be to use both of these triggers.
~~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~~
- https://github.com/kedacore/keda-docs/pull/388
Fixes #1643

Add RabbitMQ `publishRate` trigger

---

CHANGELOG.md
pkg/scalers/aws_sqs_queue_scaler.go

This change affects the AWS SQS Scaler and how it considers when to scale down a ScaledObject. Before this change, the scaler only considered `AproximateNumberOfMessages`, which only includes pending queue messages.
After this change, the scaler will add `ApproximateNumberOfMessages` and `ApproximateNumberOfMessagesNotVisible`, the latter of which is all in-flight messages.
Fixes #1663

AWS SQS Scaler: Add Visible + NotVisible messages for scaling considerations

---

.github/workflows/build-tools.yml
.github/workflows/main-build.yml
.github/workflows/release-build.yml
BUILD.md
CREATE-NEW-SCALER.md
Makefile
config/manager/kustomization.yaml
config/manager/manager.yaml
config/metrics-server/deployment.yaml
config/metrics-server/kustomization.yaml

Publishing KEDA images on GitHub Container Registry, images are still mirrored to Docker Hub.
Fixes #1650

Publish KEDA images on GitHub Container Registry

---

CHANGELOG.md
pkg/scaling/scale_handler.go

When there is ScaledJob with External Scaler and this scaler has wrong definiton (url or any other metdata) the metricSpecs aren't returned for this scaler and that results in Operator panic
Fixes #1669

Fixing behavior on ScaledJob with incorrect External Scaler

---

CHANGELOG.md
pkg/scalers/metrics_api_scaler.go
pkg/scalers/metrics_api_scaler_test.go

Quantities can now be parsed from a metrics API response. Lots of metrics APIs return Quantity types which get marshalled to strings (KEDA itself actually has this behaviour).
ExternalMetricValue.Value is already a Quantity so there should be no impact on the wider codebase.
Fixes #1667

Metrics API scaler to support parsing numbers in quotes as well as quantities.

---

.github/workflows/main-build.yml
.github/workflows/pr-validation.yml
.github/workflows/release-build.yml

Adds the CI's go build cache to the static cache
Fixes #

Add GOCACHE to github action cache

---

CHANGELOG.md
config/crd/kustomization.yaml
config/crd/patches/scaledjob_patch.yaml

Add x-kubernetes-preserve-unknown-fields to ScaledJob CRD in order to support Labels in Job templates. Because there's a [bug](https://github.com/kubernetes-sigs/controller-tools/issues/448) in controller-gen, this field is not set during the generation. We need to patch during the "release of yaml" process via Kustomization.
Fixes #1311

ScaledJob: support metadata labels in Job template

---

CHANGELOG.md
Makefile
config/default/kustomization.yaml
config/default/kustomize-config/metadataLabelTransformer.yaml

Remove app.kubernetes.io/version label from label selectors

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Kafka: provide new option to enable scaling past partition count

---

CHANGELOG.md
pkg/scalers/external_scaler.go
pkg/scaling/scale_handler.go

As explained in the [docs for `time.After()`](https://pkg.go.dev/time#After), the `time.Timer` that underpins the call to `time.After` is not released and recovered by the GC. This PR fixes the resulting leak by creating and releasing `time.Timer`s instead of using `time.After()`

Using time.Timers instead of time.After()

---

CHANGELOG.md
pkg/scaling/scale_handler.go

https://github.com/kedacore/keda/pull/1704 changed the way how is the timer in scale loop calculated, but we have missed a bug. The timer was initialized only once (at the start), causing the scale loop not perform any checks :)

Fix regression brought by using time.NewTimer() in scale loop

---

tests/scalers/openstack-swift.test.ts
tests/scalers/openstack/openstack-helper.ts

Signed-off-by: Pedro Felipe Dominguite <p.dominguite@sidi.org.br>

Fix Swift scaler E2E test enviroment variables

---

.dockerignore
Dockerfile
Dockerfile.adapter
Makefile

- Context is lighter when running on remote docker server
- Image was not reproducible
- Azure ACR build ignore .git by default
Add parameters to `Makefile` and _build-arg_ to `Dockefile` to pass git commit and version (only things require `.git`).

chore: Don't send .git in docker context

---

CHANGELOG.md
pkg/scalers/ibmmq_scaler.go
pkg/scalers/ibmmq_scaler_test.go

Following https://github.com/kedacore/keda/issues/1133 and the related PR https://github.com/kedacore/keda/pull/1251, this PR adds a timeout to the HTTP client used by the IBM MQ scaler
- ~A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~ N/A
- ~A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*~ N/A

Adding HTTP timeout to the IBM MQ Scaler

---

CHANGELOG.md

Changelog chores

---

.devcontainer/Dockerfile
.github/workflows/pr-validation.yml
.golangci.yml

```
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
```

updating golangci and removing deprecated linters

---

tools/build-tools.Dockerfile

Fixes: https://github.com/kedacore/keda/runs/2490865709

Helm is not needed in build tools image

---

tools/build-tools.Dockerfile

go is not installed in the image
Fixes:

hardcode os and arch in kubebuilder installer

---

.github/workflows/fossa.yml
.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-validation.yml
.github/workflows/release-build.yml

New version of this image are no longer push to Docker Hub, we need to refere to ghcr.io in order to consume the lastest one.

refer to build-tools image hosted on ghcr.io

---

pkg/scalers/stan_scaler.go

Stan Scaler shows error message with Kafka in text instead of nats. 
The error message is:
```
"error": "error parsing kafka metadata: no queue group given."
```
It should be 
```
"error": "error parsing stan metadata: no queue group given."
```
Fixes #1781

updating stan scaler with correct error message

---

CHANGELOG.md
controllers/hpa.go
controllers/scaledobject_controller_test.go
controllers/suite_test.go

Fixes #1699 and includes a test to make sure it doesn't come back.

 🐛 Fix incorrect handling when removing from the end of the triggers array

---

CHANGELOG.md
go.mod
pkg/scalers/azure/azure_eventhub.go
pkg/scalers/azure/azure_eventhub_checkpoint.go
pkg/scalers/azure/azure_eventhub_test.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go

this is a solution for a language agnostic checkpointing. 
It comes with a new konfiguration for eventhub scaler: checkpointType. 
Actually with 3 Types:
AzureWebJob: the is default if no blobcontainer is set. this is the current working behavior for azure functions
GoSdk: GoSdk has a very special storage path and a special checkpoint structure.
Default: Default is set if a blobcontainer is set. Default, because this path and checkpoint structure is used by java, python and maybe others. It stores the values as metadata on the checkpoint blob. 
Fixes #769 #767 #741

language agnostic checkpointing for azure eventhub scaler

---

CHANGELOG.md
pkg/scalers/artemis_scaler.go
pkg/scalers/artemis_scaler_test.go

Encounter a problem while using apache artemis (last version), it complains that the header Origin is null. It seems now, unless you remove cors protection there is a need to add this header.
Content of the patch:
- Adding the origin header
- making it configurable in the metadata
Signed-off-by: Bernard Chesnoy <bernard.chesnoy@gmail.com>

Apache artemis origin header needed

---

CHANGELOG.md
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_blob_scaler_test.go

Include blobPrefix in metricName and allow custom metricName for azure-blob scaler
Fixes #1815

Azure Blob Scaler - Fix multiple scalers with the same blobContainerName

---

CHANGELOG.md
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/azure_servicebus_scaler_test.go

Signed-off-by: Damian Trojanowski <trojan.dg@gmail.com>
Changed Azure Service Bus scaler `metricName` to include Azure Service Bus Namespace, provided either from metric trigger parameter or from connection string. Thanks to this we can have more than one metric with the same `queueName` parameter.
Fixes #1755

Changed Azure Service Bus scaler `metricName` to include Azure Service Bus Namespace

---

tests/README.md

There is a correction needed here. 
>  See "scrips" in package.json.
Replacing 'scrips' with 'scripts' , Ava's link with correct ones.

correcting naming and links in README

---

renovate.json

Provide additional configuration for Renovate:
- Disable PR control to pass the task list PR check
- Bundle Kubernetes updates into 1 PR
- Bundle GitHub Action updates into 1 PR
- Automatically add `dependencies` label to PR
- Define branch prefix name	
- Sign off commits for DCO

Provide additional configuration for Renovate

---

pkg/scalers/cron_scaler.go
pkg/scalers/cron_scaler_test.go

Adding validation to check start and end for range values such as : 
> start: "30-39 * * * *" 
or negative values such as 
> start: "-39 * * * *"
Fixes #1809

cron: adding validation for range or hyphenated inputs for start and end

---

CHANGELOG.md
controllers/scaledjob_controller.go
pkg/scaling/executor/scale_jobs.go

Fix the READY AND ACTIVE fields of ScaledJob to show Status before and after scaling when we run `kubectl get sj`. and also replace ScaledObject to ScaledJob in comments and error message for ScaledJob.
Fixes #1849

Fix: READY and ACTIVE fields of ScaledJob to show status.

---

CHANGELOG.md
api/v1alpha1/triggerauthentication_types.go
config/crd/bases/keda.sh_clustertriggerauthentications.yaml
config/crd/bases/keda.sh_triggerauthentications.yaml

Add `VaultAdress` field in TriggerAuthentication and ClusterTriggerAuthentication CRD so on using` kubectl get TriggerAuthentication` or` kubectl get ClusterTriggerAuthentication` it would show the Address of HashiCorp Vault. 
Fixes #1826

Show HashiCorp Vault Address when using 'kubectl get ta' or 'kubectl get cta'

---

CHANGELOG.md
pkg/scaling/resolver/scale_resolvers.go

If HashiCorp Vault is being used and the input path is non existent, the library for reading the secret doesn't return error. In this case we need to handle this case and return error, instead of panic caused by accessing non existent secret.
Fixes #1864

Don't panic when HashiCorp Vault path doesn't exist

---

SECURITY.md

Add container image scanning in security policy to clarify that we already have this detection in place.
Relates to #1040

docs: Add container image scanning in security policy

---

pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Adding a metadata `version` to be able to set the user's kafka version. Right now, the value is hardcoded to 1.0.0 when calling the samara library. This commit will let the user specify which kafka version he is using only if it is supported by samara.
The PR updating the documentation will be submitted asap. To avoid any breaking changes, the default version is setted to 1.0.0 as before.
See https://github.com/kedacore/keda/discussions/1764
https://github.com/kedacore/keda-docs/pull/464

feat: adding version metadata to be able to specify kafka broker version

---

CHANGELOG.md
pkg/scalers/azure/azure_monitor.go
pkg/scalers/azure_monitor_scaler.go
pkg/scalers/azure_monitor_scaler_test.go

Add `metricNamespace` parameter to the Azure Monitor scaler to allow scaling based on custom metrics.
When querying [Custom metrics in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-custom-overview), the metric namespace must be provided in the API request. Otherwise, only default metrics can be found. E.g. for Azure Key Vault, when trying to get a custom metric without specifying the namespace, we will get the following error from the metrics client:
keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error getting azure monitor metric QueueDepth: insights.MetricsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequest\" …

Extend Azure Monitor scaler to support custom metrics

---

.devcontainer/Dockerfile
.github/workflows/pr-validation.yml
.golangci.yml
CONTRIBUTING.md
controllers/scaledjob_controller.go
controllers/scaledjob_finalizer.go
controllers/scaledobject_controller_test.go
pkg/scalers/azure_pipelines_scaler.go
pkg/scalers/influxdb_scaler.go
pkg/scalers/openstack_metrics_scaler.go
pkg/scalers/openstack_swift_scaler.go

Update golint to 1.41.1 and minor related fixes
```
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
controllers/scaledjob_controller.go:179:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
if err := r.scaleHandler.DeleteScalableObject(scaledJob); err != nil {
return err
}
controllers/scaledobject_controller_test.go:46:19: ST1023: should omit type []map[string]string from declaration; it will be inferred from the right-hand side (stylecheck)
var triggerMeta []map[string]string = []map[string]string{
^
pkg/scalers/influxdb_scaler.go:116:41: SA1030: 'bitSize' argument is invalid, must …
```

linter: update & use revive instead of golint

---

CHANGELOG.md
pkg/scalers/influxdb_scaler.go
pkg/scalers/influxdb_scaler_test.go

This allows `authToken`, `serverURL`, and `organizationName` to be sourced from `TriggerAuthentication` and `ClusterTriggerAuthentication` by the influxdb scaler.
Relates to https://github.com/kedacore/keda/issues/1905
Relates to https://github.com/kedacore/keda/discussions/1892
- [n/a] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*

Add support for Trigger Authentication for InfluxDB

---

api/v1alpha1/withtriggers_types.go
pkg/scaling/resolver/scale_resolvers.go
pkg/scaling/resolver/scale_resolvers_test.go
pkg/scaling/scale_handler.go

No changes to the functionality.
Minor chores and code refactoring/cleanup in scaler handler:
- moved `scalehandler.getPods()` -> `resolver.ResolveScaleTargetPodSpec()`
- extracted the relevant code from `scalehandler.buildScalers() `-> `resolver.ResolveAuthRefAndPodIdentity()`
- moved functions relevant to `WithTriggers` close to the `WithTriggers` source code
- some renaming
The code relevant to `ScaledJob` in scale_handler.go needs some love as well, but should be done in a separate PR.

scale handler: minor chores

---

CHANGELOG.md
pkg/scalers/ibmmq_scaler.go
pkg/scalers/ibmmq_scaler_test.go

Signed-off-by: Trevor Dolby <tdolby@uk.ibm.com>
Use passwords from secrets correctly.
Fixes #1938

Handle password value correctly; add tests.

---

renovate.json

It is very hard to actually update dependencies automatically, because we have many conflicting dependencies in our project.
Let's use Renovate to update only GH Actions and get back to updating all dependencies later.

Renovate: update only actions

---

CHANGELOG.md
adapter/main.go

Add rate limiting parameters to the Keda metrics apiserver to allow override of client defaults
Signed-off-by: Chris Berry <bez625@gmail.com>
Adding flags to the metrics api server main so that we can override the default client QPS and burst. This allows us to enable higher throughput of requests when Kubernetes HPA sync rate is higher frequency than default client limits.

Metrics APIServer: Add ratelimiting parameters to override client

---

renovate.json

Seems like https://github.com/kedacore/keda/pull/1947 doesn't work as expected :(

Renovate: ignore other deps then GH actions

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go

Signed-off-by: Lionel Villard <villard@us.ibm.com>
Send one request to get all topic offsets instead of one request per partition.
Fixes #

Kafka scaler: batch GetOffset requests

---

CHANGELOG.md
config/metrics-server/role_binding.yaml

This PR changes the name of the ClusterRoleBinding. This appeared after running https://github.com/helm/chart-testing on the kedacore/charts repository.

Change ClusterRoleBinding name to align with industry standard

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-validation.yml
tests/scalers/azure-queue.test.ts
tests/scalers/helpers.ts
tests/scalers/influxdb.test.ts
tests/scalers/redis-cluster-streams.test.ts

- `azure-queue` tests had an issue where it would fail if it took the deployment more than 10 seconds to scale. increasing it seems to make the test pretty reliable. However, we might wanna take a future work item to see what's the effective wait time of `pollingInterval`. 
- `redis-cluster-streams` had an issue with running the producer jobs before redis finished installing and that would cause them to fail to connect most of the time. To fix it I added a wait until redis statefulset rollout is complete.
- `influxdb` tests had a similar issue to `redis-cluster-streams` but with influxdb server. 
- [N/A] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. …

Fix timing in azure-queue and redis-cluster-streams tests

---

CHANGELOG.md
pkg/scalers/selenium_grid_scaler.go
pkg/scalers/selenium_grid_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/selenium-grid-test.ts

Signed-off-by: prashanth <rprashanth27@gmail.com>
Added a new scaler to scale selenium grid browser nodes based on the requests pending in queue. This will query the selenium grid based on the url that user provides and determine the metric based on the provided browser name.
Fixes #871

Add Selenium Grid scaler

---

CHANGELOG.md
pkg/scalers/influxdb_scaler.go
tests/scalers/influxdb.test.ts

Signed-off-by: Adam Gardner <adam.gardner@magicmemories.com>
Adjusted the InfluxDB scaler so that it can successfully process queries that return integer results in addition to those that return float results.
Fixes #1973

feat(influxdb-scaler): add support for integer query results

---

.gitignore
Makefile
tools/build-tools.Dockerfile

Prepare testenv in Makefile as part of `test` target and don't rely on the keda-tools container with backed kubebuilder. This simplifies testin on local machine

prepare testenv in Makefile

---

tools/build-tools.Dockerfile

Build tool image - use Bash by default instead of limited Dash

use Bash instead of Dash

---

.github/workflows/pr-validation.yml
Makefile
pkg/scaling/scale_handler.go
tests/package.json
tests/run-all.sh
tests/scalers/argo-rollouts.test.ts
tests/scalers/azure-pipelines.test.ts
tests/scalers/helpers.ts
tests/scalers/influxdb.test.ts
tests/scalers/prometheus-deployment.yaml
tests/scalers/prometheus.test.ts
tests/scalers/rabbitmq-helpers.ts
tests/scalers/rabbitmq-queue-amqp.test.ts
tests/scalers/rabbitmq-queue-http-regex.test.ts
tests/scalers/rabbitmq-queue-http.test.ts
tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts
tests/scalers/stan-helpers.ts

This change:
- increases test timeout to ~5~ 10 minutes
- uses a different namespace for Prometheus for `argo-rollouts.test.ts` and `prometheus.test.ts` to avoid conflict if the tests run at the same time
- reduce `pollingInterval` and `cooldownPeriod` in `azure-pipelines.test.ts`
- add readiness probe on influxdb, and rabbitmq deployment
- use `rabbitmq.conf` and `enabled_plugins` files for configuring rabbitmq instead of env vars since they are [deprecated](https://github.com/docker-library/rabbitmq/pull/467) and cause an error on start up
- add some helper methods for common tasks. 
- [NA] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A] A PR is opened …

Improve and update E2E tests 

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

This change adds support for parsing custom `metricName` in **RabbitMQ** scaler, and help to workaround use cases where there's reconcile error for a `ScaledObject` having duplicate auto generated `metricName`s, e.g., multiple trigger on the same queue, mode but from different RabbitMQ hosts.
- ~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
Fixes #1975

feat: Add support custom metricName in RabbitMQ scaler

---

CHANGELOG.md
api/v1alpha1/scaledjob_types.go
pkg/scaling/executor/scale_jobs.go
pkg/scaling/executor/scale_jobs_test.go

Added the `pendingPodConditions` setting for which users can pass a list of [Pod Conditions](https://kubernetes.io/docs/concepts/workloads/pods/_print/#pod-conditions) which Keda will consider when calculating the pending job count.
Resolves #1963 
Signed-off-by: Yaron Yarimi <yaron.yarimi@env0.com>

Support pod conditions for pending job count calculation

---

tests/scalers/helpers.ts

@zroubalik I'm not sure why the redis-cluster test never finished rolling out. I have seen that test case be a bit inconsistent due to the time it takes azure to mount the persistentVolumnClaim redis-cluster is requiring. I'm not sure if this was an instance of that or not. I added a timeout to the command so it doesn't get stuck for hours.
For the stability of the test itself, I can make it always try to rerun it or restart the redis cluster if it's stuck
- [N/A] Changelog has been …

set timeout on deployment rollout

---

CHANGELOG.md
config/crd/bases/keda.sh_scaledjobs.yaml

ScaledJob CRD hasn't been regenerated as part of https://github.com/kedacore/keda/pull/1970 
Thus `pendingPodConditions` feature wouldn't be available to the users. This PR fixes that.
Fixes #1963

Adding `pendingPodConditions` field to ScaledJob CRD

---

CHANGELOG.md
pkg/scalers/azure/azure_cloud_environment.go
pkg/scalers/azure/azure_cloud_environment_test.go
pkg/scalers/azure/azure_storage.go
pkg/scalers/azure/azure_storage_test.go
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/azure_servicebus_scaler_test.go

Similarly to #1863, added an optional `cloud` parameter to the Azure SB scaler to support non-public Azure clouds.
PR for updating the documentation: kedacore/keda-docs#473.
Fixes https://github.com/kedacore/keda/issues/1918
Signed-off-by: amirschw <24677563+amirschw@users.noreply.github.com>

Support non-public cloud environments in the Azure Service Bus scaler

---

.golangci.yml
CHANGELOG.md
pkg/scalers/kubernetes_workload_scaler.go
pkg/scalers/kubernetes_workload_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/kubernetes-workload.test.ts

Add a new scaler based on the amount of pods which match the selectors (allowing also to specify a specific namespace or all)
With this scaler, you can scale a workload according to another relater workload inside the cluster:
> For example - Workload A processes a queue and interacts with workload B. Workload A can autoscale based on queue depth and workload B on CPU. But in some scenarios, you want to add 1 instance for workload B for every 4 instances of workload A
Relates to #1735

Add Kubernetes Workload scaler 

---

CHANGELOG.md
controllers/hpa.go
controllers/scaledjob_controller.go
controllers/scaledobject_controller.go
pkg/scaling/executor/scale_jobs.go

KEDA defines and uses labels in order to do scaling, there are certain recommendations for labels naming, ie. use some prefix and keep non prefixed for user defined labels. 
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
> If the prefix is omitted, the label Key is presumed to be private to the user. Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add labels to end-user objects must specify a prefix.
Also:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
---
So this PR intoduces a change in labels (It shouldn't bring any problems to users as KEDA Operator automatically sets these): …

Use `scaled[object/job].keda.sh/` prefix for KEDA related labels

---

CHANGELOG.md
pkg/scalers/cron_scaler.go
pkg/scalers/cron_scaler_test.go

In corn scaler, the target doesn't scale down when the start and end schedule are given the same input.
Fixes #2031

validation and check in cron scaler for same start and end case

---

CHANGELOG.md
pkg/scalers/authentication/authentication_types.go
pkg/scalers/metrics_api_scaler.go
pkg/scalers/metrics_api_scaler_test.go

Adds an authorization method named `bearer` for Metrics API scaler
Relates to https://github.com/kedacore/keda/issues/1081

Add Bearer Auth for Metrics API scaler

---

CHANGELOG.md
pkg/scalers/cron_scaler.go
pkg/scalers/cron_scaler_test.go

This PR changes the method to validate the cron. Now the package parser is used to detect invalid expressions instead a custom method.
Fixes https://github.com/kedacore/keda/issues/2034

Update cron scaler to parse the cron with parser instead of searching for '-'

---

pkg/scalers/prometheus_scaler_test.go

Hi, with this pr I've adapt prometheus scaler tests input to #381

adapt test to #381

---

Makefile

If you are using dev container to contribute to this repo, you could need run `make test` to ensure that all the tests working.
The default shell inside the container that is used with make is /bin/sh and it doesn't support `source`, so in order to maintain the same Makefile, the best approach could be specifying the `SHELL` variable to enforce the usage of bash.
This PR sets the variable inside the file

Update Makefile to ensure that bash is used instead of sh or another

---

config/manager/manager.yaml
config/metrics-server/deployment.yaml

As the same way as using helm, this PR adds the env `KEDA_HTTP_DEFAULT_TIMEOUT` to do explicit the option of setting it
Fixes https://github.com/kedacore/charts/issues/180

Adds explicit the option of setting `KEDA_HTTP_DEFAULT_TIMEOUT`

---

controllers/scaledobject_controller.go

There was a typo in `isScalableCache`, StatefulSets weren't properly specified there, it is not a big deal, since this map is properly populated with first StatefulSet `/scale` call.

fix typo in isScalableCache

---

tests/scalers/postgresql.test.ts

This PR adds e2e test for Postgres scaler. It's a draft until this other PR is merged ~~https://github.com/kedacore/test-tools/pull/18~~ https://github.com/kedacore/test-tools/pull/20  (I need it to use the PostgreSQL docker image here :) )

Adds e2e test for PostgreSQL scaler

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

This PT adds the support to specify a specific timeout to use for each trigger when you are using RabbitMQ Scaler.
Fixes https://github.com/kedacore/keda/issues/2053

Add custom http timeout in RabbitMQ Scaler

---

CHANGELOG.md
apis/keda/v1alpha1/triggerauthentication_types.go
pkg/scaling/resolver/hashicorpvault_handler.go

Signed-off-by: Nicolas Chapurlat <nc@coorganix.com>
Related to this issue: [#2084](https://github.com/kedacore/keda/issues/2084)
Related to this discussion: [#2080](https://github.com/kedacore/keda/discussions/2080)
- Add an optional "namespace" in Keda TriggerAuthentication spec: `spec.hashiCorpVault.namespace`
- Optionally configure the Vault namespace in the Vault client
- **REMOVED FROM THIS PR**: Make sure the VAULT_NAMESPACE env var never takes precedence (Vault client default behaviour)
Relates to https://github.com/kedacore/keda/issues/2084

TriggerAuthentication/Vault: add support for vault namespace

---

CHANGELOG.md
CREATE-NEW-SCALER.md
pkg/scalers/graphite_scaler.go
pkg/scalers/graphite_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/graphite-deployment.yaml
tests/scalers/graphite.test.ts

Support scaling by Graphite Metrics
https://github.com/kedacore/keda-docs/pull/524
Fixes #1628

Graphite Scaler + e2e tests

---

.devcontainer/Dockerfile

After the go upgrade, the default behavior related with packages has changed. This change broke the dev container. 
This PR, setting the environment variable `GO111MODULE` to `auto` in dev container maintain the previous behavior and fixes the problem. Basically we don't have the go.mod file during the image building so for us is most interesting to still use GOPATH instead go modules (in case of not existing the go.mod file)

Fix dev container after Golang version update

---

pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go

As we were talking during the last meeting, this PR modifies the behavior of RabbitMQ Scaler to raise an error in case of the provided regex matches with more queues those are returned in a single page. At least with this PR, the user get information about why the scaler doesn't reflect the current status of the queues (if they need 2 or more pages)
Fixes https://github.com/kedacore/keda/issues/2068

Raises an error when RabbitMQ regex matches more than 1 page

---

CHANGELOG.md
pkg/scalers/mssql_scaler.go
pkg/scalers/mssql_scaler_test.go

Adds support to getthe connection data from Trigger Authorization in MSSQL Scaler
Fixes https://github.com/kedacore/keda/issues/2108

Add support to get connection data from Trigger Authorization in MSSQL Scaler

---

CHANGELOG.md
pkg/scalers/mysql_scaler.go
pkg/scalers/mysql_scaler_test.go

Add support to get connection data from Trigger Authorization in MySQL Scaler
Fixes https://github.com/kedacore/keda/issues/2109

Add support to get connection data from Trigger Authorization in MySQL Scaler

---

CHANGELOG.md
pkg/scalers/mongo_scaler.go
pkg/scalers/mongo_scaler_test.go

Add support to get connection data from Trigger Authorization in MongoDB Scaler 
Fixes https://github.com/kedacore/keda/issues/2111

Add support to get connection data from Trigger Authorization in MongoDB Scaler 

---

tests/scalers/cassandra.test.ts

Problem:
```
2021-11-01T14:59:32.0823763Z 202***-***-0***T***4:48:25.590Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "cassandra-scaledobject", "namespace": "cassandra-test"}
2021-11-01T14:59:32.0826654Z 202***-***-0***T***4:48:25.590Z	INFO	controller.scaledobject	Adding Finalizer for the ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "cassandra-scaledobject", "namespace": "cassandra-test"}
2021-11-01T14:59:32.0830282Z 202***-***-0***T***4:48:25.62***Z	INFO	controller.scaledobject	Detected resource targeted for scaling	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": …
```

Fix Cassandra e2e test

---

tests/scalers/cassandra.test.ts

The Secret has encoded `cassandra\n` as the password instead of `cassandra`. Also changing cassandra images to bitnami/cassandra as they are non root.
Relates to: https://github.com/kedacore/keda/issues/2227

Fix Cassandra e2e tests part 2

---

tests/scalers/redis-sentinel-streams.test.ts

Signed-off-by: Jeroen Bobbeldijk <jeroen@klippa.com>
This fixes a minor mistake in the e2e test for Redis Sentinel Streams
Relates to #2227

Fix sentinel streams e2e test

---

.github/workflows/pr-e2e.yml
CHANGELOG.md
Makefile
tests/run-all.sh
tools/build-tools.Dockerfile

We have been discussing how to run e2e test in PRs before merge them when anyone with writing permissions requests it.
There are several options to achieve this behavior, in this PR I propose to use several actions in a row to allow it.
When someone with writing permissions comment the PR with the message `/e2e`, automatically this action will be executed reacting the comment with 🚀  to refer that the pipeline is in process, and also with 👍 / 👎  to notify if the e2e tests have passed or not.
Also, the trigger supports setting the e2e test discovery regex using if you want, using this format `/e2e REGEX`, ex:
- `/run-e2e *.test.ts`
- `/run-e2e cron*`
**Note**: To use this feature, we should build and push this image …

Add github action to run e2e command "on-demand"

---

.github/workflows/pr-e2e.yml

After merged, the new workflow,  all the comment on PRs are reacted with 👎 always that e2e are not successfully passed, even if they should not be executed. 
[This is an example](https://github.com/kedacore/keda/pull/2241#issuecomment-962034017)
The workflow only should react to authorized comments

Add triggering condition to failure reaction for on-demand command

---

.github/workflows/pr-e2e.yml

The new workflow to trigger e2e-test on demand runs in a single job with concurrency with other e2e processes. This could produce long queues of waiting comments until the e2e tests finish.
This is not necessary at all and can be handled splitting the workflow in 2 different jobs, one without concurrency to evaluate the comments and another one with concurrency to execute the tests. Another improvement using this second way is that the "e2e related steps" don't need a condition in each one because the condition is at job level.
This PR implements the second way to improve the process and also fix a minor problem that react with rocket always when the comment is on a PR

Split the workflow to trigger e2e test in 2 different jobs

---

CHANGELOG.md
pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_cloudwatch_test.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_kinesis_stream_test.go
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/aws_sqs_queue_test.go

update aws related scalers to reuse the aws clients instead of creating a new one for every GetMetrics call
Signed-off-by: Xiayang Wu <xwu@rippling.com>
Refactor the aws related scalers, which includes cloudwatch, sqs and kinesis, to hold references to the dedicated aws client per scaler instance to improve performance, since the aws clients are reusable and able to refresh tokens automatically.
This is a follow up on issue: https://github.com/kedacore/keda/issues/2242
Fixes #

update aws related scalers to reuse the aws clients

---

.github/workflows/pr-e2e.yml

the e2e env is shared, so all actions running e2e should wait on the same concurrency key.

Set concurrency for pr-e2e action

---

.github/workflows/pr-e2e.yml

Reverting #2261 because `concurrency` has been already set on the second job in the worklflow: https://github.com/kedacore/keda/blob/5d035404e73aa6b25e5af21d150c99c9e0752bde/.github/workflows/pr-e2e.yml#L43
Setting it once again on the workflow level causes problems like: https://github.com/kedacore/keda/actions/runs/1439326562
```
Execute e2e tests
Canceling since a higher priority waiting request for 'e2e-tests' exists
```

Reverting #2261

---

CHANGELOG.md
pkg/scalers/prometheus_scaler.go
pkg/scalers/prometheus_scaler_test.go

Signed-off-by: Magdalena Andruszak <mandruszak@gmail.com>
Validating values length in prometheus query response. When there is no values returned `invalid array index` panic occurs. 
Solution:
- If there is no values in response return zero
- If single value received return error
Fixes #

Validate values length for prometheus scaler

---

.github/workflows/pr-e2e.yml

Signed-off-by: Ahmed ElSayed <ahmed@elsayed.io>
Fixes #

Use a different cluster for pr e2e runs

---

config/manager/manager.yaml
config/metrics-server/deployment.yaml
tests/scalers/azure-blob.test.ts

```
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```

`beta.kubernetes.io/os` nodeSelector is deprecated

---

CHANGELOG.md
pkg/scalers/artemis_scaler.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_log_analytics_scaler.go
pkg/scalers/azure_pipelines_scaler.go
pkg/scalers/azure_queue_scaler.go
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/graphite_scaler.go
pkg/scalers/ibmmq_scaler.go
pkg/scalers/influxdb_scaler.go
pkg/scalers/influxdb_scaler_test.go
pkg/scalers/metrics_api_scaler.go
pkg/scalers/openstack/keystone_authentication.go
pkg/scalers/openstack/utils/serviceTypes.go
pkg/scalers/prometheus_scaler.go
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/selenium_grid_scaler.go
pkg/scalers/selenium_grid_scaler_test.go
pkg/scalers/solace_scaler.go
pkg/scalers/stan_scaler.go
pkg/util/http.go

Fixes https://github.com/kedacore/keda/issues/2252

Add `unsafeSsl` parameter in Selenium Grid scaler

---

.github/workflows/pr-e2e.yml
CHANGELOG.md

Using the on-demand e2e test feature, we discovered that getting the execution url is useful to check what happened in case of failure. This PR modifies the workflow in order to update the trigger comment with a link to the execution.
~~**EDIT**: I converted it to draw again because I'd like to solve the problem with the replies also in this PR~~
Fixes https://github.com/kedacore/keda/discussions/2224#discussioncomment-1604768

Add execution url in the pr-e2e triggering comment and fix problem related with not starting with

---

CHANGELOG.md
adapter/main.go
controllers/keda/metrics_adapter_controller.go
pkg/provider/fallback_test.go
pkg/provider/provider.go

Cache metrics provided by KEDA Metrics Server instead of requesting list of all ScaledObjects in the cluster, this should reduce the load on k8s server and Metrics Server should respond much faster.
Fixes #2156
Potential fix for: https://github.com/kedacore/keda/issues/1937

Cache metric names provided by KEDA Metrics Server

---

CHANGELOG.md
pkg/scalers/azure_pipelines_scaler.go

Signed-off-by: Enderson Menezes <endersonster@gmail.com>
Logging URL on Azure Pipelines Scaler Error!
---
Hi, I'm new to Go and here at Keda we are running a POC within the company and this little addition helped us to better understand our mistake.
Does this change need to change CHANGELOG? Any other nonsense I've done let me know please!

improve (azure-pipelines): log url on error

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go

Fixes https://github.com/kedacore/keda/issues/2318

RabbitMQ: use int64 for `pageSize` to avoid conversion problems

---

CHANGELOG.md
adapter/main.go
controllers/keda/metrics_adapter_controller.go
controllers/keda/scaledjob_controller.go
controllers/keda/scaledobject_controller.go
controllers/keda/suite_test.go
main.go
pkg/util/env_resolver.go

This should allow setting MaxConcurrentReconciles for controllers.

Allow setting `MaxConcurrentReconciles` for reconcilers

---

.github/CODEOWNERS

Use @kedacore/keda-maintainers for code ownership which includes @JorTurFer 
Closes https://github.com/kedacore/governance/issues/42

chore: Use @kedacore/keda-maintainers for code ownership

---

RELEASE-PROCESS.MD

Introduce continuous container scanning with Snyk in the release process so that we are monitoring them.
Relates to https://github.com/kedacore/keda/issues/1041

docs: Introduce continous container scanning with Snyk in release process

---

.github/CODEOWNERS

Remove org prefix for code owners given this is breaking the assignment as per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
Fixes https://github.com/kedacore/keda/pull/2326

fix: Remove org prefix for code owners

---

.devcontainer/Dockerfile
.github/workflows/fossa.yml
.github/workflows/pr-validation.yml
CHANGELOG.md
Dockerfile
Dockerfile.adapter
go.mod
tools/build-tools.Dockerfile

Bump to Go 1.17.3, follow up to this: https://github.com/kedacore/keda/pull/2186
Fixes: #2222

bump to Go 1.17.3

---

.github/CODEOWNERS

Use verbose code ownership given it's not working with groups.

fix: Use verbose code ownership

---

.github/CODEOWNERS

Use @kedacore/keda-core-contributors for code ownership to see if this works, thanks to @JorTurFer for repo access tip.
Let's see if this works, if not then just revert the PR.

chore: use @kedacore/keda-core-contributors for code ownership

---

CHANGELOG.md
pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_cloudwatch_test.go

Handle no metrics found for AWS Cloudwatch

---

pkg/util/tls_config.go

We need to disable the validation in those cases, so instead of ignoring it in GitHub, this could hide it
Fixes https://github.com/kedacore/keda/issues/2336

fix: Validate TLS certificate check being disabled

---

renovate.json

Remove PR checkbox for Renovate PRs which are blocking our checklist PR check.
https://docs.renovatebot.com/presets-default/#disableprcontrols
Follow-up for #2361

chore: Remove PR checkbox for Renovate PRs

---

CHANGELOG.md
pkg/scalers/graphite_scaler.go

Graphite query responses return values in order of oldest to latest. With the final element of the response array being the most up-to-date timestamp. Graphite's scaler should be on the most recent datapoint, not on data potentially hours old.
https://graphite-api.readthedocs.io/en/latest/api.html#json
https://github.com/kedacore/keda/blob/main/pkg/scalers/graphite_scaler.go#L197
Fixes #2366

Graphite scaler should use latest datapoint, not earliest, returned

---

CHANGELOG.md
pkg/scalers/kubernetes_workload_scaler.go
pkg/scalers/kubernetes_workload_scaler_test.go

The kubernetes-workload scaler is great, but I was surprised to discover that it counts terminated pods. While it's useful to have Shutdown or Completed pods stay around to aid for example troubleshooting I fail to come up with a use case where scaling should count them together with running. This PR excludes the two obvious terminated states from the metric value.

Kubernetes Workload Scaler: ignore terminated pods

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-e2e.yml

In order to be able to test [this PR](https://github.com/kedacore/keda/pull/2387), New Relic environment variables are needed, otherwise the pr-e2e workflow will fail because it gets the definition from main branch.
Those variables are already defined inside repo secrets

Add New Relic variables for e2e tests

---

CHANGELOG.md
config/rbac/role.yaml

Signed-off-by: tomasspi <tom-300@hotmail.com>
Added `list` and `watch` access for service accounts to `keda-operator` cluster role.
Fixes #2383

fix: add list and watch access for service accounts to cluster role

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-e2e.yml

This PR adds the required variables for running [Datadog Scaler](https://github.com/kedacore/keda/pull/2354) e2e-test 
Related https://github.com/kedacore/keda/pull/2354

Add Datadog secrets for e2e-test

---

CHANGELOG.md
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go

Fixes https://github.com/kedacore/keda/issues/2403

Azure EventHub Scaler: don't expose connection string in metricName

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
tests/README.md
tests/scalers/kafka.test.ts

Concurrently query brokers for consumer and producer offsets
Fixes #2377. 
Signed-off-by: VerstraeteBert <bertverstraete22@gmail.com>

Kafka scaler: concurrent offset fetches

---

CHANGELOG.md
pkg/scalers/postgresql_scaler.go
pkg/scalers/postgresql_scaler_test.go

Add missing test for connectionString generation
Related https://github.com/kedacore/keda/pull/2432

Add PostgreSQL connectionString generation test

---

.github/stale.yml

Don't consider dependencies for stale updates by adding them to the exclusion list.
See https://kubernetes.slack.com/archives/CKZJ36A5D/p1641256299483500

chore: Don't consider dependencies for stale updates

---

tests/scalers/azure-queue-trigger-auth.test.ts

E2E test case in file `scalers/azure-queue-trigger-auth.test.ts` used to fail with below error.
```
Error getting triggerAuth
{
"type": "ScaledObject",
"namespace": "azure-queue-auth-test",
"name": "test-scaledobject",
"triggerAuthRef.Name": "azure-queue-auth",
"error": "TriggerAuthentication.keda.sh \"azure-queue-auth\" not found"
}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
/workspace/pkg/scaling/scale_handler.go:301
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
/workspace/pkg/scaling/scale_handler.go:309
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
/workspace/pkg/scaling/scale_handler.go:189
```
The reason for error must be the order of creation of resources, as the `ScaledObject` was being created before …

fix: Fix Azure Queue TriggerAuthentication E2E test failure

---

pkg/scalers/aws_cloudwatch_test.go

Very small and silly change.
I noticed that the test data values didn't match the comment :-) 
(probably copy/paste of the previous use case)

Fix Cloudwatch Scaler test data

---

.github/workflows/pr-e2e.yml
.github/workflows/upgrade-validation-template.yml
CHANGELOG.md

fix: Use a user with permissions for ghcr login always

---

.pre-commit-config.yaml

Fix incompatible pre-commit validation to rely on HTTPS instead of GIT
Relates to https://github.com/pre-commit/action/issues/137#issuecomment-1009978115
Relates to https://github.com/pre-commit/action/issues/137#issuecomment-1009978115

chore: Fix incompatible pre-commit validation

---

.github/assets/test-upgrade-manifest.yml
.github/workflows/upgrade-validation-template.yml
RELEASE-PROCESS.MD
tests/scalers/mongodb.test.ts

Right now MongoDB e2e test are broken because the current image doesn't exist anymore. This PR changes the used image from new one under our ownership. The image from [this PR](https://github.com/kedacore/test-tools/pull/25) is needed

fix: Use our own docker image for MongoDB e2e tes

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go
tests/scalers/kafka.test.ts

Allow kafka scaler to use sum of lag for all topic partition when no `topic` is supplied.
This is useful when the consumer is subscribed to multiple topics;

Allow Apache Kafka scaler to scale using sum of lag for all topics within a consumer group

---

CHANGELOG.md
go.mod
go.sum
pkg/scalers/datadog_scaler.go
pkg/scalers/datadog_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/datadog.test.ts

This PR adds a new Datadog scaler. Right now, it uses Datadog metrics to drive HPA, both on a target value and a target average value. In the future, it could grow to also allow to scale based on events, monitor statuses, etc.
Related docs PR: https://github.com/kedacore/keda-docs/pull/602
This is an example of what the TriggerAuthentication and the ScaledObject definitions would look like:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: datadog-secrets
namespace: my-project
type: Opaque
data:
apiKey: # Required: base64 encoded value of Datadog apiKey
appKey: # Required: base64 encoded value of Datadog appKey
datadogSite: # Optional: base64 encoded value of Datadog site
---
kind: TriggerAuthentication
metadata:
name: keda-trigger-auth-datadog-secret …
```

Add new Datadog scaler

---

CHANGELOG.md
tests/scalers/cpu.test.ts

This PR add E2E tests for cpu scaler.
Fixes #2219

E2E test for cpu scaler

---

CHANGELOG.md
pkg/scaling/scale_handler.go

Signed-off-by: Xiayang Wu <xwu@rippling.com>
Instead of creating an unexpected HPA, fail fast when not able to resolve a secret a deployment is relying on. 
the missing secret can be a mistake or just timing issue.  more details can be found from https://github.com/kedacore/keda/issues/2393
Fixes https://github.com/kedacore/keda/issues/2393

fail fast on `buildScalers` when not able to resolve a secret

---

.github/workflows/release-build.yml
CHANGELOG.md
Makefile

Sign KEDA images published on GitHub Container Registry. Don't sing DockerHub hosted images, as we are going to abandon this registry soon.
Fixes https://github.com/kedacore/keda/issues/2386

Sign KEDA images published on GitHub Container Registry

---

.github/workflows/main-build.yml
.github/workflows/release-build.yml
CHANGELOG.md

Sign main tag and add missing env during release workflow

---

.github/workflows/main-build.yml
.github/workflows/release-build.yml
CHANGELOG.md

For being able to sign the images with the token, we should specify the requirement of `GitHub OIDC Token` in GITHUB_TOKEN. This pushes to add all the needed permission because once you request 1, you have to specify all of them. 
Instead of adding all available permissions in the token, **I added those I think we use, but please review it**
Related #2501 #2502
Fixes #2386

Add GitHub OIDC Token into GITHUB_TOKEN for signing images

---

CHANGELOG.md
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/aws_sqs_queue_test.go

AWS SQS autoscaler does not really need a full queueURL, it also works with simple queue names, but there was some code that tried to parse the URL to get the queue name for building a metric ID.
The example in the doc already [uses a simple name](https://keda.sh/docs/2.5/scalers/aws-sqs/#scaling-a-deployment-using-podidentity-providers).
Fixes #

Allow using simple queue names in aws sqs scaler

---

CHANGELOG.md
controllers/keda/metrics_adapter_controller.go
pkg/mock/mock_scaling/mock_interface.go
pkg/provider/provider.go
pkg/scaling/scale_handler.go

This fix should correctly clear/invalidate cache in both KEDA Operator and Metrics Server, when ScaledObject is deleted from cluster, when there is a problem in resolving secrets/credentials or when there is a general problem in scraping metrics from a scaler.
The previous fix https://github.com/kedacore/keda/pull/2408 worked only partially - in KEDA Operator, because it didn't use `ClearScalersCache()` function, but tried to delete the map entry directly. But the main problem was, that the `ClearScalersCache()` which is being used in Metrics Server, operated on a wrong key, ie. `name.namespace` instead of `kind.namespace.name` generated by `withTriggers.GenerateIdenitifier()`.  That resulted in cache not being invalidated in Metrics …

Clear scalers cache correctly both in Operator and Metrics Server

---

CHANGELOG.md
pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_cloudwatch_test.go
pkg/scalers/aws_iam_authorization.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_kinesis_stream_test.go
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/aws_sqs_queue_test.go

Add support for AWS temporary credentials by allowing session tokens to
be specified.
Assuming Secrets are kept up-to-date with valid session tokens, scalers
using temporary credentials will error once after token expiration. The
scaler cache for the corresponding ScaledObject will be cleared, the
scaler will be rebuilt using the updated temporary credentials, and the
scaler will resume operation.
Signed-off-by: Jacob Henner <code@ventricle.us>
- https://github.com/kedacore/keda-docs/pull/642 
Fixes #2495

Add support for AWS temporary credentials

---

.github/workflows/main-build.yml
.github/workflows/release-build.yml
CHANGELOG.md
Makefile

On June 21, 2021, [GitHub Container Registry became generally available](https://github.blog/2021-06-21-github-packages-container-registry-generally-available/) which means that we will no longer push to Docker Hub on release as per https://github.com/kedacore/governance/issues/16 and our [announcement in March 2021](https://github.com/kedacore/keda/discussions/1700).
Fixes https://github.com/kedacore/governance/issues/16

chore: No longer push to Docker Hub on release

---

CHANGELOG.md
pkg/scaling/scale_handler.go

We have passed a wrong reference to scaler index in the for loop in the factory method. And subsequent calls to `factory()` resulted in the last index has been populated for this particular scaler.
Fixes #2592
Fixes #2381

use correct index in `ScalerBuilder.Factory`

---

tests/package-lock.json

Updates the npm tar version to 6.1.11 (currently latest) due to CVE-2021-32803
Update trim-off-newlines to 1.0.3 and follow-redirects to 1.14.7
due to CVE-2021-23425 and CVE-2022-0155
Fixes #2529 #2542 #2544 #2545 #2548 #2516 #2518
Signed-off-by Ram Cohen ram.cohen@gmail.com

Update npm test packages tar, trim-off-newlines and follow-redirects

---

tests/package-lock.json

Update use of ansi-regex 4.1.0 & 5.0.0 to 5.0.1
Fixes #2541

Use ansi-regex 5.0.1 due to CVE-2021-3807

---

.golangci.yml
CHANGELOG.md
apis/keda/v1alpha1/condition_types.go
controllers/keda/scaledobject_controller.go
pkg/scaling/cache/scalers_cache.go
pkg/scaling/executor/scale_executor.go
pkg/scaling/executor/scale_scaledobjects.go
pkg/scaling/executor/scale_scaledobjects_test.go
pkg/scaling/scale_handler_test.go

Images with this fix + fix from #2593 are hosted here: 
- `quay.io/zroubalik/keda:statusFix`
- `quay.io/zroubalik/keda-metrics-apiserver:statusFix`
Fixes #2603

Properly log and set correct status if any of ScaleObject's triggers are in error state

---

CHANGELOG.md
config/crd/bases/keda.sh_scaledjobs.yaml
controllers/keda/scaledobject_controller_test.go
tests/package.json
tests/run-all.sh
tests/scalers/activemq.test.ts
tests/scalers/argo-rollouts.test.ts
tests/scalers/artemis-helpers.ts
tests/scalers/azure-pipelines.test.ts
tests/scalers/azure-queue-restore-original-replicas.test.ts
tests/scalers/azure-queue-trigger-auth.test.ts
tests/scalers/azure-queue.test.ts
tests/scalers/cassandra.test.ts
tests/scalers/elasticsearch.test.ts
tests/scalers/graphite.test.ts
tests/scalers/kubernetes-workload.test.ts
tests/scalers/mongodb.test.ts
tests/scalers/mysql.test.ts
tests/scalers/new-relic.test.ts
tests/scalers/openstack-swift.test.ts
tests/scalers/predictkube.test.ts
tests/scalers/prometheus.test.ts
tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts
tests/scalers/redis-lists.test.ts
tests/scalers/redis-sentinel-lists.test.ts
tests/scalers/redis-sentinel-streams.test.ts
tests/scalers/redis-streams.test.ts
tests/scalers/selenium-grid.test.ts

This PR increases some timeouts across different e2e test and does these relevant changes:
- **Azure Pipelines**: e2e tests now check scaling from/to 0 instead of between 1 and 3 because otherwise we have random fails if the removed pods during the scale in are still executing an AzDO job.
- **New Relic**: e2e test has changed a bit to maintain the load till the scaling out is done.
- **Selenium**: e2e test has changed, now nodes starts from 0 and check scaling to 0 instead of job status because sometimes the job started before the hub is ready and has more than 1 result (and the test fails)
- **Global**: The timeout for each scaler e2e tests has been increased from 10m to 30m.
- **Global**: Removed all the resources except for cpu e2e …

Improve e2e test reliability

---

CHANGELOG.md
CONTRIBUTING.md
pkg/scalers/azure/azure_queue.go

This PR reorders the logic of getting an Azure queue size in a way
that skips the call to get the queue properties (for getting the
ApproximateMessagesCount) if the queue has less than 32 messages.

Don't call Azure queue GetProperties API unnecessarily

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go

Signed-off-by: Gunnar Palsson <gunniwho@gmail.com>
Accepts `disable` as a valid value for the `tls` auth parameter of the kafka scaler.
Fixes #2608

accept 'disable' as a valid tls value for kafka scaler

---

CHANGELOG.md
pkg/scalers/datadog_scaler.go
pkg/scalers/datadog_scaler_test.go

It's probably nice to handle the error gracefully rather than panic in case of unexpected datadog scaler query
Fixes #2625

datadog_scaler: handle mising { on dd query

---

pkg/scalers/kubernetes_workload_scaler_test.go

Use fake.NewClientBuilder instead of deprecated NewFakeClient

Use fake.NewClientBuilder instead of deprecated NewFakeClient

---

.golangci.yml
pkg/scaling/resolver/scale_resolvers_test.go

Remove reference to NewFakeClient and linter override

chore: Remove reference to NewFakeClient and linter override

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-e2e.yml

Provide e2e variables for GCP auth by exposing the JSON key for our service account.
Relates to https://github.com/kedacore/keda/issues/2628

feat: Provide e2e variables for GCP auth

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml
.github/workflows/pr-e2e.yml
Makefile

This PR extracts the context recovering and use it for e2e test and namespace deletion. This solves the problem of failing the CI before recovering the cluster context
Fixes #2584

fix: Add step in makefile to get the cluster context and use it to delete namespaces

---

.devcontainer/Dockerfile
.github/workflows/main-build.yml
.github/workflows/release-build.yml
CHANGELOG.md
Dockerfile
Dockerfile.adapter
Makefile
tests/run-arm-smoke-tests.sh
tools/build-tools.Dockerfile

This PR adds (using buildx and cross compilation) support for ARM arch (https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/)
Also removes the support to dockerhub
Fixes https://github.com/kedacore/keda/issues/2263

Automatically release container image for ARM

---

.github/workflows/pr-validation.yml
Makefile
tools/build-tools.Dockerfile

This PR fixes the error generating build-tools image with buildx enabled and also adds a CI which runs only if there are changes inside `tools` folder for checking the image
Related #2263

fix: Fix error generating build-tools image

---

.devcontainer/Dockerfile
.github/workflows/main-build.yml
.github/workflows/release-build.yml
tools/build-tools.Dockerfile

Fixes https://github.com/kedacore/keda/issues/2263

fix: create buildx context on github workflow 

---

README.md

Improve README for [CloMonitor](https://clomonitor.io/projects/keda/keda) compliance:
- Add Roadmap link
- Add `Adopters` word
Generally restructured it a bit as well, just as a suggestion
Relates to https://github.com/kedacore/governance/issues/49
Relates to https://github.com/kedacore/governance/issues/48

chore: Improve README for CloMonitor compliance

---

README.md

Migrate to CNCF-based Zoom account and Google Docs instead of HackMD.
- Available on https://github.com/kedacore/keda-docs/pull/683
Relates to https://github.com/kedacore/governance/issues/50

chore: Migrate to CNCF-based Zoom account and Google Docs

---

.github/workflows/main-build.yml

Till [this is](https://github.com/kedacore/keda/issues/2262) ready, doesn't make sense to break main workflow
Related https://github.com/kedacore/keda/issues/2262

Remove arm64 smoke tests

---

.github/workflows/pr-validation.yml
Dockerfile
Dockerfile.adapter

Locally, both multiarch Dockerfile work without the variables but in the CI, the default values are necessary for Dockerfile arguments.
This PR also adds a workflow which builds docker images (only build) if any change is detected in Dockerfiles to avoid this problem in the future
Related https://github.com/kedacore/keda/issues/2263

Fix e2e test command

---

tests/scalers/azure-blob.test.ts

After renaming env variables, we changed `TEST_STORAGE_CONNECTION_STRING` in the deployments env variables too but the consumer still uses it. This PR clears the code of the tests and revert the change of that variable

Fix azure-blob e2e test

---

CHANGELOG.md
pkg/scalers/rabbitmq_scaler.go
pkg/scalers/rabbitmq_scaler_test.go
tests/scalers/rabbitmq-helpers.ts
tests/scalers/rabbitmq-queue-http-regex-vhost.test.ts
tests/scalers/rabbitmq-queue-http-regex.test.ts

The vhost is included when you don't use `useRegex: true`. It makes
sense to have consistent behaviour between the two modes.
Fixes #2498
Fixes #

Include vhost for RabbitMQ when retrieving queue info with useRegex

---

Dockerfile
Dockerfile.adapter
Makefile

After merging https://github.com/kedacore/keda/pull/2708, ARM image is broken (I have discovered that during smoke test creation). We should always use [BuildKit](https://docs.docker.com/engine/reference/builder/#buildkit) even for pipelines which doesn't create multi arch images because the arguments are only passed if [BuildKit is enabled](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope).
Instead of setting default values in Dockerfile, this PR sets `DOCKER_BUILDKIT=1` to use BuildKit 
Related https://github.com/kedacore/keda/issues/2263

fix ARM cross compiling

---

CHANGELOG.md
tests/scalers/gcp-pubsub.test.ts

chore: Add pubsub scaler e2e test
Fixes #1528

Pubsub test

---

CHANGELOG.md
pkg/scalers/datadog_scaler.go
pkg/scalers/datadog_scaler_test.go
tests/scalers/datadog.test.ts

Several non-breaking fixes for the Datadog scaler. Fixes #2657
The problem described in #2657 is partially caused by the selection of a time window that is too small (15 seconds). Datadog doesn't have that metric yet in many cases, and returns an empty value, that logs as a warning in the HPA.
To avoid this from happening often, the user should select a bigger window, and also added some retries before giving up. I also changed the documentation, to discourage reducing the time window: https://github.com/kedacore/keda-docs/pull/682
To avoid this, we should remove the "age" parameter going forward, but as this is a breaking change, I will create a different PR for 2.7.
Other improvements in this PR:
* If more than one point is returned, return the last one,  instead of the first one, for …

Improve the Datadog scaler with non-breaking changes

---

CHANGELOG.md
pkg/scalers/prometheus_scaler.go
pkg/scalers/prometheus_scaler_test.go

Signed-off-by: Xoán Mallón <xoanmallon@gmail.com>
Fixes #2667

feat: add logic for prometheus scaler X-Scope-OrgID header

---

CHANGELOG.md
controllers/keda/hpa.go

In updateHPAIfNeeded, it should return error of update hpa object not newHPAForScaledObject, if updating failed.
Fixes https://github.com/kedacore/keda/issues/2719

Fix returns unmatched error when updating hpa object failed

---

CHANGELOG.md
pkg/scalers/datadog_scaler.go
pkg/scalers/datadog_scaler_test.go

Instead of trying to validate all potential valid queries ahead of creating the scaledobject, rely on the Datadog API to do so and return the error returned by the API if that happens. Also, rely on the Datadog API to apply the default rollup time frame if one is not specified in the query.
This way, if there are any addition to the query language down the line, we won't need to change the scaler code, while simplifying it.
Fixes #2761

Rely on Datadog API to validate the query

---

CHANGELOG.md
pkg/scalers/selenium_grid_scaler.go
pkg/scalers/selenium_grid_scaler_test.go

Signed-off-by: Alejandro Dominguez <adborroto90@gmail.com>
Consider grid `maxSession` to scale Selenium Grid.  Since each node can handle a number of parallel sessions defined by `maxSession`  then  is not needed to scale for each pending session. 
Example:  if maxSession=5 each node can hold up to 5 concurrent sessions. Therefore, if there are 10 requests in the queue, only 2 nodes are necessary to fulfill the requirements. Currently, the Selenium Grid Scaler of KEDA will scale up to 10 nodes in this case, ignoring the maxSessions per node.
Documentation changes: [PR](https://github.com/kedacore/keda-docs/pull/716) 
More info: 
* https://www.selenium.dev/documentation/grid/_print/#specific-browsers-and-a-limit-of-max-sessions
* https://www.selenium.dev/documentation/grid/advanced_features …

fix: Consider maxSessions in Selenium Grid Scaler

---

CHANGELOG.md
pkg/scalers/prometheus_scaler.go
pkg/scalers/prometheus_scaler_test.go

Prometheus: check and properly inform user that `threshold` is not set

---

CHANGELOG.md
pkg/scalers/gcp_stackdriver_scaler.go
pkg/scalers/gcp_stackdriver_scaler_test.go
pkg/scaling/scale_handler.go
tests/scalers/gcp-stackdriver.test.ts

feat: Add a scaler based on a GCP Stackdriver metric
Add a scaler based on a metric value obtained from GCP Stackdriver
Fixes: #2661

Add a scaler based on a GCP Stackdriver metric

---

pkg/scalers/datadog_scaler.go

I confused @arapulido on https://github.com/kedacore/keda/pull/2694 to include a wrong implementation of `IsActive()` function, fixing this here.
Relates #2657

Datadog: `isActive()` should react on `num > 0`

---

RELEASE-PROCESS.MD

In followup to these two issues:
- #2809
- #2810 
this PR updates the release-process notes to:
- Makes more prominent the side-note that reminds the release developer to update the VERSION in the template
- Removes the angle brackets around `<INSERT-CORRECT-VERSION>` because that makes the text disappear when the markdown is rendered/previewed -- since the renderer considers it to be a HTML tag. (It might be a good idea to remove all angle brackets from that template)
/cc @tomkerkhove

RELEASE-PROCESS.MD: make warning about required template changes more prominent

---

CHANGELOG.md
pkg/scalers/azure/azure_app_insights.go
pkg/scalers/azure_app_insights_scaler.go
pkg/scalers/azure_app_insights_scaler_test.go
pkg/scalers/datadog_scaler.go

Added support for three new fields in the trigger metadata for the eventhub scaler, `cloud`, `appInsightsResourceURL`, `activeDirectoryEndpoint`. The cloud parameter can be `azureChinaCloud`, `azureUSGovernmentCloud`, `azurePublicCloud`, or `private` (default is `azurePublicCloud`).
Sample ScaledObject definition -
```yaml
metadata:
name: app-insights
labels: {}
spec:
scaleTargetRef:
name: app-insights
minReplicaCount: 0
maxReplicaCount: 2
pollingInterval: 10
cooldownPeriod: 30
triggers:
- type: azure-app-insights
metadata:
metricAggregationTimespan: "0:1"
metricAggregationType: count
metricId: "customMetrics/testMetric"
targetValue: "100"
applicationInsightsId: <app-id>
tenantId: …
```

Enable support for non-public clouds in Application Insights scaler.

---

tests/run-all.sh

This PR disables azure data explorer e2e test [till this is solved](https://github.com/kedacore/keda/issues/2770)

Disable azure-data-explorer e2e test

---

tests/scalers/aws-dynamodb.test.ts

Fixes https://github.com/kedacore/keda/issues/2803

Increase DynamoDB e2e timeouts

---

.github/PULL_REQUEST_TEMPLATE.md

Use "Relates to" instead of "Fixes" given the majority of our PRs need doc/Helm changes as well and we only want to close afterward

chore: Use "Relates to" instead of "Fixes"

---

CHANGELOG.md
pkg/util/http.go

Signed-off-by: Louwrens Benade <tobias.benade@absa.africa>
Fixes #2577 
This patch addresses #2577 
- Simple implementation to allow the HTTPClient to read proxy variables, if available, from the environment.
- No tests updated, as all scalers should behave as normal.

Patch to make the HTTPClient proxy-aware

---

CHANGELOG.md
pkg/scalers/azure/azure_monitor.go
pkg/scalers/azure_monitor_scaler.go
pkg/scalers/azure_monitor_scaler_test.go

Supporting non-public clouds for the Azure Monitor scaler using the `cloud` parameter.
Sample ScaledObject definition -
```yaml
metadata:
name: monitor-so
spec:
scaleTargetRef: 
name: monitor-deployment
pollingInterval: 10
cooldownPeriod: 30
minReplicaCount: 0
maxReplicaCount: 2
triggers:
- type: azure-monitor
metadata:
resourceURI: <resource-uri>
tenantId: <tenant-id>
subscriptionId: <subscription-id>
resourceGroupName: <rg-name>
targetValue: <target>
metricName: <metric-name>
metricAggregationType: <metric-agg-type>
cloud: "private" 
resourceManagerEndpoint: <resource-manager-endpoint>
activeDirectoryEndpoint: <active-directory-endpoint>
authenticationRef:
name: monitor-ta
``` …

Non-public cloud support for Azure Monitor scaler.

---

CHANGELOG.md
pkg/scalers/azure/azure_data_explorer.go
pkg/scalers/azure_data_explorer_scaler.go
pkg/scalers/azure_data_explorer_scaler_test.go

Support for `cloud` parameter in Data Explorer trigger metadata.
Sample ScaledObject definition - 
```yaml
metadata:
name: kusto-so
spec:
scaleTargetRef: 
name: kusto-deployment
pollingInterval: 10
cooldownPeriod: 30
minReplicaCount: 0
maxReplicaCount: 2
triggers:
- type: azure-data-explorer
metadata:
tenantId: <tenant-id>
clientId: <client-id>
clientSecret: <client-secret>
endpoint: <endpoint>
databaseName: <database>
cloud: "private" # Optional
activeDirectoryEndpoint: <active-directory-endpoint> # Required when cloud = private
query: <query>
threshold: <threshold>
```
Documentation PR - https://github.com/kedacore/keda-docs/pull/736
Fixes #2734

Non-public cloud support for Azure Data Explorer scaler.

---

CHANGELOG.md

Following #2309 where we deprecated the `type` field from the CPU, Memory, and Datadog scalers.
Signed-off-by: amirschw <24677563+amirschw@users.noreply.github.com>

Add a deprecation notice for the 'type' field

---

CHANGELOG.md
tests/scalers/postgresql-hashicorp-vault.test.ts

Fixes https://github.com/kedacore/keda/issues/2842

Add Hashicorp Vault secret provider e2e test

---

CHANGELOG.md
go.mod
go.sum
pkg/scalers/azure/azure_blob.go
pkg/scalers/azure/azure_blob_test.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_blob_scaler_test.go

Sample ScaledObject spec -
```yaml
metadata:
name: blob-so
spec:
scaleTargetRef: 
name: blob-deployment
pollingInterval: 10
cooldownPeriod: 30
minReplicaCount: 0
maxReplicaCount: 2
triggers:
- type: azure-blob
metadata:
blobContainerName: keda
metricName: keda
globPattern: foo**
recursive: "true"
authenticationRef:
name: blob-ta
```
Documentation PR - https://github.com/kedacore/keda-docs/pull/738
Fixes #1789

Add globPattern, recursive parameters to Azure Blob Storage Scaler.

---

CHANGELOG.md
pkg/scalers/azure/azure_cloud_environment.go
pkg/scalers/azure/azure_cloud_environment_test.go
pkg/scalers/azure_app_insights_scaler.go
pkg/scalers/azure_data_explorer_scaler.go
pkg/scalers/azure_eventhub_scaler.go
pkg/scalers/azure_log_analytics_scaler.go
pkg/scalers/azure_monitor_scaler.go

Refactor active directory endpoint parsing for Azure scalers.
Relates to #1285

Refactor active directory endpoint parsing for Azure scalers.

---

CHANGELOG.md
pkg/scalers/kafka_scaler.go
pkg/scalers/kafka_scaler_test.go
tests/scalers/kafka.test.ts

When getting the consumer offset of a Kafka topic for which no offset
was committed yet, the scaler returns with -1 instead of 0, which
causes to scale to the maximum number of replicas.
This fix changes the behavior to return in that case either '1' (the default) or '0', depending on a new scaler parameter scaleToZeroOnInvalidOffset which default to 'false'
Also fixed some typos and used interim variables for error strings.
Fixes #2612 #2033

Return 1 or 0 instead of -1 when detecting an invalid offset in Kafka

---

CHANGELOG.md
pkg/scalers/external_scaler.go
pkg/scalers/scaler.go
pkg/scalers/scaler_test.go
tests/scalers/external-scaler.test.ts
tests/scalers/helpers.ts

Fix metric name passed to external scaler in GetMetrics call. 

---

CHANGELOG.md
tests/scalers/metrics-api-trigger-auth.test.ts
tests/scalers/metrics-api.test.ts

Signed-off-by: Alejandro Dominguez <adborroto90@gmail.com>
Adding test for metric-api scaler. [#2791](https://github.com/kedacore/keda/issues/2791).
Fixes #2791

Add e2e test for metric-api scaler

---

.github/workflows/main-build.yml
.github/workflows/nightly-e2e.yml

Helm team has merged the PR adding support to ARM to their action, this PR switches from mine action to the upstream action

chore: Update `kind-action` task to use the upstream

---

.github/ISSUE_TEMPLATE/3_bug_report.yml

Provide self-help in bug report template to reduce amount of bug reports that are documented in FAQ, troubleshooting guide or already reported in open bug or discussion.

chore: Provide self-help in bug report template

---

CHANGELOG.md
pkg/scalers/activemq_scaler.go
pkg/scalers/activemq_scaler_test.go

This PR addresses issue #2884 and adds CoreHeaders to ActiveMQ scaler queries using the same logic used by the the Artemis scaler in the activemq scaler.
Signed-off-by: Mark DeNeve <xphyr@users.noreply.github.com>
- [NA] Tests have been added
- [NA] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
Fixes #2884

adding CORS header to activemq scaler for issue #2884

---

tests/run-all.sh

By error, we could add extra spaces or new lines to the e2e command. It seems correct from GH UI but the workflow doesn't execute any test. This PR adds a check to return a failure from run-all.sh if there isn't any e2e test matching the regex.

Fail e2e tests if no test matches regex

---

controllers/keda/scaledobject_controller.go
pkg/scaling/scale_handler.go

Changed some comments and some misspellings throughout the source code, mostly in regards to the `scale_handler.go`
Fixes #

chore: fix some comments and some misspelling

---

.golangci.yml
adapter/main.go
controllers/keda/suite_test.go
main.go
pkg/scalers/authentication/authentication_helpers.go
pkg/scalers/aws_cloudwatch_scaler.go
pkg/scalers/aws_kinesis_stream_scaler.go
pkg/scalers/aws_sqs_queue_scaler.go
pkg/scalers/azure_blob_scaler.go
pkg/scalers/azure_eventhub_scaler_test.go
pkg/scalers/azure_pipelines_scaler.go
pkg/scalers/azure_queue_scaler.go
pkg/scalers/azure_servicebus_scaler.go
pkg/scalers/datadog_scaler.go
pkg/scalers/external_scaler_test.go
pkg/scalers/gcp_storage_scaler.go
pkg/scalers/influxdb_scaler.go
pkg/scalers/liiklus_scaler_test.go
pkg/scalers/metrics_api_scaler.go
pkg/scalers/mssql_scaler.go
pkg/scalers/openstack/keystone_authentication.go
pkg/scalers/openstack_metrics_scaler.go
pkg/scalers/openstack_metrics_scaler_test.go
pkg/scalers/openstack_swift_scaler.go
pkg/scalers/openstack_swift_scaler_test.go
pkg/scalers/predictkube_scaler.go
pkg/scalers/predictkube_scaler_test.go
pkg/scalers/scaler.go
pkg/scaling/cache/scalers_cache.go
pkg/scaling/executor/scale_scaledobjects.go

Add 'gci' linter for deterministic import order.

---

tests/run-all.sh
tests/scalers/argo-rollouts.test.ts
tests/scalers/influxdb.test.ts
tests/scalers/mysql.test.ts
tests/scalers/postgresql-hashicorp-vault.test.ts
tests/scalers/postgresql.test.ts
tests/scalers/redis-cluster-helper.ts
tests/scalers/redis-cluster-lists.test.ts
tests/scalers/redis-cluster-streams.test.ts
tests/scalers/redis-sentinel-lists.test.ts
tests/scalers/redis-sentinel-streams.test.ts

Summary of changes:
- [argo-rollouts](https://github.com/argoproj/argo-rollouts) e2e test used outdated manifest and that's why it fails:
- Small improvements in mysql
- Small improvements in postgresql
- Redis e2e tests don't use pvc any more (slow responses sometimes provisioning them produces timeout on tests)
- Influxdb e2e test doesn't use pvc any more (slow responses sometimes provisioning them produces timeout on test)

feat: improve e2e tests reliability

---

CHANGELOG.md
config/manager/manager.yaml
config/metrics-server/deployment.yaml

feat: use safe `securityContext` as default

---

CHANGELOG.md

Improve changelog to emphasize KEDA already supported running as non-root; but that we do it by default nowadays.
Relates to https://github.com/kedacore/keda/issues/2933

docs: Improve changelog around KEDA as secure by default

---

CHANGELOG.md
pkg/scalers/graphite_scaler.go
pkg/scalers/graphite_scaler_test.go

Do not mis-interpet null as zero
Use the latest non-null returned value in a query response
Fixes #2944

Fix Graphite Scaler doesn't properly handle null responses #2944

---

CHANGELOG.md
adapter/main.go

Fixes https://github.com/kedacore/keda/issues/2914

fix: Adapter has high qps to apiserver

---

.github/workflows/pr-e2e.yml

right now, the process is split in 2 jobs:
1. check permissions
2. the rest (single execution)
This PR adds an extra job to build images in parallel, non-blocking the e2e-concurrency for building images
1. triage
2. build images
3. the rest (single execution)
With current approach, we don't parallelize the image generation because it's inside the exclusive job, this PR solves the problem saving up to 7-8 minutes if there is an e2e test pending in the queue

feat: improve e2e on PR workflow
