kedacore/keda

pkg/scalers/azure_servicebus_scaler_test.go
Fixes an error in the servicebus scaler tests due to the change in default connection settings.
=> Fix scaler tests error re: default connection setting change

pkg/handler/scale_handler.go
=> don't scale if deployment is nil

README.md
Extends #162 by emphasizing "Experimental" phase in README.
/cc @jeffhollan
=> Emphasize Experimental Phase

examples/azurequeue_scaledobject.yaml, examples/azureservicebus_scaledobject.yaml, examples/kafka_scaledobject.yaml, examples/rabbitmq_scaledobject.yaml, examples/scaledobject.yaml
Discovered in https://github.com/kedacore/keda/issues/158 thanks to @zach-dunton-sf
=> fixing example labels

pkg/handler/scale_handler.go
=> Prevent HPA from getting 0 for MinReplicaCount

.github/kubevalidator.yaml
This PR configured [Kubevalidator](https://github.com/urcomputeringpal/kubevalidator) which needs to be installed on the GitHub repo.
While we are adding PR checks, I would also recommend using [YAMBURGER](https://github.com/urcomputeringpal/yamburger) which validates YAML syntax
Relates to #179
Once the PR is merged and the Apps are installed I'll create a sample PR of what it blocks to verify the configuration.
=> Configure Kubevalidator

pkg/handler/scale_handler.go
=> fix update ScaledObject

chart/keda/templates/scaledobject-crd.yaml
Addresses #200 as well as adding a singular form for "scaledobjects"
I'd love input on whether these are the shortnames you'd like to see.
=> Add singular and short names to scaledobject spec

pkg/handler/scale_handler.go
=> fix scale from zero when minReplicaCount is 0

pkg/apis/keda/v1alpha1/types.go, pkg/handler/scale_handler.go
=> allow multiple containers on deployment

README.md, examples/prometheus_scaledobject.yaml, pkg/handler/scale_handler.go, pkg/scalers/prometheus.go, pkg/scalers/prometheus_scaler_test.go
This PR adds the ability to scale to/from zero and 1:n with a vector/scalar prometheus query.
Closes #156
=> Add prometheus scaler

pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_test.go
Fixes tests and slight refactor to scaler resolved envs handling.
=> fix aws sqs test

chart/keda/README.md
Provide list of configuration values for Helm Chart.
This is a PR which is a clean version of #222
=> Provide list of configuration values for Helm Chart

README.md
=> enable ARM deployment

examples/awssqsqueue_scaledobject.yaml, pkg/scalers/aws_sqs_queue_scaler.go
Modified the AWS authentication to use the default provider chain before trying the credentials passed in from the configuration.
=> Update AWS authentication methods

spec/triggers/README.md
Fix broken link to specific trigger specs
=> [Docs] Fix broken link to specific trigger specs

.github/CODEOWNERS
Provide CODEOWNER file to automatically assign reviews.
I've added myself for the specification to focus on good docs and avoid breaking changes, but please do not feel obliged to add me.
=> Provide CODEOWNER file to automatically assign reviews

README.md
Following b8460e2741f74c8004bde892f53cd35f030141a6, how did I manage to add a sample but miss the main README?
=> Add liiklus to the list of supported scalers

chart/keda/Notes.txt
Provide Notes.txt for Helm chart
Replaces #315 per @ahmelsayed 	his request.
=> Provide Notes.txt for Helm chart

pkg/scalers/azure_eventhub.go, pkg/scalers/azure_eventhub_test.go
=> add error handling

README.md
=> Mention Event Hub scaler limitations in README

.vscode/launch.json, pkg/handler/scale_handler.go, pkg/scalers/rabbitmq_scaler.go
=> Close Rabbitmq connections properly

deploy/KedaScaleController.yaml, tests/cleanup.test.ts
- removed an unused clusterrole
- changed the name of hpa-controller-custom-metrics clusterrolebinding
closes #371
=> fix KedaScaleController so that it can be installed alongside knative

README.md
=> Create `keda` namespace when using kubectl apply -f deploy/

.github/workflows/master-build.yml
Forgot to update the CI environment as part of #424
=> Add STORAGE_HELM_SAS_TOKEN to github publish action

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md
This adds a VSCode Remote devcontainer to make it super easy for new contributors to get up and running quickly. 
https://code.visualstudio.com/docs/remote/containers
=> Add devcontainer

examples/azureservicebus_scaledobject.yaml, pkg/handler/scale_handler.go, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/azure_servicebus_scaler_test.go, spec/triggers/azure-service-bus.md
=> Read triggerAuthentication values for service bus

README.md, examples/redis_scaledobject_auth.yaml, pkg/handler/scale_handler.go, pkg/scalers/redis_scaler.go, pkg/scalers/redis_scaler_test.go, spec/triggers/redis.md
Addresses the issue https://github.com/kedacore/keda/issues/342
=> Use Trigger Authentication for Redis Scaler

pkg/handler/scale_handler.go, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go, spec/triggers/rabbit-mq-queue.md
=> Read triggerAuthentication values for Rabbitmq

CONTRIBUTING.md
=> adding contributor guide

README.md
- Add Twitter badge to README & align build badge
- Format community standup info
Relates to https://github.com/kedacore/keda/issues/435
=> Community improvements

README.md
Adding a few things back in just so they are super discoverable.  Like the quickstarts, how to deploy.  I also think having a badge for the nightly test is a good signal of quality.
=> readme changes for 1.0.0

README.md
=> IM on Kubernetes Slack

.github/ISSUE_TEMPLATE/Feature_request.md
Label feature requests with `feature-request` and use `feature` for those that we commit to
=> Label feature requests with `feature-request`

pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_test.go
Add tests for queueURL to queueName parsing
=> Add unique name for aws-sqs-queue metrics

README.md
Switch to bi-weekly meetings
Relates to #502
=> Switch to bi-weekly community meetings

pkg/scalers/huawei_cloudeye_scaler.go
ensure get the metrics that have been aggregated for huaweicloud cloudeye.
=> ensure get the metrics that have been aggregated

README.md
Reverts kedacore/keda#513
Sorry for being a pain @ahmelsayed but we've decided to not do this for now in the standup today.
=> Revert "Switch to bi-weekly community meetings"

pkg/scalers/prometheus.go
Url escape prometheus query before sending it
=> Escape Prometheus querystring

CREATE-NEW-SCALER.md
As mentioned in issue #531 there are few typos in the CREATE-NEW-SCALER.md file, this PR is just trying to fix them.
=> Fix typos in CREATE-NEW-SCALER.md

README.md
Related to discussion in https://github.com/kedacore/keda/issues/240#issuecomment-577753303
=> Update readme steps for deploying custom KEDA

RELEASE-PROCESS.MD
Move release process to Markdown in repo to use PRs as review process.
Last piece before we can remove the wiki (#460)
=> Move release process to Markdown in repo

.devcontainer/Dockerfile
=> Fix gopls location

.github/ISSUE_TEMPLATE/Bug_report.md
Fixes https://github.com/kedacore/keda/issues/588
=> Add kubernetes and platform version to the Issue template

pkg/scalers/kafka_scaler.go
- Added SASL_SSL Plain authentication for Kafka Trigger Scalar.
- Removed extra newline characters being read from secrets file
This enables connecting Event Hub w/Kafka head as a scalar for KEDA.
Event Hub w/Kafka uses SASL_SSL authentication without certs with just PLAIN mechanism and needs specific TLS config while using the Sarama Go package.
TO DO:
- Update KEDA documentation to advertise this feature
- Add sample
=> [Feature] Added SASL_SSL Plain authentication for Kafka trigger scalar to work with Event Hubs

.github/PULL_REQUEST_TEMPLATE.md
Proposal for PR template so that everybody knows that is expected.
=> Proposal for PR template

README.md
This PR addresses #598 trying to mention the possible reason for the "checksum mismatch" error.
=> Mentioning problem with checksum mismatch error

deploy/00-namespace.yaml, deploy/01-service_account.yaml, deploy/10-cluster_role.yaml, deploy/11-role_binding.yaml, deploy/12-operator.yaml, deploy/20-metrics-cluster_role.yaml, deploy/21-metrics-role_binding.yaml, deploy/22-metrics-deployment.yaml, deploy/23-metrics-service.yaml, deploy/24-metrics-api_service.yaml, version/version.go
Please see the release notes for the changes:
https://github.com/kedacore/keda/releases/tag/v1.2.0
=> Keda release 1.2.0

pkg/scalers/kafka_scaler_test.go
This PR adds a couple of successful tests to the Kafka scaler and also fixes the password field.
=> Added successful tests to Kafka scaler

README.md
=> Update documentation to link to new Openshift 4 sample

LICENSE
=> updating license to Apache per CNCF donation

.github/CODEOWNERS
Make @zroubalik codeowner instead of @Aarthisk
=> Make @zroubalik codeowner instead of @Aarthisk

pkg/scalers/mysql_scaler.go
Fixes #
Typos in MySQL scaler logging.
=> Fix typos in MySQL scaler

CONTRIBUTING.md, README.md
=> Add DCO and remove Microsoft CLA section

tests/package-lock.json
Signed-off-by: Ahmed ElSayed <ahmed@elsayed.io>
Updating transient dependencies in the test project.
=> Update test dependencies

README.md
Introduce CII Badge which is required for CNCF
Relates to #667
=> Introduce CII Badge

README.md
Minor correction on Deploying KEDA documentation link.
Relevant to this doc PR: https://github.com/kedacore/keda-docs/pull/128
=> correct deploying methods

CONTRIBUTING.md, GOVERNANCE.md, README.md, pkg/controller/scaledobject/scaledobject_controller.go, pkg/scalers/prometheus.go, tests/package-lock.json
Relates to https://github.com/kedacore/keda-docs/issues/51
=> Link to guide for adding new scaler docs

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Provide better guidance around contributions & DCO:
- Add check in PR template
- Add note on how to fix unsigned commits
=> Provide better guidance around contributions & DCO

.github/workflows/v2-build.yml, tools/build-tools.Dockerfile
- [ `N/A` ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ `N/A` ] Commits are signed with Developer Certificate of Origin (DCO)
- [ `N/A` ] Tests have been added
=> Add a temporary github action for v2 branch

GOVERNANCE.md
Resolves https://github.com/kedacore/keda/issues/725
Was going to add more but decided to keep it pretty simple. Happy to clarify if we feel clarification is needed
=> add ability to ask to be maintainer

RELEASE-PROCESS.MD
Provide step for Helm chart release in release process so that people subscribing to the repo get notified and can see what has changed.
=> Provide step for Helm chart release in release process

deploy/00-namespace.yaml, deploy/01-service_account.yaml, deploy/10-cluster_role.yaml, deploy/11-role_binding.yaml, deploy/12-operator.yaml, deploy/20-metrics-cluster_role.yaml, deploy/21-metrics-role_binding.yaml, deploy/22-metrics-deployment.yaml, deploy/23-metrics-service.yaml, deploy/24-metrics-api_service.yaml, version/version.go
https://github.com/kedacore/keda/milestone/11?closed=1
=> Prepare release v.1.4.1

CHANGELOG.md
=> Provide changelog for v1.4.1

RELEASE-PROCESS.MD
Publish new documentation for new releases
Depends on https://github.com/kedacore/keda-docs/pull/168
=> Publish new documentation for new releases

README.md
We are meeting at 16 UTC for standup nowadays
=> We are meeting at 16 UTC for standup nowadays

.github/ISSUE_TEMPLATE/Support.md, .github/ISSUE_TEMPLATE/config.yml
Use GitHub discussions for questions & support
Fixes #825
=> Use GitHub discussions for questions & support

.github/workflows/release-build.yml
- [ `N/A` ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs
- [ `N/A` ] Tests have been added
Fixes #
=> Set VERSION output in github action

tests/scalers/prometheus.test.ts
Adding some logging to debug the Prometheus e2e. @ahmelsayed I see there are issues with my merged PR. I am not sure what is happening in the cluster the e2e is running on as the tests are working locally. I am open to suggestions of how to further debug this.
=> Prometheus e2e logging

tests/scalers/prometheus.test.ts
Had logging in incorrect spot in the prior PR. Added additional output of the job description itself for debugging purposes
=> Adding additional logging to debug the prometheus e2e

deploy/crds/keda.sh_v1alpha1_scaledobject_cr.yaml, deploy/crds/keda.sh_v1alpha1_triggerauthentication_cr.yaml, tests/scalers/prometheus.test.ts, tests/scalers/rabbitmq-queue-amqp.test.ts, tests/scalers/rabbitmq-queue-http.test.ts, tests/scalers/rabbitmq-queue-trigger-auth.test.ts
Changing apiVersion to `keda.sh` in a new tests added by recent rebase from master
=> [v2] post merge: change apiversion to keda.sh

tools/build-tools.Dockerfile
=> [v2] build-tools: updated operator-sdk to v0.17.1

deploy/12-operator.yaml, deploy/22-metrics-deployment.yaml, pkg/scalers/azure_eventhub_scaler.go
Nodeselector for linux machines have been statically added to deployments objects when needed.
=> Linux nodeselector

tools/build-tools.Dockerfile
=> Use keyserver.ubuntu.com instead of packages.microsoft.com

CHANGELOG.md
=> [v2] add v2 changes to the Changelog

CHANGELOG.md
=> Fix broken links in changelog

tests/scalers/kafka.test.ts
Signed-off-by: samuelmacko <samuel.macko.sm@gmail.com>
Fixed kafka e2e test.
=> Fix kafka e2e test

pkg/scalers/kafka_scaler.go
Minor improvement: Sarama Kafka client lib now allows us to create `admin client` directly from already created `client`.
=> [v2] change how kafka admin client is created

tests/scalers/kafka.test.ts
=> E2e repair

CHANGELOG.md
=> Provide changelog of v1.5 release

deploy/00-namespace.yaml, deploy/01-service_account.yaml, deploy/10-cluster_role.yaml, deploy/11-role_binding.yaml, deploy/12-operator.yaml, deploy/20-metrics-cluster_role.yaml, deploy/21-metrics-role_binding.yaml, deploy/22-metrics-deployment.yaml, deploy/23-metrics-service.yaml, deploy/24-metrics-api_service.yaml, version/version.go
=> prepare release v1.5.0

.github/workflows/release-build.yml, Makefile, RELEASE-PROCESS.MD
- modified Makefile target for updating VERSION, `make set-version`
- generate KEDA Deployment archives in the release workflow
Extending the work proposed in https://github.com/kedacore/keda/pull/917
=> Improved release process

tests/scalers/kafka.test.ts
Signed-off-by: samuelmacko <samuel.macko.sm@gmail.com>
Kafka e2e test fix.
=> Another fix of kafka e2e-test

CHANGELOG.md
=> [v2] add Standard Resource metrics note to Changelog

tests/setup.test.ts
=> e2e: print kubernetes version at startup

.github/workflows/fossa.yml
Fixes #808
See https://docs.fossa.com/docs/api-reference for more details.
Signed-off-by: Ihor Dvoretskyi ihor@linux.com
=> Push-only API key added

tests/scalers/mysql.test.ts
Adding MySQL Scaler End-to-End Test
=> Mysql Scaler e2e

tests/scalers/mysql.test.ts
It looks like the e2e is failing on the cluster. I suspect it may be a performance difference in the startup time of MySQL.  The build log is showing the test is triggering an error when trying to connect to MySQL to create the table:  
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
command terminated with exit code 1
```
I am adding a readiness probe to ensure that MySQL is truly ready for transactions. I originally hard-coded a wait time but using the readiness probe is much better.
=> Adding in readiness probe for mysql e2e

pkg/scaling/scale_handler.go
This PR is fix for https://github.com/kedacore/keda/issues/801
The logic didn't refer the MaxReplicaCount.  The logic for creating job by the SUDO code will be: 
```
MIN(maxReplicaCount, Ceil(Queue Length /(TargetAverageValue * Number of Scalers))) - RunningJobCount
```
I have two questions. `scale_handler.go` doesn't have any testing. So I follow the convention, however, if you like, I can add the test for it. For the documentation, this is v2 work. I can't find v2 branch on https://github.com/kedacore/keda-docs . Where should we change the documentation?
Fixes #
https://github.com/kedacore/keda/issues/801
=> [v2] Change the maxValue behavior to refer the maxReplicaCount

tests/scalers/redis-lists.test.ts
Adding e2e tests for the Redis Scalers
=> Redis Lists Scaler e2e

CHANGELOG.md
=> [v2] Add Managed Identity support for Azure Monitor scaler to changelog 

CHANGELOG.md
=> [v2] Changelog note about multiple triggers and Kafka offset reset policy

Makefile, tests/package.json, tests/run-all.sh
Update the e2e to run each `*.test.ts` in a separate node process.
=> run each e2e test in a separate process

.github/workflows/build-tools.yml, Makefile
=> produce kedacore/build-tools image in GitHub Action

CHANGELOG.md
=> [v2] add Redis auth params info to changelog

.github/workflows/build-tools.yml, Makefile, tests/package.json, tests/run-all.sh
`Rebase and merge` this instead of `Squash and merge`
=> [v2] cherry picking e2e tests fixes and build tools ci from master

go.mod, go.sum, tools/build-tools.Dockerfile
This should be merged first: https://github.com/kedacore/keda/pull/980
=> [v2] switch to go 1.14

tests/run-all.sh
=> e2e tests: print KEDA logs and failed tests

pkg/controller/scaledobject/hpa.go, pkg/scaling/scale_handler.go
=> [v2] Labels from ScaledObject to HPA

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Provide docs on updating changelog in pull request template.
=> Provide docs on updating changelog in pull request template

CHANGELOG.md
Document Prometheus metrics for KEDA Metrics API Server.
Relates to #823
=> [v2]  Document Prometheus metrics for KEDA Metrics API Server

pkg/scalers/aws_cloudwatch_scaler.go, pkg/scalers/azure_monitor_scaler.go, pkg/scalers/azure_monitor_scaler_test.go, pkg/scalers/cron_scaler.go, pkg/scalers/huawei_cloudeye_scaler.go, pkg/scalers/mysql_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go, pkg/util/normalize_string.go
Signed-off-by: Samuel Macko <samuel.macko.sm@gmail.com>
Updates #985
=> [v2] Fixing escaping of chars in metric names

README.md
Add Link to the Sample Repo for ScaledJob with Azure Storage Queue. 
https://github.com/kedacore/sample-go-storage-queue
It includes sender/receiver written by go lang.
=> [v2] Add Sample repo for Azure Storage Queue and  ScaledJob

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
cherry-picking from master: #999
=> [v2] Provide docs on updating changelog in pull request template (#999)

Makefile, config/crd/kustomization.yaml, config/rbac/role.yaml, controllers/scaledjob_controller.go, controllers/scaledobject_controller.go
=> [v2] add rbac access to triggerAuthentication CRD

pkg/scaling/executor/scale_jobs.go
very minor chores, resolving TODOs from the code and moving defaults to the const block
=> [v2] chores: moving defaults to const

pkg/provider/provider.go, pkg/scaling/executor/scale_jobs.go, pkg/scaling/executor/scale_scaledobjects.go
1. Improving log messages for ScaledJob -  they should contain ScaledJob Name and Namespace
2. Minor ScaledObject log messages chores
Fixes #952
=> [v2] improving ScaledJob log messages

README.md
This PR adds some line breaks for better readability and improves
wording.
=> Fix some wording and line breaks in README

pkg/scalers/mysql_scaler_test.go
=> Fix typos in MySQL scaler tests

pkg/scalers/mysql_scaler_test.go
=> [v2] Fix typos in MySQL scaler tests (#1028)

Makefile, README.md
=> [v2] Fixing minor typos and formatting in Readme

CREATE-NEW-SCALER.md
=> [v2] add details on creating a new scaler

.pre-commit-config.yaml, controllers/scaledjob_controller.go, controllers/scaledobject_controller.go, controllers/util/status.go, controllers/util/string_lists.go
=> Make controllers/ golint compatible

.pre-commit-config.yaml, hack/tools.go, pkg/util/gvkr.go, pkg/util/k8sversion.go, pkg/util/normalize_string.go, version/version.go
Make pkg/util golint compatible
Fixes #1058
=> Make pkg/util golint compatible

Makefile
Fix sed command as suggested here https://stackoverflow.com/a/4247319/9713409
Also fix sed regexp pattern to match version after golint changes
=> Fix sed commands to work on OS X

pkg/scalers/redis_scaler.go
Fixing bug brought by #1013
Fixes #1066
=> [v2] Redis Lists: default to list type if none specified

pkg/scalers/metrics_api_scaler.go
Small improvement to #1026 
Fixes #
=> Handle non 200 errors in MetricsAPIScaler

README.md
Per new zoom policy that meetings must have a password or waiting room
=> [README] zoom link with password

CHANGELOG.md
Make changelog more readable - Nits everywhere!
=> Make changelog more readable

tests/scalers/azure-blob.test.ts, tests/scalers/azure-queue-restore-original-replicas.test.ts, tests/scalers/azure-queue-trigger-auth.test.ts, tests/scalers/azure-queue.test.ts, tests/scalers/kafka.test.ts, tests/scalers/mysql.test.ts, tests/scalers/prometheus.test.ts, tests/scalers/rabbitmq-queue-amqp.test.ts, tests/scalers/rabbitmq-queue-http.test.ts, tests/scalers/rabbitmq-queue-trigger-auth.test.ts, tests/scalers/redis-lists.test.ts, tests/scalers/redis-streams.test.ts
1. Changing some e2e tests to comply the new metadata spec brought by #1072 
2. Change the cleanup sequence, to clen ScaledObject and TriggerAuth first
=> [v2] fixing e2e tests

Makefile
=> [v2] add Makefile target for runing e2e tests against local cluster

Makefile, config/metrics-server/deployment.yaml, config/metrics-server/kustomization.yaml
Signed-off-by: Chaitanya Kuduvalli Ramachandra <chaitanya.r@ETC02Y77ZVJG5H.local>
https://github.com/kedacore/keda/issues/1105
Fixes #1105
=> Changing the docker image name from adapter to apiserver

CHANGELOG.md
=> [v2] update changelog

controllers/hpa.go
Minor bug fix:
As reported in #1068, when the `HPA` was updated, the controller could not add the correct ownerRef to the updated `HPA` (pointing to the `ScaledObject`). So when `ScaledObject` is deleted, `HPA` is not deleted as well. 
Moving the `controllerutil.SetControllerReference()` to the end of `newHPAForScaledObject()` function. So every created HPA contains the correct ownerRef.
=> set ownerRef on updated HPA

Makefile, api/v1alpha1/condition_types.go, api/v1alpha1/groupversion_info.go, api/v1alpha1/gvkr_types.go, api/v1alpha1/scaledjob_types.go, api/v1alpha1/scaledobject_types.go, api/v1alpha1/triggerauthentication_types.go, controllers/scaledjob_controller.go, controllers/scaledobject_controller.go, pkg/scaling/executor/scale_executor.go, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/scale_resolvers.go, pkg/scaling/resolver/scale_resolvers_test.go
Recently go lint has been changed to revive. There were pending linting issues in few files. This PR is to address those issues.
Fixes #1054
=> refactor[v2]: fixing revive issues to make project revive compatible

tests/scalers/azure-queue-restore-original-replicas.test.ts
Fixes test case which got broken by https://github.com/kedacore/keda/pull/1131
Not sure how this was passing. 
Fixes #
=> Fix azure-queue-restore-original-replicas test

.github/workflows/v2-build.yml
missed this in the code review for #1085
=> Add Azure Log Analytics workspace ID to github action

.pre-commit-config.yaml, CONTRIBUTING.md
I didn't know that we had such nice doc on e2e test 🚀 
Fixes #
=> Add information about e2e test in CONTRIBUTING

BRANDING.md, README.md
Provide branding guidelines
Relates on #1080
Fixes #1090
=> Provide branding guidelines

Makefile, README.md
=> regenerate Readme & exclude liiklus mock from revive

README.md
=> KEDA v2 Beta instructions

pkg/scaling/resolver/scale_resolvers.go
=> the address of a variable cannot be nil

pkg/scalers/external_scaler.go
fix external get metadata
Fixes #1157
=> fix external get metadata

pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_log_analytics_scaler_test.go, pkg/scaling/scale_handler.go
This PR introduce a possibility to authenticate Log Analytics scaler using PodIdentity.
It is related to this issue: [#1165](https://github.com/kedacore/keda/issues/1165)
Also, a minor refactoring changes is part of this PR.
Signed-off-by: Sergiy Poplavskyi <spopla@microsoft.com>
=> [v2] Added PodIdentity authentication support for Log Analytics scaler.

config/rbac/role.yaml, controllers/scaledjob_controller.go
Fixes https://github.com/kedacore/keda/issues/1178
=> adding scaledjobs/finalizers to rbac

.golangci.yml, controllers/suite_test.go, pkg/scalers/azure/azure_blob.go, pkg/scalers/azure/azure_storage.go, pkg/scalers/azure_blob_scaler.go, pkg/scalers/azure_queue_scaler.go, pkg/scalers/external_scaler.go, pkg/scalers/external_scaler_test.go, pkg/scalers/redis_scaler_test.go
enable golangci lint:goimports
Fixes #
=> enable golangci lint:goimports

.golangci.yml, adapter/main.go, controllers/hpa.go, pkg/scalers/azure/azure_aad_podidentity.go, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/kafka_scram_client.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/scaler.go, pkg/scalers/stan_scaler.go, pkg/scaling/resolver/hashicorpvault_handler.go
enable golangci lint:misspell,bodyclose
Fixes #
=> enable golangci lint:misspell,bodyclose

config/crd/kustomization.yaml, config/crd/patches/scaledjob_patch.yaml
In #1202 we have updated CRDs to version v1, but we need to modify the ScaledJob patch (https://github.com/kedacore/keda/issues/927) as well.
=> modify ScaledJob CRD patch for version v1

RELEASE-PROCESS.MD
Provide release template and publish docs before containers
=> Provide release template and publish docs before containers

.golangci.yml, controllers/suite_test.go, pkg/scalers/aws_iam_authorization.go, pkg/scalers/aws_kinesis_stream_test.go, pkg/scalers/aws_sqs_queue_test.go, pkg/scalers/azure/azure_monitor_test.go, pkg/scalers/azure_eventhub_scaler_test.go, pkg/scalers/external_scaler_test.go, pkg/scalers/mysql_scaler.go, pkg/scalers/postgresql_scaler.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/stan_scaler.go
Signed-off-by: Michele <mdeggies@gmail.com>
Enabled  golangci lint: deadcode and removed unused references
- [ X ] Commits are signed with Developer Certificate of Origin (DCO)
Fixes # https://github.com/kedacore/keda/issues/1158
=> enable golangci lint: deadcode

README.md
=> add RC version info

.golangci.yml, pkg/scalers/aws_kinesis_stream_scaler.go, pkg/scalers/azure/azure_monitor.go, pkg/scalers/external_scaler.go, pkg/scalers/kafka_scaler.go, pkg/scalers/liiklus_scaler.go, pkg/scalers/stan_scaler.go, pkg/scaling/resolver/scale_resolvers.go
Signed-off-by: Artem Yarmoluk <koolgen@gmail.com>
Enable `unconvert` linter
Fixes #1158
=> Enable gloangcilint: unconvert

.golangci.yml, controllers/util/status.go, pkg/provider/provider.go, pkg/scalers/artemis_scaler.go, pkg/scalers/aws_cloudwatch_scaler.go, pkg/scalers/aws_iam_authorization.go, pkg/scalers/aws_kinesis_stream_scaler.go, pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/azure/azure_monitor.go, pkg/scalers/azure_blob_scaler.go, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_monitor_scaler.go, pkg/scalers/azure_queue_scaler.go, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/cron_scaler.go, pkg/scalers/gcp_pub_sub_scaler.go, pkg/scalers/huawei_cloudeye_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/redis_scaler.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/stackdriver_client.go, pkg/scaling/executor/scale_executor.go, pkg/scaling/executor/scale_jobs.go, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/scale_resolvers.go
Signed-off-by: Michele <mdeggies@gmail.com>
Enables golint for unconvert, unused, and stylecheck. 
- [ X ] Commits are signed with Developer Certificate of Origin (DCO)
Fixes # https://github.com/kedacore/keda/issues/1158
=> enable golint:unconvert,unused,stylecheck

pkg/scaling/resolver/scale_resolvers.go, pkg/scaling/resolver/scale_resolvers_test.go
This PR adds support to parsing dependent environment variables.
Fixes #1197
=> Add support to parsing dependent environment variables

pkg/scaling/scale_handler.go
Minor fix:
Build is failing because we merged 2 PRs in the same time (one of them enabled check, that is causing the failure)
=> fix linting issues

CHANGELOG.md
https://github.com/kedacore/keda/pull/1227 is missing in the Changelog
=> Changelog: Add Scaling Strategy for ScaledJob

pkg/scalers/redis_scaler.go
Signed-off-by: Mohamed Al Ashaal <m7medalash3al@gmail.com>
fixing #1243 
Fixes #
- #1243
=> using lua script in fetching the list type and length in redis scaler

.github/workflows/v2-build.yml
=> fix v2 workflows name

pkg/scalers/metrics_api_scaler.go, pkg/scalers/metrics_api_scaler_test.go
Signed-off-by: aman-bansal <bansalaman2905@gmail.com>
This change is in accordance with the review from https://github.com/kedacore/keda-docs/pull/260. Both need to be merge for this.
Docs PR https://github.com/kedacore/keda-docs/pull/260
=> fix: renaming auth mode as per documentation review

README.md
We have changed the workflow name in: https://github.com/kedacore/keda/pull/1252 thus changing the badge as well.
=> point badge to v2 build

.golangci.yml, controllers/scaledjob_controller.go, pkg/scalers/mysql_scaler_test.go, pkg/scalers/postgresql_scaler_test.go, pkg/scalers/rabbitmq_scaler_test.go, pkg/scalers/redis_streams_scaler_test.go, pkg/scaling/executor/scale_jobs.go, pkg/scaling/resolver/scale_resolvers_test.go, pkg/util/k8sversion_test.go
Signed-off-by: akartasov <agneum@gmail.com>
Enable golangci-lint for scopelint and structcheck
Fixes #1158
=> enable golangci-lint: scopelint, structcheck (#1158)

README.md
=> install instructions for 2.0.0 RC2

BUILD.md
Add the section how to enable profiling on `BUILD.md` doc. 
=> Add reference to how to setup profiler

pkg/scaling/scale_handler.go
Signed-off-by: 天元 <jianbo.sjb@alibaba-inc.com>
Fixes #
=> fix buildScalers panic when podTemplateSpec is nil

CREATE-NEW-SCALER.md
Fixed a couple of typos and made spacing more consistent.
Signed-off-by: Andrew Schneider <andjschneider@gmail.com>
I'm thinking about helping with a new scaler and noticed a few small typos and spacing inconsistencies while going through the docs. Thought this would be a good way to get familiar with the PR flow. Hopefully it's helpful!
Fixes #
=> Fix typos in CREATE-NEW-SCALER

pkg/provider/provider.go
=> fix panic when use cpu/memory and other scaler together

BUILD.md, CONTRIBUTING.md, README.md
=> chores after migrating to main branch

main.go
There's nothing like KEDA commit :)
=> print Git commit not KEDA commit

README.md
This content was a little bit lost, not it gets rendered in the TOC
=> add Building & deploying locally to the separate section

README.md
=> remove RC install instructions

Dockerfile, Dockerfile.adapter, Makefile
=> pass version string to docker build

CHANGELOG.md
We should add changes to this section and rename it once it is clear we are about to release
=> add unreleased section to the changelog

.golangci.yml, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_monitor_scaler.go
Signed-off-by: Girish Ramnani <girishramnani95@gmail.com>
enable gocyclo in golintCI and resolve the warnings by refactoring certain functions
~~- [ ] Tests have been added~~ N/A
~~- [ ] A PR is opened to update the documentation on https://github.com/kedacore/keda-docs~~ N/A
Partially https://github.com/kedacore/keda/issues/1158
=> enable gocyclo in golintCI and resolve the warnings

.golangci.yml, pkg/scalers/metrics_api_scaler.go
Signed-off-by: Shubham shubham.kuchhal@india.nec.com
This PR enable goconst in .golangcli.yml and remove the lint errors or warnings which shown on running **golangci-lint run**
PartiallyFixes #1158
=> Enable goconst in .golangcli.yml and remove the warnings

README.md, SUPPORT.md
Provide initial support policy for KEDA to help people understand how to get help, FAQ, troubleshoot and our Kubernetes support model.
Once this is merged, a PR will be opened to link to it on keda.sh.
=> Provide initial support policy for KEDA

.github/workflows/build-tools.yml, .github/workflows/fossa.yml, .github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/v1-build.yml
=> Revert update to actions/checkout requirement to v2.3.4

.github/workflows/fossa.yml, .github/workflows/pr-validation.yml, Dockerfile, Dockerfile.adapter, tools/build-tools.Dockerfile
=> Bump to Go 1.15.5

pkg/scalers/influxdb_scaler.go
Signed-off-by: Shubham82 <shubham.kuchhal@india.nec.com>
update the influxdb_scaler.go as i encountered errors while running the command  **golangci-lint run**.
=> Fix linting in influxdb_scaler.go

pkg/scalers/influxdb_scaler.go
=> influxdb: fix env resolving

.golangci.yml, adapter/main.go, controllers/scaledobject_controller.go, go.sum, pkg/metrics/prometheus_metrics.go, pkg/scalers/artemis_scaler.go, pkg/scalers/external_scaler.go, pkg/scalers/rabbitmq_scaler_test.go, pkg/scalers/stan_scaler.go, pkg/scaling/executor/scale_jobs.go, pkg/scaling/executor/scale_jobs_test.go, pkg/scaling/executor/scale_scaledobjects.go, pkg/scaling/resolver/scale_resolvers_test.go
This PR enable errcheck in .golangcli.yml and remove all the lint errors or warnings shown on running golangci-lint run.
Partially Fixes #1158
=> Enabled errcheck Linter in golangci.yml

RELEASE-PROCESS.MD
Hi there,
As said in title mostly fixing a 404 issue with URL for releases page
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>
=> fixing http 404 on mention of releases page

CREATE-NEW-SCALER.md
Hi there,
as per title
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>
=> CREATE_NEW_SCALER: fix typos

BUILD.md
Hi there,
As per title.
Ultimate typos that I found on the site.
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>
=> BUILD.md: fixing some typos

SECURITY.md
Provide security policy to talk about:
- What versions we support
- How we will prevent vulnerabilities
- How people can disclose vulnerabilities privately
- How we communicate changes
Fixes https://github.com/kedacore/governance/issues/3
=> Provide security policy

pkg/scalers/influxdb_scaler.go, pkg/scalers/influxdb_scaler_test.go, pkg/scalers/postgresql_scaler.go, pkg/util/normalize_string.go
Signed-off-by: Yoofi Quansah <yqsummon@gmail.com>
Fixes #
=> chore: use different metric default name

pkg/scalers/rabbitmq_scaler_test.go
=> increasing HTTP timeout to fix flaky test

README.md
Fixing links to workflow actions to point to the actual actions for main and nightly run
=> Fixing links to workflow actions

tests/scalers/azure-blob.test.ts
Increase the number of blobs generated in azure-blob test
=> Increase number of blobs generated in azure-blob test

.github/workflows/fossa.yml, .github/workflows/pr-validation.yml, Dockerfile, Dockerfile.adapter, tools/build-tools.Dockerfile
=> Bump Golang to 1.15.6

.github/workflows/main-build.yml, .github/workflows/release-build.yml
Related: https://github.com/kedacore/keda/pull/1512#issuecomment-763537478
=> Go modules sync in GH workflows

pkg/scalers/azure/azure_monitor.go
Very minor fix, KEDA operator is using ` controller-runtime logging`, in azure monitor there was `klog` left. Replacing it to have consistent logging.
=> Azure Monitor Scaler: remove klog to unify logging

adapter/main.go, go.mod
Bump the klog version from v1 to v2.
=> Bump klog version to v2

CHANGELOG.md
Provide v2.1.0 section in release notes.
=> docs: Provide v2.1.0 section in release notes

RELEASE-PROCESS.MD
Note that Azure Function CLI is optional during release.
=> docs: Note that Azure Function CLI is optional during release

CHANGELOG.md
=> add MongoDB scaler to Changelog

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Add Helm chart to PR template

.github/ISSUE_TEMPLATE/3_bug_report.yml
Add "Any" as option for platform in bug report
=> chore: Add "Any" as option for platform in bug report

CHANGELOG.md, pkg/scalers/azure/azure_aad_podidentity.go
Fixes #1566
Opened https://github.com/kedacore/keda/issues/1599 to track adding an e2e test for this.
=> Add 'Metadata' header to AAD podIdentity request

.devcontainer/Dockerfile
As per discussion here #1610, I have Updated the **golang version** and **OPERATOR_RELEASE_VERSION**  in Dockerfile.
Fixes #1610
=> Update Dockerfile in .devcontainer.

.pre-commit-config.yaml
=> Updating precommit

config/crd/bases/keda.sh_scaledjobs.yaml
=> regenerate ScaledJob CRD

.golangci.yml, adapter/generated/openapi/zz_generated.openapi.go, controllers/scaledobject_controller_test.go, controllers/suite_test.go
=> regenerate adapter openapi & fix linter issues

CHANGELOG.md
=> prepare 2.2 release

.github/ISSUE_TEMPLATE/3_bug_report.yml, RELEASE-PROCESS.MD
=> add 2.2.0 to the bug report GH template

.github/ISSUE_TEMPLATE/1_feature_request.yml, .github/ISSUE_TEMPLATE/2_suggest_scaler.yml, .github/ISSUE_TEMPLATE/3_bug_report.yml
Breaking changes to GitHub's Issue Forms
=> Breaking changes to GitHub's Issue Forms

tests/package-lock.json, tests/package.json
This PR adds the missing dependencies for the Azure Pipelines e2e test.
Fixes #1744
=> fix Azure Pipelines e2e test

tools/build-tools.Dockerfile
Breaking out this bit from #1768 so we can rebuild the build-tools image which should make CI work for that PR.
=> 👷‍♂️ Install the kubebuilder tools in the build image.

CONTRIBUTING.md
End-to-end tests are mandatory for new scalers.
=> chore: End-to-end tests are mandatory for new scalers

README.md
Correct the Community bi-weekly meeting time under community section corresponding to [keda.sh/community](https://keda.sh/community/) docs.
=> Correct Community Meeting Time

RELEASE-PROCESS.MD
Reordering the process in the release process notes.
It makes sense to update Changelog and add new KEDA version to the bug report template at the same time.
=> reorder release process in notes

renovate.json
Use a single PR for all dependency updates
=> chore: Renovate configuration for single PR

renovate.json
This should append a table in the commit message body describing all updates in the commit.
=> Update Renovate to describe updates in the commmit

renovate.json
=> Enable PR controls for Renovate

.devcontainer/Dockerfile, .github/workflows/fossa.yml, .github/workflows/pr-validation.yml, Dockerfile, Dockerfile.adapter, tools/build-tools.Dockerfile
=> bump to golang 1.15.13

.gitignore, pkg/provider/provider.go, tests/cleanup.test.ts, tests/setup.test.ts
=> chore: change Keda -> KEDA

tests/scalers/azure-queue-idle-replicas.test.ts
The ScaledObject targeted wrong AZ queue.
=> Idle Replicas test fix

controllers/scaledobject_controller_test.go
controller test - increasing timeouts to mitigate flaky tests
=> controller test - increasing timeouts

CHANGELOG.md
Somehow we forgot to add this https://github.com/kedacore/keda/pull/1866 change to Changelog 😖
=> add Kafka Version support to Changelog

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
=> Prepare 2.4.0 release

tools/build-tools.Dockerfile
=> build-tools image: bump Golang to 1.16.7

.devcontainer/Dockerfile, .github/workflows/pr-validation.yml, CONTRIBUTING.md
=> bump golangci-lint to 1.42.0

tests/scalers/cron.test.ts
=> Add e2e test for cron scaler

tests/scalers/redis-lists.test.ts, tests/scalers/redis-sentinel-lists.test.ts, tests/scalers/redis-sentinel-streams.test.ts, tests/scalers/redis-streams.test.ts, tests/scalers/solace-helpers.ts
=> e2e: extend deployment timeouts

tests/scalers/redis-cluster-lists.test.ts, tests/scalers/redis-cluster-streams.test.ts, tests/scalers/redis-lists.test.ts, tests/scalers/redis-sentinel-lists.test.ts, tests/scalers/redis-sentinel-streams.test.ts, tests/scalers/redis-streams.test.ts
=> e2e: extending Redis timeouts

RELEASE-PROCESS.MD
Provide emphasize on preparing our Helm chart so that we are certain that it has the latest CRDs & Kubernetes resources.
- ~[ ] Tests have been added~
- ~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
- ~[ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*~
- ~[ ] Changelog has been updated~
=> docs: Provide emphasize on preparing our Helm chart

CHANGELOG.md, pkg/scalers/influxdb_scaler.go
=> Influx: Update client generation to fix issues

CHANGELOG.md
=> Changelog chores

CHANGELOG.md
=> Changelog: fix typo

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
=> Prepare 2.5.0 release

.github/workflows/release-build.yml
=> Use GH Action to extract the tag

.github/workflows/release-build.yml, Makefile
=> Revert GH action change and fix makefile

RELEASE-PROCESS.MD
=> Add note about Snyk for the release process 

.github/stale.yml
Never close Epic issues with our stale bot.
- ~[ ] Tests have been added~
- ~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
- ~[ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*~
- ~[ ] Changelog has been updated~
Closes kedacore/governance#33
=> chore: Never close Epic issues

.golangci.yml
=> Increase golangci timeout to 10m

CHANGELOG.md
Provide formatting for changelog.
=> chore: Provide formatting for changelog

RELEASE-PROCESS.MD
Provide more extensive release document that includes new contributors and GitHub Discussion.
=> chore: Provide more extensive release document

.github/ISSUE_TEMPLATE/3_bug_report.yml
=> chore: Add Kubernetes v1.23 to bug report template

.github/workflows/main-build.yml, .github/workflows/pr-validation.yml, .github/workflows/upgrade-validation-template.yml, CHANGELOG.md
=> Update reusable workloads with missing parameters

.github/workflows/pr-validation.yml
=> Removed upgrade-validation from pr workflow 

RELEASE-PROCESS.MD
Microsoft will update Azure Function Core Tools during release as this is not related to KEDA
=> docs: Microsoft will update Azure Function Core Tools during release

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
=> Prepare v2.6

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md
Provide information related to changelog in our contribution guide
=> docs: Provide guidance on changelog

CHANGELOG.md, tests/scalers/azure-queue-idle-replicas.test.ts, tests/scalers/azure-queue-trigger-auth.test.ts
Related https://github.com/kedacore/keda/issues/2603
=> e2e: Fix failing tests based on the scale to zero bug

.github/workflows/auto-add-issues-to-project.yml
Automatically add new issues to our backlog project on https://github.com/orgs/kedacore/projects/2/views/1.
A big thank you to @chrisreddington for his help on https://www.cloudwithchris.com/blog/automate-adding-gh-issues-projects-beta/!
=> feat: Automatically add new issues to our backlog project

.github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-e2e.yml
Provide e2e test variables for Azure Data Explorer
Relates to https://github.com/kedacore/keda/issues/1488
=> feat: Provide e2e test variables for Azure Data Explorer

tests/scalers/rabbitmq-queue-amqp.test.ts
=> Use new rabbit MQ mode/value parameters in one of the e2e tests

SECURITY.md
Provide update on prevention for security vulnerabilities in security policy:
- Renovate is patching our dependencies
- Snyk has been used for a while to scan published images on GHCR
- WhiteSource Bolt is used to detect vulnerabilities
- Provide overview of GitHub features we use
Relates to https://github.com/kedacore/governance/issues/52
Relates to https://github.com/kedacore/governance/issues/47
=> chore: Provide update on prevention for security vulnerabilities in security policy

CONTRIBUTING.md
=> chore: update changelog guide

CHANGELOG.md
Reshuffle changelog to consolidate ARM
Fixes #
=> chore: Reshuffle changelog

.github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-e2e.yml
Provide e2e variables for Azure Key Vault.
Relates to https://github.com/kedacore/keda/issues/900
Relates to https://github.com/kedacore/keda/pull/2727
=> feat: Provide e2e variables for Azure Key Vault

.devcontainer/Dockerfile, .github/workflows/pr-validation.yml, CONTRIBUTING.md, pkg/scalers/datadog_scaler.go
=> update golangci-lint to 1.45.0

tests/package-lock.json, tests/run-all.sh, tests/scalers/aws-dynamodb.test.ts
the previous attempt didn't work, we need to enable this test once we have AWS Accoutn ready as requested in https://github.com/kedacore/keda/issues/2803
=> Disable AWS DynamoDB e2e tests properly

.github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-e2e.yml, CHANGELOG.md, tests/run-all.sh
Fixes https://github.com/kedacore/keda/issues/2803
=> Enable DynamoDB tests

.github/PULL_REQUEST_TEMPLATE.md
=> revert : Use "Relates to" instead of "Fixes"

BUILD.md
=> Add debugging instructions to BUILD.md

CHANGELOG.md, README.md, RELEASE-PROCESS.MD, ROADMAP.md
Provide information around our roadmap & upcoming release cycles.
Fixes https://github.com/kedacore/governance/issues/48
=> docs: Provide information around our roadmap & upcoming release cycles

.github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-e2e.yml
Provide e2e variables for Azure Service Bus
Relates to https://github.com/kedacore/keda/issues/2731
Relates to https://github.com/kedacore/keda/issues/2732
Relates to #2882
=> feat: Provide e2e variables for Azure Service Bus

README.md
Community standups are at 5 PM (EU time).
Relates to https://github.com/kedacore/keda/discussions/2773
=> docs: Community standup information is available on website

.github/workflows/pr-e2e.yml
=> fix typo in e2e-pr workflow

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Prepare for v2.7 release:
- Introduce v2.7 in changelog
- Add 2.7 in issue template for bugs
=> chore: Prepare for v2.7 release

ROADMAP.md
Provide updated roadmap after v2.7 release
=> chore: Provide updated roadmap after v2.7 release

RELEASE-PROCESS.MD
Add "tweet" step to release process
=> chore: Add "tweet" step to release process

CHANGELOG.md, Dockerfile, Dockerfile.adapter, config/manager/manager.yaml, config/metrics-server/deployment.yaml
=> Don't hardcode UIDs in securityContext

CHANGELOG.md
=> chore: Changelog - add Other section to Unreleased

.github/workflows/pr-e2e.yml
=> chore: add safe folder to git

.github/workflows/pr-e2e.yml
I made an error copy-pasting the task
=> fix: fix typo in e2e workflow

.github/workflows/pr-e2e.yml
After changing one of the triage actions, the condition has changed a bit (from 1 to true)
=> fix: Fix job condition for e2e test after changing the actions

.github/workflows/pr-e2e.yml
=> fix: Add missing exclusions for git folders

tools/build-tools.Dockerfile
=> add git-lfs to build tools image

.github/workflows/pr-e2e.yml
=> fix: Update error in the adding label condition on e2e-PR

CHANGELOG.md, adapter/main.go
Fixes https://github.com/kedacore/keda/issues/2316
=> fix: Refactor adapter startup to ensure proper log initilization

.github/workflows/pr-validation.yml, Makefile
This PR adds the needed changes to report unit tests results to the workflow summary
Fixes #
=> chore: Add test report on CI

.github/PULL_REQUEST_TEMPLATE.md
Add comment for documentation / chart links in PR template
=> chore: Add comment for documentation / chart links in PR template

.devcontainer/Dockerfile, .github/workflows/pr-validation.yml, CHANGELOG.md
This PR fixes the issue using devcontainers on ARM64 arch and also includes a CI to validate it in the future
Fixes https://github.com/kedacore/keda/issues/3084
Relates to #
=> fix: add necessary configuration for devcontainer with ARM arch

.github/workflows/pr-validation.yml
=> chore(deps): update actions/setup-python action to v4

CHANGELOG.md, tests/scalers_go/aws_sqs_queue/aws_sqs_queue_test.go
=> Use `AWS_REGION` environment variable

tests/run-arm-smoke-tests.sh
=> fix arm e2e test.

CREATE-NEW-SCALER.md
Signed-off-by: Yoichi Kawasaki <yokawasa@gmail.com>
I found the function name to change in CREATE-NEW-SCALER was old one. So I fix it
Fixes #
Relates to #
=> Fix function name to change in CREATE-NEW-SCALER.md

.github/workflows/main-build.yml, .github/workflows/pr-e2e-checker.yml, .github/workflows/pr-e2e-creator.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, go.mod, go.sum
Relates to https://github.com/kedacore/keda/pull/3310
Relates to https://github.com/kedacore/keda/pull/3311
Relates to https://github.com/kedacore/keda/pull/3312
Relates to https://github.com/kedacore/keda/pull/3317
Relates to https://github.com/kedacore/keda/pull/3319
Relates to https://github.com/kedacore/keda/pull/3316
=> chore: bump-deps

tests/helper/helper.go
Signed-off-by: aviadlevy <aviadlevy1@gmail.com>
The DeleteKubernetesResources cleanup method now verify that namespace is deleted
Fixes #3322
=> e2e test namespace deletion verify namespace actually deleted

go.mod, go.sum
Fixes https://github.com/kedacore/keda/issues/2543
=> chore: bump github.com/hashicorp/vault/api

tests/run-arm-smoke-tests.sh
=> Fix path in ARM test script.

.fossa.yml, .github/workflows/fossa.yml, README.md
=> chore: update FOSSA key and badge

.github/workflows/fossa.yml
=> fix: remove unsupported parameter from fossa task

pkg/scalers/graphite_scaler.go, pkg/scalers/graphite_scaler_test.go, tests/scalers_go/graphite/graphite_test.go
Fixes #
Relates to https://github.com/kedacore/keda/issues/2800
=> feat: introduce `activationThreshold` for Graphite Scaler

tests/README.md
=> chore: e2e tests Readme

pkg/scalers/postgresql_scaler.go, pkg/scalers/postgresql_scaler_test.go, tests/scalers_go/postgresql/postgresql_test.go
Relates to https://github.com/kedacore/keda/issues/2800
=> feat: Introduce `activationTargetQueryValue` for PostgreSQL Scaler

tests/scalers_go/activemq/activemq_test.go, tests/scalers_go/artemis/artemis_test.go, tests/scalers_go/aws_cloudwatch/aws_cloudwatch_test.go, tests/scalers_go/aws_cloudwatch_expression/aws_cloudwatch_expression_test.go, tests/scalers_go/aws_dynamodb/aws_dynamodb_test.go, tests/scalers_go/aws_kinesis_stream/aws_kinesis_stream_test.go, tests/scalers_go/cassandra/cassandra_test.go, tests/scalers_go/datadog/datadog_test.go, tests/scalers_go/elasticsearch/elasticsearch_test.go, tests/scalers_go/graphite/graphite_test.go, tests/scalers_go/postgresql/postgresql_test.go, tests/scalers_go/stan/stan_test.go
=> chore: e2e tests - use correct format for printing int values

pkg/scalers/mssql_scaler.go, pkg/scalers/mssql_scaler_test.go, tests/scalers_go/mssql/mssql_test.go
Follow up: https://github.com/kedacore/keda/issues/3401
=> feat: Introduce activationTargetValue for MS SQL Scaler

pkg/scalers/huawei_cloudeye_scaler.go, pkg/scalers/huawei_cloudeye_scaler_test.go
Related to https://github.com/kedacore/keda-docs/pull/824
=> feat: Introduce activationThreshold/minMetricValue for Huawei Scaler

pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go, tests/scalers_go/prometheus/prometheus_test.go
=> feat: Introduce activationThreshold for Prometheus Scaler

pkg/scalers/ibmmq_scaler.go, pkg/scalers/ibmmq_scaler_test.go
Related to https://github.com/kedacore/keda-docs/pull/825
=> feat: Introduce activationThreshold/minMetricValue for IBM Scaler

pkg/scalers/kubernetes_workload_scaler.go, pkg/scalers/kubernetes_workload_scaler_test.go, tests/scalers_go/kubernetes_workload/kubernetes_workload_test.go
Related to https://github.com/kedacore/keda-docs/pull/828
Related to https://github.com/kedacore/keda/pull/3380
=> feat: Introduce activationThreshold/minMetricValue for Kubernetes Workload Scaler

pkg/scalers/liiklus_scaler.go, pkg/scalers/liiklus_scaler_test.go, pkg/scalers/openstack_metrics_scaler.go, pkg/scalers/openstack_metrics_scaler_test.go
Related to https://github.com/kedacore/keda-docs/pull/829
Related to https://github.com/kedacore/keda/pull/3380
=> feat: Introduce activationThreshold/minMetricValue for Liiklus and Openstack metrics Scalers

pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_pubsub_scaler_test.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_stackdriver_scaler_test.go, pkg/scalers/gcp_storage_scaler.go, pkg/scalers/gcp_storage_scaler_test.go, tests/scalers_go/gcp_pubsub/gcp_pubsub_test.go, tests/scalers_go/gcp_stackdriver/gcp_stackdriver_test.go, tests/scalers_go/gcp_storage/gcp_storage_test.go
Related to #2800 
Related to kedacore/keda-docs#831
=> Introduce activationThreshold for GCP scalers

pkg/scalers/azure_app_insights_scaler.go, pkg/scalers/azure_app_insights_scaler_test.go, pkg/scalers/azure_blob_scaler.go, pkg/scalers/azure_blob_scaler_test.go, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/azure_monitor_scaler.go, pkg/scalers/azure_monitor_scaler_test.go, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_queue_scaler.go, pkg/scalers/azure_queue_scaler_test.go, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/azure_servicebus_scaler_test.go
=> azure: Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/metrics_api_scaler.go, pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go, pkg/scalers/mssql_scaler.go, pkg/scalers/mysql_scaler.go, pkg/scalers/newrelic_scaler.go, pkg/scalers/newrelic_scaler_test.go, pkg/scalers/openstack_metrics_scaler.go, pkg/scalers/openstack_metrics_scaler_test.go, pkg/scalers/openstack_swift_scaler.go, pkg/scalers/openstack_swift_scaler_test.go
=> m|n|o*: Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/influxdb_scaler.go, pkg/scalers/influxdb_scaler_test.go, tests/scalers/influxdb/influxdb_test.go
=> Introduce activationValue/minMetricValue for InfluxDB scaler

pkg/scalers/nats_jetstream_scaler_test.go
Signed-off-by: Deepak <sah.sslpu@gmail.com>
Add unit tests for NATS JetStream scaler
- N/A A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- N/A A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- N/A Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
Relates: https://github.com/kedacore/keda/issues/2391
=> Add unit tests for NATS JetStream scaler

CHANGELOG.md
=> fix: Broken link in Changelog

.github/ISSUE_TEMPLATE/4_release_tracker.md
Provide issue template to track progress of new KEDA release so that the community has visibility in progress and we can link issues.
=> feat: Provide issue template to track progress of new KEDA release

CHANGELOG.md
List scaler features under new, not improvements in changelog as these are "new" features and not improvements of existing features.
Relates to https://github.com/kedacore/keda/issues/3541
=> docs: List scaler features under new, not improvements in changelog

ROADMAP.md
Update roadmap now that v2.8 is out
Relates to https://github.com/kedacore/keda/issues/3541
=> docs: Update roadmap now that v2.8 is out

BUILD.md, tests/scalers/cron/cron_test.go
=> docs: Improve documentation about how to debug metrics server

BUILD.md
=> chore: Add a note about debbugging metrics server

.github/PULL_REQUEST_TEMPLATE.md
Add scaler governance to PR checklist.
Relates to https://github.com/kedacore/governance/issues/5
=> feat: Add scaler governance to PR checklist

.github/ISSUE_TEMPLATE/3_bug_report.yml, .github/ISSUE_TEMPLATE/4_release_tracker.md, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/3626
=> chore: prepare release v2.8.1

CHANGELOG.md
Streamline changelog
Relates to https://github.com/kedacore/keda/pull/3625
=> chore: Streamline changelog

.github/ISSUE_TEMPLATE/3_bug_report.yml
=> chore: update k8s versions in bug template

.github/workflows/template-trivy-scan.yml
=> fix: Address style issue in trivy template

CHANGELOG.md, pkg/scalers/azure/azure_aad_podidentity.go
=> chore: improve aad-pod-identity errors

BUILD.md
=> docs: How to use devcontainers and a local Kubernetes cluster

Makefile, config/crd/bases/keda.sh_scaledobjects.yaml, tests/helper/helper.go, tests/scalers/aws/aws_cloudwatch/aws_cloudwatch_test.go, tests/scalers/aws/aws_cloudwatch_expression/aws_cloudwatch_expression_test.go, tests/scalers/aws/aws_cloudwatch_pod_identity/aws_cloudwatch_pod_identity_test.go, tests/scalers/aws/aws_dynamodb/aws_dynamodb_test.go, tests/scalers/aws/aws_dynamodb_pod_identity/aws_dynamodb_pod_identity_test.go, tests/scalers/aws/aws_dynamodb_streams/aws_dynamodb_streams_test.go, tests/scalers/aws/aws_dynamodb_streams_pod_identity/aws_dynamodb_streams_pod_identity_test.go, tests/scalers/aws/aws_kinesis_stream/aws_kinesis_stream_test.go, tests/scalers/aws/aws_kinesis_stream_pod_identity/aws_kinesis_stream_pod_identity_test.go, tests/scalers/aws/aws_sqs_queue/aws_sqs_queue_test.go, tests/scalers/aws/aws_sqs_queue_pod_identity/aws_sqs_queue_pod_identity_test.go, tests/scalers/kafka/kafka_test.go, tests/utils/cleanup_test.go, tests/utils/setup_test.go
~[This other PR](https://github.com/kedacore/keda/pull/3684) needs to be merged before continue with this~
Relates to https://github.com/kedacore/keda/issues/3659
=> chore: add aws-pod-identity e2e tests

tests/scalers/prometheus/prometheus_test.go
=> chore: use kedacore hosted images for prom e2e tests

ROADMAP.md
Update roadmap, KEDA v2.9 to ship in December.
=> feat: Update roadmap, KEDA v2.9 to ship in December

.github/workflows/template-trivy-scan.yml
=> feat: add trivy-config support

.devcontainer/Dockerfile, tools/build-tools.Dockerfile
=> build tools image: install `protoc` & bump protoc to v21.9

.github/workflows/template-smoke-tests.yml
Currently, [there is an issue](https://github.com/helm/kind-action/issues/70) with kind action in main branch, so this PR set the version to v1.4.0
=> fix: use fixed kind version

tests/run-all.sh, tests/run-smoke-tests.sh, tests/scalers/mysql/mysql_test.go
To improve the stability of the e2e test, this PR adds a 3rd try for failing tests.
=> feat: Add a 3rd try for e2e test executions

CHANGELOG.md, pkg/util/normalize_string.go
=> chore: improve string normalization for metric names

.github/workflows/pr-e2e.yml
=> chore: add GCP_RUN_IDENTITY_TESTS in e2e pr

.github/workflows/pr-e2e.yml, go.mod, go.sum, vendor/github.com/Azure/azure-kusto-go/kusto/data/errors/errors.go, vendor/github.com/Azure/azure-kusto-go/kusto/internal/version/version.go, vendor/github.com/Azure/azure-kusto-go/kusto/query_builder.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/gocql/gocql/AUTHORS, vendor/github.com/gocql/gocql/CHANGELOG.md, vendor/github.com/gocql/gocql/README.md, vendor/github.com/gocql/gocql/conn.go, vendor/github.com/gocql/gocql/connectionpool.go, vendor/github.com/gocql/gocql/debug_off.go, vendor/github.com/gocql/gocql/debug_on.go, vendor/github.com/gocql/gocql/doc.go, vendor/github.com/gocql/gocql/fuzz.go, vendor/github.com/gocql/gocql/host_source_gen.go, vendor/github.com/gocql/gocql/marshal.go, vendor/github.com/gocql/gocql/policies.go, vendor/github.com/gocql/gocql/session.go, vendor/modules.txt
=> chore: bump deps

CHANGELOG.md
Provide off-the-shelf dashboard.
Relates to #3911
=> docs(changelog): Provide off-the-shelf dashboard

pkg/scalers/artemis_scaler.go, pkg/scalers/openstack/keystone_authentication.go
=> fix: Add some missing error checks

pkg/scalers/activemq_scaler.go
=> fix (activemq): use html/template instead of text/template to avoid injections

pkg/metricsservice/client.go, pkg/scalers/aws_cloudwatch_scaler.go, pkg/scalers/azure_app_insights_scaler.go, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/couchdb_scaler.go, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/etcd_scaler.go, pkg/scalers/gcp_stackdriver_client.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/kafka_scram_client.go, pkg/scalers/kubernetes_workload_scaler.go, pkg/scalers/loki_scaler.go, pkg/scalers/mongo_scaler.go, pkg/scalers/mssql_scaler.go, pkg/scalers/mysql_scaler.go, pkg/scalers/newrelic_scaler.go, pkg/scalers/predictkube_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scaling/scale_handler.go
This PR solves some cases where we use assigned values even we have an error
=> fix: apply rule trailofbits.go.questionable-assignment.questionable-assignment

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md, RELEASE-PROCESS.md
Fixes #
Relates to https://github.com/kedacore/keda/issues/4018
=> chore: prepare release

pkg/scalers/couchdb_scaler.go, pkg/scalers/mongo_scaler.go, pkg/scalers/postgresql_scaler.go, pkg/util/normalize_string.go
=> fix: update connections strings to address db-connection-string rule

.github/ISSUE_TEMPLATE/1_feature_request.yml
Add "interested to contribute" to issue template for feature request
=> chore: Add "interested to contribute" to issue template for feature request

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml
Relates to https://github.com/kedacore/keda/pull/4030
=> chore: add needed variables to workflows

Makefile
=> fix: update make run target file

CHANGELOG.md, pkg/scaling/cache/scalers_cache.go
Relates to https://github.com/kedacore/keda/issues/4092
=> cherry-pick: fix: prevent panic while refreshing a scaler cache (#4093)

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
=> Prepare release v2.9.2

pkg/fallback/fallback.go, pkg/fallback/fallback_test.go, pkg/provider/provider.go, pkg/scaling/resolver/scale_resolvers.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_test.go
=> chore: logging cleanup

CHANGELOG.md, pkg/scalers/azure/azure_azidentity_chain.go, pkg/scalers/azure_servicebus_scaler.go
Fixes https://github.com/kedacore/keda/issues/4123
=> fix: Register only the wanted Azure credential in the chain

pkg/scalers/azure_eventhub_scaler.go
Relates to https://github.com/kedacore/keda/issues/4032
=> fix: Add missing error check

.github/workflows/auto-add-issues-to-project.yml
https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/#%F0%9F%A4%96-graphql-api-improvements
This is a dirty change, needs to be tested.
=> fix: Use GA API for GitHub Projects

pkg/scalers/gcp_common.go, pkg/scalers/gcp_pubsub_scaler_test.go, pkg/scalers/gcp_stackdriver_scaler_test.go, pkg/scalers/gcp_storage_scaler_test.go
This code is not used anywhere, doesn't make sense to keep it for nothing
=> chore(gcp): remove unused code

CHANGELOG.md
=> chore: prepare v2.9.3

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
=> chore: update main changelog with v2.9.3

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go
Hi team,
This PR will improve the error logging in Azure Pipelines Scaler. Could you help to review it :pray: ?
Fixes #3996
=> Improve error logging for  in Azure Pipelines Scaler

controllers/keda/scaledjob_controller.go, pkg/metricsservice/client.go, pkg/prommetrics/adapter/adapter_prommetrics.go, pkg/scalers/gcp_stackdriver_client.go, pkg/scalers/redis_scaler.go, pkg/util/http.go
=> chore: review last semgrep vulnerabilities

tests/internals/custom_hpa_name/custom_hpa_name_test.go, tests/scalers/cpu/cpu_test.go, tests/scalers/graphite/graphite_test.go, tests/scalers/memory/memory_test.go
Relates to https://github.com/kubernetes/k8s.io/issues/4780
=> chore: use new k8s registry

pkg/util/http.go
Probably during a rebase, I introduced duplicated code. This PR removes the duplicated code
=> chore: remove duplicated code

CHANGELOG.md
=> chore: add missing link to v2.9.3

ROADMAP.md
Release will be delayed some days. This PR updates the roadmap to reflect the correct dates
=> Update Roadmap to reflect new dates

pkg/util/certificates.go
I have noticed that sometimes an error is raised during KEDA operator startup:
```
Failed to append "..data" to certPool	{"error": "read /custom/ca/..data: is a directory"}
```
After investigating the error, I found that sometimes (IDK when exactly) k8s add some extra hidden folders with some symlinks. This happens on my local cluster and I have seen it sometimes in testing clusters but I don't know exactly when.
This PR just adds a skip for folders which start with `..` and also improve a fix the logic to print each error only once
=> chore: Skip hidden folders from custom-ca registration

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/4018
=> chore: Prepare v2.10 (#4350

pkg/util/welcome.go
=> chore: update supported versions in the welcome message

.github/ISSUE_TEMPLATE/4_release_tracker.md
=> chore: Add a release step to ensure that supported versions are updated

CHANGELOG.md, go.mod, go.sum, vendor/modules.txt
Need to drop this dependency to fix licence issues.
Fixes https://github.com/kedacore/keda/issues/4364
=> Drop a transitive dependency on bou.ke/monkey

.github/workflows/fossa.yml
In order to detect issue problems before merging PRs, this PR enables FOSSA analysis on every PR
=> chore: Execute FOSSA on PRs

CHANGELOG.md
=> fix link in the changelog

CREATE-NEW-SCALER.md
Hi team,
This MR fixes the broken rendering in markdown file to create a new scaler. Let me know if I need to update CHANGELOG file if it is for Document changes
=> Fix: broken rendering in create new scaler markdown file

Makefile
=> fix: add missing labels for aad wi

config/e2e/patch_operator.yml
=> fix smoke tests

.github/ISSUE_TEMPLATE/3_bug_report.yml
Relates to https://github.com/kedacore/keda/issues/4374
=> chore: Add v2.10.1 to the bug template (#4450

tests/run-all.go
=> fix(e2e): uninstall KEDA properly

.github/workflows/pr-e2e.yml, Makefile
=> chore: use new cluster names

tests/README.md
=> chore: add `sequential` section to e2e tests Readme

tests/run-all.go
Fixing wording and trying to hack numbers of attempts to not get masked by GH.
=> chore: e2e log messages

CHANGELOG.md, pkg/scalers/pulsar_scaler.go
=> Pulsar: improve error messages

CHANGELOG.md
=> chore: add v2.10.1 to Changelog

controllers/keda/scaledobject_controller.go
=> style: correct the sentence

controllers/keda/scaledobject_controller.go
Fix typo (UnkownState => UnknownState)
Fixes #
Relates to #
=> Fix typo (`UnkownState` => `UnknownState`)

pkg/scalers/mongo_scaler_test.go
Fix typo (localhost => localhost)
Fixes #
Relates to #
=> Fix typo (localshot => localhost)

pkg/scaling/scale_handler.go
=> chore: remove obsolete comment

config/grafana/keda-dashboard.json
This provides some work on the dashboard and 
* fixes #4485 
* fixes #4599 
* fixes #4485 
* fixes #4599 
Relates to #
=> feat: fix metrics not showing and improve graphs

ROADMAP.md
https://github.com/kedacore/keda/issues/4710
=> update roadmap with 2.14

pkg/scaling/executor/scale_scaledobjects.go
Fix typo (repliacs -> replicas)
Fixes #
Relates to #
=> Fix typo (repliacs -> replicas)

.github/ISSUE_TEMPLATE/4_release_tracker.md
Typo in release tracker issue template
=> fix(github): Typo in release tracker issue template

CHANGELOG.md, pkg/scalers/prometheus_scaler.go
Relates to https://github.com/kedacore/keda/issues/4743
=> chore: Cherry-pick fixes for KEDA v2.11.1 (#4744)

CHANGELOG.md
KEDA v2.11.1 changelog
Relates to https://github.com/kedacore/keda/issues/4743
=> chore: KEDA v2.11.1 changelog

apis/keda/v1alpha1/scaledobject_types.go, config/crd/bases/keda.sh_scaledobjects.yaml
fix typo in comment : the a reference -> the reference
Fixes N/A
Relates to N/A
=> Fix typo in scaledobject_types comment

tests/README.md
Signed-off-by: Adarsh-verma-14 <t_adarsh.verma@india.nec.com>
fix path for azure_queue_test.go
=> fix path for azure_queue_test.go

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/4795
=> chore: Update changelog and bug template with v2.11.2

.github/workflows/template-arm64-smoke-tests.yml, .github/workflows/template-versions-smoke-tests.yml, pkg/util/welcome.go
Relates to https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md
=> chore: Adjust supported versions on CI and welcome message

controllers/keda/hpa.go
=> fix: typo in log message, keep code style consistency

.devcontainer/Dockerfile, .github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/template-main-e2e-test.yml, Dockerfile, Dockerfile.adapter, Dockerfile.webhooks
=> bump Golang to 1.20.8

pkg/scalers/azure/azure_azidentity_chain.go, pkg/scalers/azure/azure_data_explorer.go, pkg/scalers/azure/azure_managed_prometheus_http_round_tripper.go, pkg/scalers/azure/azure_managed_prometheus_http_round_tripper_test.go, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/prometheus_scaler.go
This PR adds some logs to the azure chained provider to help on cases as https://github.com/kedacore/keda/issues/5006
Relates to https://github.com/kedacore/keda/issues/5006
=> chore: Improve azure podIdentity logs

ROADMAP.md
Delay KEDA v2.12 until Sept 28th to ensure everything gets in
Relates to https://github.com/kedacore/keda/issues/4994
=> chore: Delay KEDA v2.12 until Sept 28th

ROADMAP.md
Add v2.15 to roadmap
Relates to https://github.com/kedacore/keda/issues/4994
=> docs: Add v2.15 to roadmap

ROADMAP.md
=> fix: update roadmap year

CHANGELOG.md, hack/validate-changelog.sh
=> fix: Changelog script allows TODO entries

.github/workflows/fossa.yml, .github/workflows/pr-e2e-checker.yml, .github/workflows/pr-e2e-creator.yml, .github/workflows/pr-validation.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/static-analysis-semgrep.yml
=> chore: Enable concuncurrency in PR workflows to skip unnecessary executions

README.md, SECURITY.md
There was an obsolete information. Adding link to KEDA support page to Readme for visibility.
=> chore: link the proper Support policy

config/crd/kustomization.yaml, config/e2e/kustomization.yaml
Update deprecated patchesJson6902 to patches in yaml
=> chore: Update deprecated patchesJson6902 to patches in yaml 

.github/ISSUE_TEMPLATE/4_release_tracker.md
=> Release Tracker template - add link to GH bug report template

.github/ISSUE_TEMPLATE/3_bug_report.yml
=> Bug report template - prepare 2.12.1

CHANGELOG.md
=> Changelog - prepare 2.12.1

RELEASE-PROCESS.md
=> Update Release Process doc with info about Snyk image pruning.

tests/sequential/prometheus_metrics/prometheus_metrics_test.go
I missed this file during my previous PR
Relates to https://github.com/kedacore/keda/pull/5226
=> chore: Add missing changes on prometheus metrics e2e test case

.github/workflows/template-smoke-tests.yml
=> fix: Main pipeline generates artifacts incuding machine type in the name

pkg/util/certificates.go
Relates to https://github.com/kedacore/keda/issues/5248
=> getRootCAs() - add mutex for concurrency safety

CHANGELOG.md, config/rbac/role.yaml, controllers/keda/scaledobject_controller.go, pkg/certificates/certificate_manager.go
Fixes https://github.com/kedacore/keda/issues/5261
=> chore: Revisit RBAC permissions to remove not needed permissions

tests/helper/helper.go, tests/secret-providers/hashicorp_vault/hashicorp_vault_test.go
=> feat: Increase e2e coverage to hashicorp-secret-provider by testing kubernetes auth

tests/scalers/azure/azure_managed_prometheus/helper/helper.go, tests/scalers/loki/loki_test.go, tests/scalers/prometheus/prometheus_test.go
=> chore: use `ghcr.io/kedacore/tests-hey` image in e2e tests for HTTP load testing

config/samples/keda_v1alpha1_scaledjob.yaml, config/samples/keda_v1alpha1_scaledobject.yaml
=> fix typo about cr yaml sample

.github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/template-main-e2e-test.yml, Dockerfile, Dockerfile.adapter, Dockerfile.webhooks
=> chore: bump Go to 1.21.6

.github/workflows/pr-welcome.yml
PR Bot has malformed workflow manifest because I did a sloppy change.
=> fix: PR Bot has malformed workflow manifest

pkg/scalers/azure_pipelines_scaler.go
=> chore: Add a comment for az pipelines magic string

.devcontainer/Dockerfile, .github/workflows/pr-validation.yml, CONTRIBUTING.md
=> chore: bump golangci-lint to 1.55.2

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, CHANGELOG.md
Edit the e2e test YAML file before merging https://github.com/kedacore/keda/pull/5436 so that it can be tested.
Relates to # https://github.com/kedacore/keda/pull/5436
https://github.com/kedacore/keda/issues/5375
=> Edit e2e test YAML before merging #5436

CHANGELOG.md, pkg/scaling/scale_handler.go
=> fix:  reports errors during upstream requests

ROADMAP.md
We're delaying the release a week as all required items are not in.
Relates to https://github.com/kedacore/keda/issues/5671
=> chore: Delay v2.14 release to next week

ROADMAP.md
=> Prepare roadmap for v2.15

pkg/scalers/artemis_scaler.go, pkg/scalers/artemis_scaler_test.go
Refactor artemis scaler config reading with a better way
=> Refactor Artemis scaler config

ROADMAP.md
As per disussion from July 7 2024: https://docs.google.com/document/d/1zdwD6j86GxcCe5S5ay9suCO77WPrEDnKSfuaI24EwM4/edit
=> Update estimated release dates

.github/workflows/static-analysis-semgrep.yml
=> fix: Exclude test files from semgrep scan

.github/workflows/static-analysis-semgrep.yml
=> fix: use AMD machines again for semgrep workflow

.github/workflows/pr-e2e.yml
=> chore: Use CNCF runner to execute PR e2e tests

.github/workflows/pr-e2e.yml
There are some connection issues with the cluster and we are still working on them, but in the meantime I want to unlock the e2e tests
=> fix: Revert equinix change

tests/scalers/azure/azure_pipelines_aad_wi/azure_pipelines_aad_wi_test.go
=> chore: Disable temporally AzPipeline WI e2e

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/6049
=> chore: Prepare v2.15.1

controllers/keda/scaledjob_controller.go, controllers/keda/scaledobject_controller.go
=> fix: fix slice init length

.github/workflows/template-smoke-tests.yml
=> fix: Install wget for smoke tests

.github/workflows/main-build.yml, .github/workflows/release-build.yml
=> chore: Use ARM to build multi-arch images

pkg/scalers/cpu_memory_scaler.go, pkg/scalers/kubernetes_workload_scaler.go
Remove unnecessary validation
Relates to #6229
Relates to #6226
=> Remove unnecessary validate in kubernetes workload and cpu mem

pkg/scalers/predictkube_scaler.go
Refactor predictkube scaler config
Fixes #
Relates to #5797
=> Refactor predictkube scaler config

pkg/scalers/cassandra_scaler.go, pkg/scalers/cassandra_scaler_test.go
=> Refactor Cassandra scaler

pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go
Fixes #
Relates to https://github.com/kedacore/keda/issues/5797 https://github.com/kedacore/keda/pull/6180#pullrequestreview-2381518356
=> Refactor rabbitmq scaler config

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md, ROADMAP.md, pkg/util/welcome.go
Prepare v2.16
Fixes #
Relates to #  https://github.com/kedacore/keda/issues/6260
=> chore: Prepare v2.16

pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_scaler_test.go
Refactor AWS sqs queue scaler configuration
Fixes #
Relates to #5797
=> refactor aws sqs queue scaler configuration

.github/workflows/main-build.yml, .github/workflows/template-smoke-tests.yml, .github/workflows/template-trivy-scan.yml
=> fix: use right token permissions

.github/workflows/template-versions-smoke-tests.yml
=> fix: Add missing comma in matrix generator

.github/workflows/pr-validation.yml, .pre-commit-config.yaml, Makefile, apis/keda/v1alpha1/scaledobject_webhook.go
=> chore: update golangci-lint setup and Makefile integration

tests/scalers/azure/azure_pipelines/azure_pipelines_test.go, tests/scalers/azure/azure_pipelines_aad_wi/azure_pipelines_aad_wi_test.go, tests/scalers/azure/azure_pipelines_adv/azure_pipelines_adv_test.go
=> chore: Improve azure pipelines e2e error messages

ROADMAP.md
As discussed on the KEDA community call today.
Relates: https://github.com/kedacore/keda/issues/6502
=> update release date for v2.17

pkg/scalers/predictkube_scaler.go, pkg/scalers/predictkube_scaler_test.go
=> fix: Remove http://demo.robustperception.io/ dependency

ROADMAP.md
There are still issues to tackle: https://github.com/kedacore/keda/issues/6502
=> push 2.17 release date

pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/azure_servicebus_scaler_test.go
Refactor Azure ServiceBus Scaler
Relates to # https://github.com/kedacore/keda/issues/5797
=> Refactor Azure ServiceBus Scaler

.devcontainer/Dockerfile, .github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/template-main-e2e-test.yml, Dockerfile, Dockerfile.adapter, Dockerfile.webhooks, go.mod
=> chore: update Go version to v1.23.7

CHANGELOG.md, ROADMAP.md
Relates to https://github.com/kedacore/keda/issues/6502
=> Clean changelog

.github/workflows/static-analysis-codeql.yml, .github/workflows/static-analysis-semgrep.yml, .github/workflows/template-trivy-scan.yml
=> fix workflows

BUILD.md, CHANGELOG.md, cmd/adapter/main.go, go.mod, go.sum, pkg/metricsservice/client.go, pkg/metricsservice/server.go, pkg/metricsservice/utils/tls.go, vendor/github.com/fsnotify/fsnotify/.cirrus.yml, vendor/github.com/fsnotify/fsnotify/CHANGELOG.md, vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md, vendor/github.com/fsnotify/fsnotify/README.md, vendor/github.com/fsnotify/fsnotify/backend_fen.go, vendor/github.com/fsnotify/fsnotify/backend_inotify.go, vendor/github.com/fsnotify/fsnotify/backend_kqueue.go, vendor/github.com/fsnotify/fsnotify/backend_other.go, vendor/github.com/fsnotify/fsnotify/backend_windows.go, vendor/github.com/fsnotify/fsnotify/fsnotify.go, vendor/github.com/fsnotify/fsnotify/internal/darwin.go, vendor/github.com/fsnotify/fsnotify/internal/freebsd.go, vendor/github.com/fsnotify/fsnotify/internal/unix.go, vendor/github.com/fsnotify/fsnotify/internal/windows.go, vendor/github.com/fsnotify/fsnotify/shared.go, vendor/github.com/fsnotify/fsnotify/staticcheck.conf, vendor/modules.txt
=> feat: grpc mTLS certificates are hot reloaded

CHANGELOG.md
=> Update changelog according to v2.17.1

tests/utils/setup_test.go
Fixes #6784
Relates to #
```sh
➜  keda git:(fix/missing-test-function) ✗ go test -v -tags e2e tests/utils/setup_test.go -run TestVerifyPodsIdentity
=== RUN   TestVerifyPodsIdentity
--- PASS: TestVerifyPodsIdentity (0.00s)
PASS
ok      command-line-arguments  0.037s
```
=> fix missing test function

CHANGELOG.md, controllers/keda/scaledobject_controller.go
Fixes https://github.com/kedacore/keda/issues/6802
=> Improve Events emitted from ScaledObject controller

.github/ISSUE_TEMPLATE/3_bug_report.yml, BUILD.md, CHANGELOG.md, cmd/adapter/main.go, go.mod, go.sum, pkg/metricsservice/client.go, pkg/metricsservice/server.go, pkg/metricsservice/utils/tls.go, pkg/scalers/temporal.go, vendor/github.com/fsnotify/fsnotify/.cirrus.yml, vendor/github.com/fsnotify/fsnotify/CHANGELOG.md, vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md, vendor/github.com/fsnotify/fsnotify/README.md, vendor/github.com/fsnotify/fsnotify/backend_fen.go, vendor/github.com/fsnotify/fsnotify/backend_inotify.go, vendor/github.com/fsnotify/fsnotify/backend_kqueue.go, vendor/github.com/fsnotify/fsnotify/backend_other.go, vendor/github.com/fsnotify/fsnotify/backend_windows.go, vendor/github.com/fsnotify/fsnotify/fsnotify.go, vendor/github.com/fsnotify/fsnotify/internal/darwin.go, vendor/github.com/fsnotify/fsnotify/internal/freebsd.go, vendor/github.com/fsnotify/fsnotify/internal/unix.go, vendor/github.com/fsnotify/fsnotify/internal/windows.go, vendor/github.com/fsnotify/fsnotify/shared.go, vendor/github.com/fsnotify/fsnotify/staticcheck.conf, vendor/modules.txt
Releasing KEDA v2.17.2 patch with cherry-picked fixes from https://github.com/kedacore/keda/issues/6822
see also: https://github.com/kedacore/keda/issues/6822
=> Prepare release v2.17.2

pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_log_analytics_scaler_test.go
Refactor Azure Log Analytics Scaler
Fixes #
Relates to # https://github.com/kedacore/keda/issues/5797
=> Refactor Azure Log Analytics Scaler

pkg/scalers/github_runner_scaler.go, pkg/scalers/github_runner_scaler_test.go
=> refactor github runner scaler

pkg/scalers/openstack_metrics_scaler.go, pkg/scalers/openstack_metrics_scaler_test.go
=> Refactor openstack metric scaler

pkg/scalers/gcp_cloud_tasks_scaler.go, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_stackdriver_scaler.go, schema/generate_scaler_schema.go, schema/generated/scalers-metadata-schema.json, schema/generated/scalers-metadata-schema.yaml
Fixes https://github.com/kedacore/keda/issues/6255
=> chore: Add deprecation message for GCP scalers

ROADMAP.md
Fixes https://github.com/kedacore/governance/issues/122
=> update release schedule and estimations

.github/ISSUE_TEMPLATE/4_release_tracker.md
Hopefully last iteration on the file for now 
Relates: https://github.com/kedacore/keda/pull/7159
=> chore: release tracker update 3
