Makefile
Use `-mod=readonly` with `go list` so that even if someone builds with
vendored deps, the build will still work.
=> Make code generation more robust

CHANGELOG.md, go.mod, go.sum
=> Fix CVE-2022-21221 in `github.com/valyala/fasthttp`

.devcontainer/Dockerfile, CHANGELOG.md, Dockerfile, Dockerfile.adapter, tools/build-tools.Dockerfile
=> Bump Go to 1.17.9

.github/workflows/fossa.yml, .github/workflows/pr-e2e.yml, tools/build-tools.Dockerfile
Github Hub hasn't been updated for 2 years and it's failing right now. This PR switch from github hub to github-cli for e2e test on PRs (adding the tool also to the build-tools image).
*This PR solves another problem related with FOSSA
=> fix: use gh-cli instead of hub

CHANGELOG.md, pkg/scaling/executor/scale_scaledobjects.go, tests/scalers/azure-queue-pause.test.ts
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
Fixes the issue of a ScaledObject scaling up/down based on the incoming events/messages when it's paused.
Fixes #3009
=> Avoid scaling triggered by events/messages when ScaledObject is paused

Makefile
The KEDA images that are hosted on the Microsoft Container Registry (mcr.microsoft.com) are separately built with a Microsoft-internal pipeline that uses Microsoft's security-compliant build infrastructure. We recently found about #2457 that updated the Makefile target for release-build from `publish` to `publish-multiarch`.
Our internal pipeline used to execute `make docker-build` which would add the image local repository and then call `docker save` on them to export them into tar files. At present, the Makefile does not allow this for multi-arch images. Hence, this PR is created to enable saving of docker images targeting different platforms.
=> Enable saving of KEDA container images locally

.github/workflows/pr-e2e-pr-validation.yml, .github/workflows/pr-e2e.yml, CHANGELOG.md
This PR introduces 2 big changes to improve the proces:
- All PRs will be blocked till e2e tests pass or till the label `ok-to-merge` is manually added
- Every member of the team @kedacore/keda-e2e-test-executors will be able to trigger the e2e tests
Fixes https://github.com/kedacore/keda/issues/3004
=> feat: improve e2e on PR process

BUILD.md, CHANGELOG.md, config/manager/manager.yaml
Before:
```
1.6520847646863375e+09    INFO    setup    KEDA Version: 2.7.0
1.652084764686349e+09    INFO    setup    Git Commit: 5f8af5cd90805d8b9c5964e1619a8b2bdcec6cfd
1.6520847646863651e+09    INFO    setup    Go Version: go1.17.3
1.6520847646863775e+09    INFO    setup    Go OS/Arch: linux/amd64 
```
After:
```
2022-05-24T12:07:40Z     INFO    setup    KEDA Version: 2.7.0
2022-05-24T12:07:40Z     INFO    setup    Git Commit: 5f8af5cd90805d8b9c5964e1619a8b2bdcec6cfd
2022-05-24T12:07:40Z     INFO    setup    Go Version: go1.17.3
2022-05-24T12:07:40Z     INFO    setup    Go OS/Arch: linux/amd64 
```
Fixes #3066
=> use more readable timestamps in KEDA operator logs

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go, tests/scalers/selenium-grid.test.ts
1. Fixed the implementation of MaxSessions to now give an accurate count of nodes to scale up or down.
2. Implemented an optional parameter `sessionBrowserName` to allow users to specify a different name for their browser in the active sessions list. In this case this is the behavior of Edge where in the session queue it is called "MicrosoftEdge" and as an active session it is called "msedge".
Fixes #2709 
Fixes #3061 
Docs PR: https://github.com/kedacore/keda-docs/pull/764
=> Implementation of sessionBrowserName and a fix for maxSessions (#2709 and #3061

CHANGELOG.md, pkg/scalers/external_scaler.go, pkg/scaling/cache/scalers_cache.go, pkg/scaling/cache/scalers_cache_test.go, tests/scalers/external-scaler.sj.test.ts, tests/scalers/external-scaler.so.test.ts, tests/scalers/helpers.ts, tests/scalers/mongodb.test.ts
After introducing the unique metric names using the prefix and the solution for external scaler, it fails in case of ScaledJobs because we use `queueLength` as a metric name in case of ScaledJob (ignoring the given name from the external scaler) and this metric doesn't have the prefix. 
This PR modifies the behaviour to use the metric spec given from GetMetricSpec instead of the hardcoded value, Using this approach all the code in the scaler that work for ScaledObject work for ScaledJob because now they follow the same behavior (from scaler internal pov).
I have added also an e2e with ScaledJob and external scaler to ensure the behaviour in the future and other small improvements
Fixes # https://github.com/kedacore/keda/issues/3032
=> fix: use metricName from GetMetricsSpec in ScaledJobs instead of `queueLength`

tools/build-tools.Dockerfile
After merging [3075](https://github.com/kedacore/keda/pull/3075), the main workflow is broken due to missing environment variables needed to `make test` in tools image. This PR adds them and also bumps Ubuntu version.
=> fix(build-tools): bump image base version and add missing envs

.github/workflows/build-tools.yml, .github/workflows/fossa.yml, .github/workflows/main-build.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, CHANGELOG.md, Makefile, tools/build-tools.Dockerfile
Signed-off-by: Xoán Mallón <xoanmallon.moure@docplanner.com>
Initial implementation of changes to add support for ARM64 in build-tools Dockerfile
Fixes #
Relates to #3092
=> add support for ARM64 in build-tools Dockerfile

CHANGELOG.md, pkg/scaling/resolver/scale_resolvers.go
=> chore: improve error message in getting ServiceAccount for PodIdentityProviderAwsEKS

.github/workflows/pr-e2e.yml
This bothers me more than it should for no particular reason.
Fixes #
Relates to #
=> Fix typo in e2e test comment.

.github/workflows/main-build.yml, .github/workflows/release-build.yml
We now have tags available in the cosign-installer, which allows us to pin the latest release via `v1`.
=> Pin cosign-installer to `v1`

.github/workflows/main-build.yml, .github/workflows/release-build.yml
- use v2 tag and install always the latest cosign
I saw the pipeline is using keyless and the version below `1.8.0` will not work anymore if use the keyless approach and the public sigstore services. Need to upgrade to `>1.8.0`
using the action with no parameter it always gets the latest available
Fixes #
Relates to #
=> use v2 tag and install always the latest cosign

CHANGELOG.md, pkg/scalers/activemq_scaler.go, pkg/scalers/activemq_scaler_test.go, tests/scalers/activemq.test.ts
Fixes https://github.com/kedacore/keda/issues/3188
=> fix (ActiveMQ): KEDA doesn't respect restAPITemplate

CHANGELOG.md, pkg/scalers/external_scaler.go, pkg/scalers/external_scaler_test.go
Signed-off-by: champly <champly@outlook.com>
- Reduce gRPC connections and `scalerAddress` multiplexing connections with the same address.
- Fix `WaitGroup is reused before previous Wait has returned` panic error.
Fix: #3193
=> reduce gRPC connection create

tests/README.md, tests/helper/helper.go, tests/scalers_go/aws_cloudwatch/aws_cloudwatch_test.go, tests/scalers_go/aws_cloudwatch_expression/aws_cloudwatch_expression_test.go, tests/scalers_go/aws_dynamodb/aws_dynamodb_test.go, tests/scalers_go/aws_dynamodb_streams/aws_dynamodb_streams_test.go, tests/scalers_go/aws_kinesis_stream/aws_kinesis_stream_test.go, tests/scalers_go/aws_sqs_queue/aws_sqs_queue_test.go, tests/scalers_go/azure_keyvault_queue/azure_keyvault_queue_test.go, tests/scalers_go/azure_queue/azure_queue_test.go, tests/scalers_go/azure_queue_trigger_auth/azure_queue_trigger_auth_test.go, tests/scalers_go/azure_service_bus_queue/azure_service_bus_queue_test.go, tests/scalers_go/azure_service_bus_topic/azure_service_bus_topic_test.go, tests/scalers_go/azure_workload_identity/azure_workload_identity_test.go, tests/scalers_go/azure_workload_identity_user_assigned/azure_workload_identity_user_assigned_test.go, tests/scalers_go/cpu/cpu_test.go, tests/scalers_go/cron/cron_test.go, tests/scalers_go/custom_hpa_name/custom_hpa_name_test.go, tests/scalers_go/memory/memory_test.go
Added a variable for template name in /tests/helper/helpers.go to clarify any erroneous template file developer is applying.
Fixes #3192
=> Template variable for e2e log

CHANGELOG.md, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_stackdriver_scaler_test.go, pkg/scalers/stackdriver_client.go, tests/scalers/gcp-pubsub.test.ts, tests/scalers/gcp-stackdriver.test.ts, tests/scalers/gcp-storage.test.ts
Fixes #3008
Docs: https://github.com/kedacore/keda-docs/pull/776
=> Add GCP stackdriver aggregation parameters

.github/workflows/main-build.yml, .github/workflows/pr-validation.yml, SECURITY.md
This PR enables [Trivy](https://aquasecurity.github.io/trivy/v0.29.2/) as an analyzer to check the code and the build images.
- On every PR Trivy will be executed checking the code and exposing the results as a table, in case of detected vulnerabilities, the CI will fail. 
- On every push to `main`, after the image generation, both images are analyzed for each arch to detect vulnerabilities and the results will be pushed to GitHub as security alerts
Relates to https://github.com/kedacore/keda/issues/1040
=> feat: add trivy scanner for code and images

.github/stale.yml
Add `enhancement` to label for stale bot to ignore.
I've thought of adding `bug` as well but didn't proceed given we want to auto-close bugs where reporters are not getting rid of the stale poke given it might not be relevant anymore.
=> chore: Add `enhancement` to label for stale bot to ignore

pkg/scalers/artemis_scaler.go, tests/helper/helper.go, tests/scalers_go/artemis/artemis_test.go
Note: Before merging this, we need to merge [this other PR](https://github.com/kedacore/keda/pull/3339) and rebase this
Fixes https://github.com/kedacore/keda/issues/3225
Related to https://github.com/kedacore/keda-docs/pull/807
=> feat: Introduce activationThreshold/minMetricValue for Artemis Scaler

tools/build-tools.Dockerfile
Sadly, az-cli doesn't support ARM64 if we use deb package, so this PR changes it to install az-cli by python3 pip
=> chore: install az-cli using pip in build-tools

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
=> Kafka Scaler: check `lagThreshold` is a positive number

.github/workflows/fossa.yml
FOSSA pushes the analysis status to the repository using a different check:
Using fossa test it's not necessary and avoid the requirement of having a secret
=> chore: remove fossa test 

go.mod, go.sum
With this dep bump, we solved the FOSSA issues (these versions have license) and also we can remove the replace that we introduce to address a vulnerability with github.com/valyala/fasthttp
Relates to #https://github.com/kedacore/governance/issues/61
=> chore: bump predictkube to address issues

CHANGELOG.md, apis/keda/v1alpha1/scaledjob_types.go, config/crd/bases/keda.sh_scaledjobs.yaml, controllers/keda/scaledjob_controller.go
Signed-off-by: Jonas Bentz <jonas.bentz@sap.com>
This PR allows to configure the kubernetes propagation policy during job scaled roll out. 
In some usecases (see Issue https://github.com/kedacore/keda/issues/2910) its required to use foreground propagation instead of background propagation during rollout. 
Fixes #2910
Relates to # https://github.com/kedacore/keda-docs/pull/804
=> make propagationPolicy configurable during job rollout

tests/scalers_go/activemq/activemq_test.go, tests/scalers_go/cassandra/cassandra_test.go
=> chore: e2e - extend timeout for cassandra & activemq tests

pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go, tests/scalers_go/mongodb/mongodb_test.go
Related to https://github.com/kedacore/keda-docs/pull/826
Related to https://github.com/kedacore/keda/pull/3380
=> feat: Introduce activationThreshold/minMetricValue for MongoDB Scaler

tests/internals/pause_scaling/pause_scaling_test.go, tests/run-all.sh, tests/scalers_go/activemq/activemq_test.go, tests/scalers_go/azure_pipelines/azure_pipelines_test.go
This PR improves activemq, az_pipeline nad pause_scaling e2e test and also increase the concurrency from 6 to 8.
I know that `redis-cluster-lists` fails but they are in ts so I will not touch them. I'm going to migrate them directly in other PR
Fixes #
Relates to #
=> fix: Updated flaky tests and max concurrent test

go.mod, go.sum
This PR bumps `github.com/emicklei/go-restful` to version `v2.16.0+incompatible`  to solve CVE-2022-1996. Maybe trivy still signals it as a vulnerability because it has an intentional delay in it database updates but [NVD has already updated the vulnerability to add this version as fixed](https://nvd.nist.gov/vuln/detail/CVE-2022-1996)
=> chore: bump github.com/emicklei/go-restful to address CVE-2022-1996

pkg/scalers/mysql_scaler.go, pkg/scalers/mysql_scaler_test.go, tests/scalers_go/mysql/mysql_test.go
Related to https://github.com/kedacore/keda-docs/pull/835
=> feat: Introduce activationThreshold/minMetricValue for MySQL Scaler

Makefile, tools/build-tools.Dockerfile
This PR bumps golang version for build-tools and bump it to golang 1.17.12.
Note: to make the process easier, I have removed the checksum validation because I can't recover it dynamically so I need to pass another build args. I think that this could be acceptable because this is only for tooling and not for prod images, but if we consider it as a requirement, I can pass ARM and AMD checksums as build args too.
=> chore: Use golang version as tag for build-tools and bump it

.github/workflows/build-tools.yml
Golang version for build-tools is set in `Makefile` now, so we need to add it to the triggering paths for the CI that generates the image
=> chore: Add extra path to build tools CI

CHANGELOG.md, go.mod, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go, pkg/util/tls_config.go
Signed-off-by: Tobias Krause <tobias.krause@otto.de>
Enhanced Kafka TLS configuration to accept a passphrase for a provided PKCS #8 private key. 
Fixes https://github.com/kedacore/keda/issues/3449
=> Kafka Scaler: added support for PKCS #8 private key decryption

CHANGELOG.md, controllers/keda/scaledobject_controller_test.go, pkg/scalers/activemq_scaler.go, pkg/scalers/artemis_scaler.go, pkg/scalers/azure_data_explorer_scaler.go, pkg/scalers/azure_data_explorer_scaler_test.go, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/external_scaler.go, pkg/scalers/external_scaler_test.go, pkg/scalers/kubernetes_workload_scaler.go, pkg/scalers/kubernetes_workload_scaler_test.go, pkg/scalers/scaler.go, pkg/scaling/scale_handler.go
Reference ScaledObject's/ScaledJob's name in the scalers log.
Sorry for the huge PR :(
Relates #3419
=> Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_pubsub_scaler_test.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_stackdriver_scaler_test.go, pkg/scalers/gcp_storage_scaler.go, pkg/scalers/gcp_storage_scaler_test.go, pkg/scalers/graphite_scaler.go
=> g*: Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/cassandra_scaler.go, pkg/scalers/cassandra_scaler_test.go, pkg/scalers/cpu_memory_scaler.go, pkg/scalers/cpu_memory_scaler_test.go, pkg/scalers/cron_scaler.go, pkg/scalers/cron_scaler_test.go, pkg/scalers/datadog_scaler.go, pkg/scalers/datadog_scaler_test.go, pkg/scalers/elasticsearch_scaler.go
=> c|d|e*: Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/huawei_cloudeye_scaler.go, pkg/scalers/huawei_cloudeye_scaler_test.go, pkg/scalers/ibmmq_scaler.go, pkg/scalers/influxdb_scaler.go, pkg/scalers/influxdb_scaler_test.go, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go, pkg/scalers/liiklus_scaler.go, pkg/scalers/liiklus_scaler_test.go
=> h|i|k|l*: Reference ScaledObject's/ScaledJob's name in the scalers log

pkg/scalers/postgresql_scaler.go, pkg/scalers/postgresql_scaler_test.go, pkg/scalers/predictkube_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/redis_scaler.go, pkg/scalers/redis_scaler_test.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/redis_streams_scaler_test.go, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go, pkg/scalers/solace_scaler.go, pkg/scalers/stan_scaler.go
=> p|r|s*: Reference ScaledObject's/ScaledJob's name in the scalers log

CHANGELOG.md
Changelog has invalid markdown
=> fix: Changelog has invalid markdown

pkg/scalers/azure_data_explorer_scaler.go, pkg/scalers/azure_data_explorer_scaler_test.go, pkg/scalers/redis_streams_scaler.go
Fixing outstanding issues introduced by this change.
=> fix: Reference ScaledObject's/ScaledJob's name in the scalers log

RELEASE-PROCESS.MD
Change status of sprint items to done after release
=> docs: Change status of sprint items to done after release

tests/helper/helper.go, tests/internals/idle_replicas/idle_replicas_test.go, tests/internals/pause_scaling/pause_scaling_test.go, tests/internals/restore_original/restore_original_test.go
=> Simplify internal e2e tests using Kubernetes Workload scaler.

tools/build-tools.Dockerfile
One leftover from the migration.
Relates to #2737
=> Node is no longer needed in build tools image

.github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .gitignore, Makefile
=> remove npm calls as node is not used anymore

.golangci.yml, CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go, pkg/scaling/scale_handler.go, tests/README.md, tests/scalers/nats_jetstream/nats_helper.go, tests/scalers/nats_jetstream/nats_jetstream_test.go
Add NATS JetStream scaler
Fixes #2391 
Documentation https://github.com/kedacore/keda-docs/pull/881
=> Add NATS JetStream scaler

pkg/scalers/nats_jetstream_scaler.go
=> chore: refactor logger for Nats Jetstream scaler

controllers/keda/scaledobject_controller.go, pkg/scalers/azure/azure_aad_podidentity.go, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/graphite_scaler.go, pkg/scalers/ibmmq_scaler.go, pkg/scalers/metrics_api_scaler.go, pkg/scalers/openstack/keystone_authentication.go, pkg/scalers/openstack_metrics_scaler.go, pkg/scalers/openstack_swift_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/pulsar_scaler.go, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/solace_scaler.go, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/scale_resolvers.go, tests/helper/helper.go
with `golangci-lint version 1.48.0` there can be discovered additional problems in the repo, some linting problems and some deprecations, such as:
```
SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
```
=> chore: fix deprecations and linting

.github/ISSUE_TEMPLATE/4_release_tracker.md, RELEASE-PROCESS.MD
Only publish new docs after KEDA has been released given that makes more sense.
=> chore: Only publish new docs after KEDA has been released

.github/workflows/pr-validation.yml, CHANGELOG.md, RELEASE-PROCESS.md
Fixes https://github.com/kedacore/keda/issues/3540
=> chore: Execute trivy scan (on PRs) only if there are changes in deps

CHANGELOG.md, config/metrics-server/deployment.yaml, config/metrics-server/service.yaml, pkg/metrics/prometheus_metrics.go, pkg/provider/provider.go, tests/internals/metrics_endpoint/metrics_endpoint_test.go, tests/internals/prometheus_metrics/prometheus_metrics_test.go
=> fix: Metrics endpoint returns correct HPA value

CHANGELOG.md, pkg/scalers/datadog_scaler.go
In getQueryResult(), check if the last point as a value before dereferencing it.
~~In the datadog scaler, returns the value of the last point with a value instead of the value of the last point.
This fixes a panic when the last point has a nil value when we try to dereference it.~~
~~Also moves duplicated code used when no metric can be found to a dedicated function.~~
Fixe #3448
=> Fix: panic in datadog scaler

CHANGELOG.md, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp/rabbitmq_queue_amqp_test.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp_vhost/rabbitmq_queue_amqp_vhost_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http/rabbitmq_queue_http_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http_vhost/rabbitmq_queue_http_vhost_test.go
After [this PR](https://github.com/kedacore/keda/pull/2591), the parsing of the `vHost` from the url changed. With this PR we restore that behaviour and add 2 extra e2e test to ensure that these changes works with and without `vHost` on `amqp` and `http`
Fixes https://github.com/kedacore/keda/issues/3602
=> fix(rabbitmq): Parse vhost correctly if it's provided in the host url

CHANGELOG.md, config/manager/manager.yaml, config/metrics-server/deployment.yaml
Add/update securityContext configs:
* seccompProfile.type RuntimeDefault is needed for compliance with restricted policies in Kubernetes 1.19+
* Updated comment in metrics Deployment regarding readOnlyRootFilesystem
Fixes #3561
=> feat: add seccompProfile

CHANGELOG.md, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go
=> Adding changes for configuring unsafe ssl for self signed certs use case

.github/workflows/pr-validation.yml, .github/workflows/template-trivy-scan.yml, go.mod, go.sum
ATM, the output is always `trivy.sarif` but for PRs should be `''` because otherwise the output is not routed to the agent console.
After solving the issue, trivy has detected a vulnerability in one dep, so I bumped it too
=> fix: Trivy output can be modified

adapter/main.go
This allows the user to specify which port the metrics API server container should use.
Relates to kedacore/keda#3576
Relates to https://github.com/kedacore/charts/pull/308
=> feat(metrics-api): allow user to configure metrics API server port

CHANGELOG.md
With the SDK update, this is now supported. No changes required.
Fixes #2920 
Relates to https://github.com/kedacore/keda-docs/pull/938
=> feat: Add support for SAS tokens for authentication in Azure Service Bus scaler.

pkg/scalers/authentication/authentication_helpers.go
Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>
- Corrects bearer spelling
- Improves grammar of error statements
- Removes unnecessary err word from error statement
=> fix: Corrected error statement spelling

pkg/scalers/rabbitmq_scaler.go
Reword a conditional statement in the RabbitMQ Scaler to match the error message that is returned when evaluating to true.
Translated in a sentence, the conditional statement would match "if excludeUnacknowledged is set and the protocol used is equal to amqp" instead of "if excludeUnacknowledged is set and the protocol used is different then http"
=> reword(rabbitmq): make condition match error string

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go
azure_pipelines_scalar.go has been modified to use a struct for the ADO JobRequest API to remove reliance on interface{} and a pre-run step has been introduced to remove previously completed jobs so only working jobs getting analysed for scaling
Fixes #
Issue (#3702)
Relates to #
=> Improved scaling speed of AzDO pipelines

CHANGELOG.md, go.mod, main.go
Adding flags to the manager main so that we can override the default client QPS and burst. This allows us to enable higher throughput of reconciliations when there is a lot of ScaledObjects in the cluster.
Regarding the helm chart: the flags can be added with `extraArgs.keda` in values.
Fixes #3730
=> Add ratelimitting parameters to keda manager

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
This allows specifying the GraphQL URL used by the Selenium Grid Scaler to be specified in a TriggerAuthentication resource and thus pulled from a secret store. We are using Selenium Grid's basic authentication and needed to specify a username/password as part of the URL.
Fixes #
Relates to https://github.com/kedacore/keda-docs/pull/959
=> feat: Allow specifying Selenium Grid URL as secret

.github/workflows/template-arm64-smoke-tests.yml
We have multiple ARM runners, but all of them run in the same machine, reusing the same Kind clusters, because we use the underlying docker engine with the same kubectl, I guess that we can improve this in the future, using different kind clusters and different kubectl (e.g: running in containers) but for the moment we can't.
This PR adds a concurrency group to avoid multiple smoke test executions running concurrently in ARM machines
=> chore: Add a concurrency group for arm-smoke-tests

go.mod, go.sum
=> fix: bump golang.org/x/text to solve CVE-2022-32149

pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_scaler_test.go
Add `queueURLFromEnv` as additional trigger metadata to allow loading the queueURL from env variables.
It would be useful to be able to set the queueURL to load from env variables, especially when having multiple deployment environment. This way if using kustomize, the queueURL could be defined in a configmap and loaded as env variable, rather than patching  the manifest. This for example would be similar to the `addressFromEnv` in the redis-lists scaler.
Signed-off-by: Fahdi Kanavati <fk128@users.noreply.github.com>
Fixes #
Relates to #
https://github.com/kedacore/keda-docs/pull/902
=> Add option to get queueURL from env for aws SQS scaler

CHANGELOG.md, pkg/metrics/adapter_prom_metrics.go, pkg/provider/provider.go, pkg/scaling/cache/scalers_cache.go, pkg/scaling/scale_handler.go
This PR is used to resolve https://github.com/kedacore/keda/issues/3588
* use the existing Trigger.Name field as the scalerName
* add scalerName to prometheus metric as a label to facilitate the grafana dashboard display
see below:
=> add trigger name as a label in Prometheus metrics

CHANGELOG.md, pkg/scalers/azure/azure_cloud_environment.go, pkg/scalers/azure/azure_cloud_environment_test.go, pkg/scalers/azure/azure_eventhub.go, pkg/scalers/azure/azure_eventhub_checkpoint.go, pkg/scalers/azure/azure_storage.go, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/azure_eventhub_scaler_test.go
Add support for pod identity based authentication to blob storage accounts in Event Hub scaler
Relates to #3569
Relates to kedacore/keda-docs#905
=> feat(event-hubs-scaler): Add pod/workload identity support to checkpoint in Azure Blob Storage

CHANGELOG.md, pkg/scalers/gcp_storage_scaler.go, pkg/scalers/gcp_storage_scaler_test.go
Signed-off-by: Ward Loos <ward.loos@gmail.com>
Fixes #3756
Relates to [#963](https://github.com/kedacore/keda-docs/pull/963)
=> GCP Storage scaler: Add Prefix and Delimiter support

CHANGELOG.md, pkg/scalers/azure_blob_scaler.go
The logger in Azure blob scaler was initialized but not saved. Thus, when logging an error, the logger segfaulted.
In addition, a very minor improvement of the log message which caused the segfault.
Note: I am not a GO developer and I have not tested it locally. 
Fixes #3811
Relates to #
=> fix(azure blob scaler): initialize logger #3811

CHANGELOG.md, pkg/scalers/metrics_api_scaler.go, pkg/scalers/metrics_api_scaler_test.go
Add unsafeSsl paramater to skil certificate validation when connecting over HTTPS
Fixes #3728 
Fixes https://github.com/kedacore/keda/issues/3821
[Relates to #972](https://github.com/kedacore/keda-docs/pull/972)
=> Metrics api unsafessl

adapter/main.go, controllers/keda/clustertriggerauthentication_controller.go, controllers/keda/scaledjob_controller.go, controllers/keda/scaledjob_finalizer.go, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_finalizer.go, controllers/keda/triggerauthentication_controller.go, controllers/keda/util/finalizer.go, pkg/prommetrics/adapter_prommetrics.go, pkg/prommetrics/operator_prommetrics.go, pkg/prommetrics/prommetrics.go, pkg/provider/provider.go, tests/internals/prometheus_metrics/prometheus_metrics_test.go
KEDA operates on many types of metrics, this has became confusing in the source code. Thus moving Prometheus related stuff from `metrics` package to `prommetrics` and bunch of renames of functions/properties.
Just source code chores, no functionality changes in this PR.
Relates to #3719
=> chore: move Prometheus related metrics to `prommetrics` package

controllers/keda/hpa_test.go, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_controller_test.go, pkg/prommetrics/adapter_prommetrics.go, pkg/provider/provider.go, pkg/scalers/scaler.go, pkg/scaling/cache/scalers_cache.go, pkg/scaling/cache/scalers_cache_test.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_test.go
Reverting part of the implementation done in #3650. Internally reuses `ScalerConfig` for the `triggerName`, also the name is visible in Prometheus metrics under label `scaler`.
Also checking uniqueness of `triggerName` in a ScaledObject.
Relates to #3650 #3588
=> triggerName is part of Prometheus metrics

CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go
Until now, the keda nats jetstream scaler did only use the `num_pending` value returned by the nats monitoring endpoint for a specifc consumer. The problem was that messages that should be re-delivered (retried) are not returned as part of the `num_pending` counter but they are in a separate counter called `num_ack_pending`.
This PR use the sum of these two counter to determine the value that should be used by keda instead of only the `num_pending` value.
This fixes two problems:
- Keda would never scale up a deployment/job based on a consumer if this consumer only has messages that are waiting for a retry.
- Keda would scale down deployment/job too fast because when a consumer pulls a message from nats, it decrements immediatly the `num_pending` counter and increment the …
=> fix(nats-jetstream): correctly count messages that should be redelivered (waiting for ack) towards keda value

CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go, pkg/scalers/nats_jetstream_scaler_test.go, pkg/scalers/stan_scaler.go, pkg/scalers/stan_scaler_test.go
Signed-off-by: Manuel Cañete <mcaneteubeda@gmail.com>
Fixes https://github.com/kedacore/keda/issues/3805
Relates to #
=> feat: support https protocol in nats scalers

CHANGELOG.md, pkg/scalers/authentication/authentication_helpers.go, pkg/scalers/loki_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/pulsar_scaler.go, pkg/scalers/pulsar_scaler_test.go, tests/scalers/pulsar/helper/helper.go
Signed-off-by: Michael Marshall <mmarshall@apache.org>
This PR adds support for both bearer tokens and basic authentication (and authorization) with Apache Pulsar. In order to reduce duplicate code, there are some backwards compatible changes made to TLS authentication. 
Note that because Apache Pulsar redirects HTTP calls using the 307 response code, it is necessary to re-add the authorization header. This PR includes that change. It is also important to add the `X-Pulsar-Auth-Method-Name` header to make authentication calls efficient on the broker.
Fixes https://github.com/kedacore/keda/issues/3844
Relates to https://github.com/kedacore/keda-docs/pull/977
=> Apache Pulsar: add support for bearer token and basic auth

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-smoke-tests.yml
=> feat: publish e2e test result as artifacts

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-smoke-tests.yml
=> fix: use correct wildcard for uploading logs

CHANGELOG.md, adapter/main.go, main.go
Keda-operator timing out for large number of configmaps and secrets. Hence disabling compression in client-go.
https://github.com/kedacore/keda/issues/3863
Fixes https://github.com/kedacore/keda/issues/3863
=> Disable response compression for k8s restAPI in client-go

pkg/util/tls_config.go, tests/scalers/pulsar/README.md, tests/scalers/pulsar/helper/helper.go
Signed-off-by: Michael Marshall <mmarshall@apache.org>
It is incorrect to override the default for `InsecureSkipVerify`. There are many parts of the code base use the default value for `InsecureSkipVerify` without testing TLS, so I did not add any tests and I did not make it configurable. I did manually verify the correctness of the change.
=> fix: Remove unnecessary TLS Config

CHANGELOG.md, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/elasticsearch_scaler_test.go
- Support providing `cloudID` and `apiKey` in Elasticsearch scaler enabling it to be used with ElasticSearch Service on Elastic Cloud.
- Add test case for missing `apiKey` parameters.
- Add test case for mutual exclusion between providing endpoint `addresses` and `cloudID`.
- Add test case for providing neither `addresses` nor `cloudID`.
- Fix `TestElasticsearchGetMetricSpecForScaling`, `testCase[7]` used as input returns a parsing error that was not being checked.
Relates to https://github.com/kedacore/keda/issues/3785
=> feat(scaler): support cloudID and apiKey in elasticsearch scaler

config/grafana/keda-dashboard.json
This commit adds a simple Grafana dashboard for the metrics exposed by Keda metric server.
Relates to https://github.com/kedacore/keda/issues/3911
Relates to https://github.com/kedacore/keda-docs/pull/985
=> Add simple Grafana dashboard

.github/stale.yml
=> chore: add `stale-bot-ignore` label to stale bot ignores

CHANGELOG.md, pkg/scalers/newrelic_scaler.go
Signed-off-by: Laszlo Kishalmi <laszlo.kishalmi@partech.com>
Trivial fix for #3945. The logging was initialized, but not saved return value. Took the idea from: #3811
Fixes #3945
=> fix: NewRelic scaler crashes on logging

config/grafana/keda-dashboard.json
added panel regarding HPA current/max replicas
Relates to #3911
=> Added panel regarding ammount of HPA

CHANGELOG.md, adapter/main.go
Fixes #3952
Relates to https://github.com/kedacore/keda/issues/3730
=> Metrics Server: use correct k8s config in Manager

pkg/scalers/azure_eventhub_scaler.go
as the scenario covered in this line is for the case in which the partition reached maxInt and started from zero. the calc is done wrongly.
Signed-off-by: Yoav Dobrin <37622785+yodobrin@users.noreply.github.com>
the calc of the remaining items to process is wrong
=> fix(azure event hub): wrong calc of the remaining items

.github/workflows/static-analysis.yml, .github/workflows/template-main-e2e-test.yml, SECURITY.md
I forgot to add `GCP_RUN_IDENTITY_TESTS: true` in the main-e2e workflow and that makes gcp_wi e2e tests to fail because the needed resources aren't deployed into the cluster. This PR solves it.
This PR also adds some missing things for semgrep
=> fix: add missing env var for gcp e2e and missing Semgrep stuff

.github/workflows/static-analysis.yml, pkg/scalers/cassandra_scaler.go, pkg/scalers/mongo_scaler.go, pkg/scalers/mssql_scaler.go, pkg/scalers/mysql_scaler.go, pkg/scalers/predictkube_scaler.go, pkg/scalers/redis_scaler.go
After adding semgrep, some alerts about using fmt.Sprintf($XX, $NET) instead of net.JoinHostPort were raised. This PR solves them replacing all the cases with net.JoinHostPort
=> fix: use net.JoinHostPort and fix semgrep pipeline

.github/stale.yml
Don't track issues with `breaking-change` label for stale issues
=> chore(stale): Don't track issues with `breaking-change` label for stale issues

CHANGELOG.md
Introduce breaking changes overview for v2.9 in release notes.
Relates to https://github.com/kedacore/keda/issues/3968
Relates to https://github.com/kedacore/keda/issues/3919
=> docs(changelog): Introduce breaking changes overview for v2.9 in release notes

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md
Add deprecations & breaking changes policy to changelog, contribution guide & PR template.
Relates to https://github.com/kedacore/governance/issues/68
Relates to https://github.com/kedacore/keda/issues/3968
=> chore(contributing): Deprecations & breaking changes policy introductino

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go, tests/helper/helper.go, tests/scalers/kafka/kafka_test.go
Add implementation for excluding consumer lag from partitions with persistent lag.
In situations where consumer is unable to process / consume from partition due to errors etc., committed offset will not change, and consumer lag on that partition will be increasing and never be decreased. KEDA trigger scaling towards the maxReplicaCount.
If partition lag is deemed as persistent, excluding its consumer lag will allow KEDA to trigger scaling appropriately based on the consumer lag observed on other topics and partition, and not be affected by this consumer lag which will not be resolved by scaling.
Upon each polling cycle, check if current consumer offset is same as previous consumer offset.
Different: return endOffset - consumerOffset (No different from current implementation)
Same: return …
=> Apache Kafka Scaler: Implementation for Excluding Persistent Lag

ROADMAP.md
v2.9 is delayed to Dec 9th to close all open PRs that are required.
#3968
=> chore: v2.9 is delayed to Dec 9th

BUILD.md, CHANGELOG.md, pkg/scalers/couchdb_scaler.go, pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go
If either the username or password contains a character in the set  :/?#[]@  ,  it must be percent-encoded or the scaler will fail.
Fixes https://github.com/kedacore/keda/issues/3992
=> fix(mongodb): escape username and password

.github/ISSUE_TEMPLATE/3_bug_report.yml
Introduce 2.9 as version in bug report.
Relates to https://github.com/kedacore/keda/issues/3968
=> chore(release): Introduce 2.9 as version in bug report

ROADMAP.md
Add KEDA v2.12 to our roadmap
Relates to https://github.com/kedacore/keda/issues/3968#
=> chore: Add KEDA v2.12 to our roadmap

CHANGELOG.md, pkg/scaling/cache/scalers_cache.go, pkg/scaling/scale_handler.go
The latest refactoring done in https://github.com/kedacore/keda/issues/2282 introduced a regression in ScaledJobs. Scalers cache hasn't been used and a new scaler(and connection) has been opened for each request.
Fixes #4011
Relates to https://github.com/kedacore/keda/issues/2282
=> fix: properly retrieve and close scalers cache

CHANGELOG.md, pkg/scaling/resolver/azure_keyvault_handler.go
=> fix(az key vault): Raise an error instead of panic if authentication not provided

CHANGELOG.md, pkg/scalers/redis_scaler.go, pkg/scalers/redis_scaler_test.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/redis_streams_scaler_test.go
Fixes https://github.com/kedacore/keda/issues/4005
=> fix: Support unsafeSsl and enable ssl verification as default

CHANGELOG.md, pkg/scalers/cpu_memory_scaler.go
I did a scan through all existing scalers and found out cpu_memory_scaler has the same issue, hence I create this MR to fix the initialization of logger
Fixes #3947 
Relates to #
=> fix: Logging for cpu memory scaler

CHANGELOG.md, pkg/scalers/aws_common.go, pkg/scalers/aws_dynamodb_scaler.go, pkg/scalers/aws_dynamodb_scaler_test.go, pkg/scalers/azure/azure_blob_test.go, pkg/scalers/azure/azure_queue_test.go, pkg/scalers/azure/azure_storage.go, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/elasticsearch_scaler_test.go, pkg/scalers/gcp_storage_scaler.go, pkg/scalers/liiklus_scaler.go, pkg/scalers/liiklus_scaler_test.go, pkg/scalers/mssql_scaler.go, pkg/scalers/mssql_scaler_test.go, pkg/scalers/redis_scaler.go, pkg/scalers/redis_scaler_test.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/redis_streams_scaler_test.go, pkg/scalers/scaler.go, pkg/scalers/scaler_test.go
Starting from Go 1.13, errors.Is is the preferable way to compare error equality.
Reference: https://go.dev/blog/go1.13-errors
=> refactor(scaler): compare error with `errors.Is`

CHANGELOG.md, pkg/prommetrics/adapter/adapter_prommetrics.go, pkg/prommetrics/prommetrics.go, pkg/provider/provider.go, pkg/scaling/cache/scalers_cache.go, pkg/scaling/scale_handler.go, tests/internals/prometheus_metrics/prometheus_metrics_test.go
Add scaler metric latency support
- ~[ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)~
- ~[ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
Relates to [#4037](https://github.com/kedacore/keda/issues/4037)
=> Add scaler metric latency support

CHANGELOG.md, pkg/scaling/cache/scalers_cache.go
- [N/A ] Tests have been added
- [N/A ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
Fixes #4092
=> fix: prevent panic while refreshing a scaler cache

CHANGELOG.md, pkg/provider/provider.go
…ing metrics
check that ScaledObject name is specified as part of a query for getting metrics
This doesnt work anymore: 
```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/sample-ns/s1-rabbitmq-queueName2"
```
A selector with ScaledObject's name needs to be specified:
```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/sample-ns/s1-rabbitmq-queueName2?labelSelector=scaledobject.keda.sh%2Fname%3D{ScaledObjectName}"
```
Fixes #4088
=> check that ScaledObject name is specified as part of a query for getting metrics

CHANGELOG.md, Dockerfile.adapter, cmd/adapter/main.go, cmd/operator/main.go, config/metrics-server/api_service.yaml, config/metrics-server/deployment.yaml, config/rbac/role.yaml, go.mod, go.sum, pkg/certificates/certificate_manager.go, pkg/metricsservice/client.go, pkg/metricsservice/server.go, pkg/metricsservice/utils/tls.go, vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go, vendor/modules.txt
This PR adds support for using TLS between KEDA components with client authentication,not just for encrypting the traffic, the client MUST authenticate itself using its own certificate. This reduces the risk of exposing metrics ignoring the cluster RBAC (if the operator grpc server doesn't have authentication, everyone could connect to it and get metric values, ignoring the cluster RBAC required for querying the metrics server).
This PR also register the injected certificates in the metrics server and exposes the tls cert instead of self-generating it on every restart. Now using the injected certificate (from our self-signed cert), we can (and we do) patch the apiservice manifest to include the caBundle, removing …
=> feat: Use self-signed certs for TLS (between components and between k8s and KEDA)

pkg/scalers/newrelic_scaler.go, tests/scalers/newrelic/newrelic_test.go
The same error is already generated in `GetFromAuthOrMeta()`
=> chore: remove duplicated error message returned from `GetFromAuthOrMeta()`

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
platformName included in the selenium grid scaler metadata so that it is possible to specify the desired platform to run the automated test considering that there are multiplatform nodes such as linux, Windows 10 available in the hub.
~- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)~
~- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
Relates to #4038
=> Add 'platformName' to selenium-grid scaler

pkg/prommetrics/prommetrics.go
=> fix: expose `keda_scaled_object_errors` metric from the operator

CHANGELOG.md, pkg/provider/provider.go, pkg/scaling/cache/scalers_cache.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_test.go
I have also taken the chance and refactored the code a little bit, to be more consistent and move the ScaledObject scaling related logic to scaler_handler.go and keep the scalers_cache.go just around the cache.
Fixes #4075
=> expose Prom Metrics also when getting ScaledObject State

CHANGELOG.md, pkg/prommetrics/prommetrics.go, pkg/scaling/scale_handler.go, tests/internals/prometheus_metrics/prometheus_metrics_test.go
This metric marks whether particular scaler is active (val = 1) or not (val = 0)
Fixes #4114
=> feat: expose `keda_scaler_active` Prometheus metric

CHANGELOG.md, cmd/adapter/main.go, cmd/operator/main.go, cmd/webhooks/main.go, pkg/util/motd.go, pkg/util/welcome.go
=> chore: Add a warning when KEDA run outside supported k8s versions

.golangci.yml, CREATE-NEW-SCALER.md, pkg/scaling/cache/scalers_cache.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_test.go, pkg/scaling/scalers_builder.go, tools/sort_scalers.sh
Just shuffling a few methods and splliting the code to be more readable. No functional changes.
=> chore: refactor scale_handler.go

.github/workflows/static-analysis-codeql.yml, .github/workflows/static-analysis-semgrep.yml, .github/workflows/static-analysis.yml, CHANGELOG.md
I have split into 2 different workflows, the static analyzers because they need different triggers, in theory both can be executed with a regular `pull_request` trigger but semgrep still has secrets (the token), so makes sense to have it safely, but CodeQL doesn't use secrets so moving it from `pull_request_target` to `pull_request` helps for future changes.
I have added more rules to CodeQL, I'm not 100% sure if it will work or not, but I think so
Fixes https://github.com/kedacore/keda/issues/4032
=> chore: Review CodeQL config

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
KEDA is supporting 0 as the default value for activationLagThreshold in kafka scaler. But if we set this field explicitly with the 0 value, KEDA is throwing below error:
"error":"error parsing kafka metadata: "activationLagThreshold" must be positive number"
A default should always behave the same whether you set it explicitly or leave it, if optional. 
Fixed the code to accept 0 in the configuration param. 
Fixes https://github.com/kedacore/keda/issues/4137
=> fix(kafka scaler):`activationLagThreshold` supports 0 as valid value

CHANGELOG.md, pkg/scaling/resolver/scale_resolvers.go, tests/secret-providers/hashicorp_vault/hashicorp_vault_test.go
Add support for Hashicorp Vault secrets backend version 1. The altered code is the same from the pull request #2772, with an end-to-end test to validate the changes.
Fixes #2645
Relates to #2772
Have a wonderful day,
Best regards.
=> Add support for Hashicorp Vault KV engine V1

pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_log_analytics_scaler_test.go
Allow users to configure whether or not they want to use SSL when using the azure monitor log analytic scaler.
Inspired by the Loki scaler.
Relates to #4046 
default value still remains false.
=> Azure log analytics scaler now supports the unsafeSsl flag

CHANGELOG.md, pkg/scalers/azure/azure_azidentity_chain.go, pkg/scalers/azure_servicebus_scaler.go
Relates to https://github.com/kedacore/keda/issues/4123
=> cherry-pick: Use new SDK with proper errors for service bus with pod identity (#4030)

CHANGELOG.md, pkg/scalers/redis_scaler.go
Fixes https://github.com/kedacore/keda/issues/4197
=> fix: Redis Scaler initialize the logger properly

CHANGELOG.md, pkg/scalers/cassandra_scaler.go, pkg/scalers/cassandra_scaler_test.go
Signed-off-by: ithesadson <thesadson@gmail.com>
Since the change I made before was a breaking change, I just fix the mistake and send a pr again.
Issue : #4110
Previous PR: #4079
If the clusterIPAddress contains port information, checking if the port information is entered in the clusterIPAddress will cause some errors.
Error example in current code: User enters the following values.
clusterIPAddress: "https://cassandra.test/"
port: "9042"
->Expected clusterIPAddress : https://cassandra.test:9042/
The actual clusterIPAddress: https://cassandra.test/
=> fix: Added port information check in ClusterIPAddress

CHANGELOG.md, pkg/scalers/kafka_scaler.go
Signed-off-by: Sergej Domme <sergej.domme@idealo.de>
This fix allows to return an error during the partition iteration in case the process of getting the lag from the partition fails finding the block.
Fixes #4098
=> fix(kafka-scaler): return error if partition processing fails

CHANGELOG.md, controllers/keda/hpa.go
Fixes https://github.com/kedacore/keda/issues/4207
=> Pass deep copy object to scalers cache from the ScaledObject controller

CHANGELOG.md, pkg/scalers/authentication/authentication_helpers.go, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/ibmmq_scaler.go, pkg/scalers/influxdb_scaler.go, pkg/scalers/predictkube_scaler.go, pkg/scalers/redis_scaler.go, pkg/util/http.go, pkg/util/http_test.go, pkg/util/tls_config.go
Relates to #https://github.com/kedacore/keda/issues/3961
Fixes #4193
=> chore: set VersionTLS12 as min default TLS version

CHANGELOG.md, pkg/util/nomalize_string_test.go, pkg/util/tls_config_test.go
Hi team,
This PR will increase the test coverage in `pkg/util` 
Fixes #3871
=> Increase test coverage in `pkg/util`

BUILD.md
Relates to https://github.com/kedacore/keda/issues/4153
=> fix: Update docs to explain how to generate certificates for debugging

CHANGELOG.md, pkg/scalers/kafka_scaler.go
Hi team,
This PR aims to make the error logging for `GetBlock()` more informative.
Fixes #4232
=> Kafka Scaler: Improve error logging for `GetBlock()` method

tests/internals/fallback/fallback_test.go
Add fallback test into `internals/`
- tests scales deployment replicas to 5 (max) -> ms-deployment replicas is updated to 0 (to envoke fallback) -> scale deployment replicas to 3 (fallback) -> restore MS server to verify replicas are updated to 5 (max)
Fixes #4129
=> new internals/fallback_test

CHANGELOG.md, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/cron_scaler.go, pkg/scalers/external_scaler.go
This PR consolidates `GetMetrics()` and `IsActive()` to `GetMetricsAndActivity()` for the remaining scalers (Azure Event Hub, Cron and External).
Fixes #4015
=> Consolidate `GetMetrics()` and `IsActive()` to `GetMetricsAndActivity()`

.github/workflows/auto-add-issues-to-project.yml
This is based on https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions as https://github.com/kedacore/keda/pull/4150 was not a proper fix
=> fix(automation): Automatically add new issues to GitHub Project

CHANGELOG.md, pkg/scalers/datadog_scaler.go
The Datadog API now creates a generic error object when returning a 429.
This fix checks the response object before the error object to craft a more complete error when reaching too many requests.
~- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)~
~- [ ] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)~
~- [ ] Tests have been added~
~- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*~
~- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if …
=> DataDog: Check for response object before returning the generic error

CHANGELOG.md, pkg/fallback/fallback.go, pkg/fallback/fallback_test.go, tests/internals/fallback/fallback_test.go
Fixes https://github.com/kedacore/keda/issues/4249
=> fix: Fallback calculation returns correct value

CHANGELOG.md, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/azure_servicebus_scaler_test.go
=> fix: change way of returns service bus namespace object

CHANGELOG.md
Clarify recent Azure Service Bus improvement as the current entry is fairly vague/unusable.
Relates to https://github.com/kedacore/keda/issues/4262
=> docs(changelog): Clarify recent Azure Service Bus improvement

tests/scalers/azure/azure_service_bus_queue_aad_wi/azure_service_bus_queue_aad_wi_test.go
=> chore: use random queue name for servicebus e2e test

CHANGELOG.md
Broken link to metric deprecation.
=> fix(changelog): Broken link to metric deprecation

CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go, pkg/scalers/nats_jetstream_scaler_test.go
I'm trying to use NATS Jetstream scaler, previously I workaround the lack of NATS Jetstream scaler by using Prometheus in middle of NATS and Keda. I run into issue with the NATS Jetstream scaler because our stack use 3 VMs for NATS Jetstream cluster and round robin load balancer. 
Currently the scaler assume NATS node always have `<node>.<monitoringURL>` as URL for the node, which is not the case when NATS cluster is not on kubernetes. `<monitoringURL>/varz` endpoint respond with
```
curl -s -X GET "http://nats.company.internal:8222/varz" | jq .cluster
{
"name": "nats",
"addr": "172.0.0.2",
"cluster_port": 4221,
"auth_timeout": 2,
"urls": [
"172.0.0.3:4221", // <--- VM's IP
"172.0.0.4:4221"
],
"tls_timeout": 2
}
```
Because the scaler assume it's on kubernetes, it splits url by `. (dot)` …
=> Add support when JetStream cluster not on kubernetes

CHANGELOG.md, cmd/adapter/main.go, pkg/metricsservice/client.go, pkg/provider/provider.go
Metrics Server: print a message on successful connection to gRPC server.
Also rearanged the startup logic a little bit, to make the output log more clear.
Fixes #4190
=> Metrics Server: print a message on successful connection to gRPC server

CHANGELOG.md, pkg/scalers/aws_cloudwatch_scaler.go, pkg/scalers/aws_cloudwatch_scaler_test.go, tests/scalers/aws/aws_cloudwatch_expression/aws_cloudwatch_expression_test.go
When we use `expression` in cloudwatch scalers, metricName and namespace aren't needed but even though it, they were required. This PR removes this requirement
Fixes https://github.com/kedacore/keda/issues/4334
=> fix(aws-cloudwatch): Not require uneeded fields

pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
Ignores whitespaces in partitionLimitation.
Fix a spelling mistake on the way.
Add a few more tests cases.
Note that currently it is not possible to configure a limitation so that
no partition will be consumed!
Relates to #4328
=> fix(kafka): Make parsing partitionLimitation more resilient against ws

CHANGELOG.md, pkg/scalers/azure/azure_app_insights.go, pkg/scalers/azure_app_insights_scaler.go, pkg/scalers/azure_app_insights_scaler_test.go
Added the option to ignore errors during the extraction of Azure Application Insights values
Relates to #4316
Inspired by #3073
Relates to https://github.com/kedacore/keda-docs/pull/1084
=> Azure Application Insights: Add option to ignore null values

CHANGELOG.md, pkg/scalers/azure_blob_scaler.go, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
Hi team,
This MR will solve 
Example:
```diff
triggers:
- type: kafka
metadata:
bootstrapServers: kafka.svc:9092
consumerGroup: my-group
topic: test-topic
lagThreshold: '5'
activationLagThreshold: '3'
offsetResetPolicy: latest
allowIdleConsumers: false
scaleToZeroOnInvalidOffset: false
excludePersistentLag: false
version: 1.0.0
+   saslAuthType: plaintext|scram_sha256|scram_sha512|oauthbearer|none
+   enableTls: true|false
```
Fixes #3611
Relates to #
=> fix: move `sasl` and `tls` flag to ScaledObject instead of specifying in TriggerAuthentication

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
It is necessary to check if the browserVersion is defined in the session before validating if the browserVersion in the trigger of the ScaledObject is set to latest. This way, it will avoid matching a ScaledObject whose browserVersion is set to latest in the trigger to sessions that may have browserVersion with different values.
Fixes #4347
=> Fix scaledObject always matching when browserVersion is latest in trigger metadata

CHANGELOG.md, pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_scaler_test.go
`awsSqsQueueMetricNames` variable was defined at package level and it was modified based on trigger parameters. 
This makes it shared across all the ScaledObjects, which isn't correct
Fixes https://github.com/kedacore/keda/issues/4276
=> fix(aws-sqs): Respect `scaleOnInFlight` value

ROADMAP.md
Provide updated roadmap which adds release notes for v2.10 and introduces 2.13 which is proposed to be 1 month later due to holidays in December.
Relates to https://github.com/kedacore/keda/issues/4349
=> chore: Provide updated roadmap

.github/workflows/pr-e2e.yml
finish with `*` when grabbing regex
example of problematic comment body: 
- the closing `"` is on the newline and this doesnt run the tests
https://github.com/kedacore/keda/actions/runs/4413811530/jobs/7735089071#step:8:2 
the line should be `MESSAGE="/run-e2e cpu*"`, **NOT** `MESSAGE="/run-e2e cpu*` - in this case the closing double-quote is on the next line
=> fix e2e test case workflow regex matching (#4363)Co-authored-by: Jorge Turrado Ferrero <Jorge_turrado@hotmail.es>

CHANGELOG.md, controllers/keda/scaledobject_controller.go
=> fix odd number of arguments passed as key-value pairs for logging

.github/workflows/template-main-e2e-test.yml
=> chore: Upload artifacts in case of failure in main e2e tests

tests/scalers/github_runner/github_runner_test.go
=> fix: Use latest image for GH Actions e2e test to avoid agent updates (#4373

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-smoke-tests.yml
=> fix: Use explicit parameter for workflow step (#4376

tests/internals/custom_hpa_name/custom_hpa_name_test.go
After adding the new validations for the CPU, custom-hpa test is failing because minReplicaCount is 0 
with only CPU trigger
=> chore: fix custom hpa name e2e test

BUILD.md, CHANGELOG.md, apis/keda/v1alpha1/scaledobject_webhook.go, apis/keda/v1alpha1/scaledobject_webhook_test.go
Fixes https://github.com/kedacore/keda/issues/4396
=> fix: Allow to remove the finalizer even if the ScaledObject isn't valid

CHANGELOG.md, pkg/scalers/solr_scaler.go, pkg/scalers/solr_scaler_test.go, pkg/scaling/scalers_builder.go, tests/scalers/solr/solr_test.go
+Adds Solr Scaler for autoscaling based on solr queries
Relates to #4234 
Relates to https://github.com/kedacore/keda-docs/pull/1093
=> feat(Scaler): Adds Solr Scaler

.github/workflows/pr-e2e.yml
After switching to go script for e2e tests, the regex has changed and this PR updates the workflow to capture the correct regex (using the original approach) and removing the whitespaces to avoid problems with the command
=> fix: Use the previous regex removing the multilines from matches (#4438

Makefile
Cosign v2 has been released and it requires a confirmation for signing the images with OIDC because it exposes information like email of the signer.
=> fix: skip cosign confirmation promt

tools/build-tools.Dockerfile
The official installation script now supports ARM64. 
This PR installs az-cli in the ARM64 images using the official script instead of pip
=> chore: Use default script to instal az-cli

pkg/scalers/gcp_pubsub_scaler.go
Causing:
```
DPANIC	gcp_pub_sub_scaler	odd number of arguments passed as key-value pairs for logging	
```
<!--
=> chore: GCP - fix logger

tests/scalers/solace/solace_test.go, tests/sequential/prometheus_metrics/prometheus_metrics_test.go
- Solace e2e: Updated the chart url
- Prometheus metrics: increased timeout and used a unique name for the metric label
=> fix(e2e): fixed some issues with e2e tests

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, Makefile
For reducing costs, this PR scales out the cluster to current nodes (4) before the tests execution and scales in the cluster again after them. 
I have checked the `stop` option but based on [documentation](https://learn.microsoft.com/en-us/azure/aks/start-stop-cluster?tabs=azure-cli#start-an-aks-cluster), we shouldn't stop/start the cluster too often, and we can execute several times the test in a row, stopping and starting the cluster in less than the recommended 15-30 minutes.
As we cannot guarantee the period between stop/starts, I guess that it's better if we only reduce the cluster size.
**This process increases the execution time 3-5 minutes per execution**
=> chore: Add logic to scale out/in the AKS cluster on every e2e test execution

CHANGELOG.md
Include cluster autoscaling in changelog
Relates to #4456
=> chore: Include cluster autoscaling in changelog

CHANGELOG.md, config/grafana/keda-dashboard.json
Use `range` instead of `instant` for HPA current/max replicas (time based).
Right now, we are using the `instant` selector, which given that the panel should be time-based (as per the title), it should use a `range` selector, thus getting all metrics in a given timeframe, not just the last data point.
Also, moved from bars to lines because bars are hard to visualize using `ranges` containing several days worth of data.
Before:
After:
=> fix(config/grafana): use range for HPA metrics

.github/workflows/pr-e2e.yml, tests/run-all.go
=> fix(e2e): Add again the path filter to ignore non e2e tests during the execution

tests/internals/polling_cooldown_so/polling_cooldown_so_test.go, tests/scalers/etcd/etcd_cluster/etcd_cluster_test.go, tests/scalers/etcd/helper/helper.go, tests/scalers/kafka/kafka_test.go, tests/scalers/redis/redis_cluster_lists/redis_cluster_lists_test.go, tests/scalers/redis/redis_sentinel_lists/redis_sentinel_lists_test.go, tests/scalers/redis/redis_standalone_lists/redis_standalone_lists_test.go, tests/sequential/disruption/disruption_test.go
After upgrading to k8s 1.26, e2e tests have started to fail. I have noticed that HPA has set `ScalingActive` to false due `AmbiguousSelector`.
In k8s 1.26 there is a new commit disabling the HPA in case of ambiguous selectors: 
https://github.com/kubernetes/kubernetes/blob/f9340f3cf1f473f7da44594ea4974635f59f7ba1/CHANGELOG/CHANGELOG-1.26.md?plain=1#L809
=> fix: Update e2e tests after upgrade k8s 1.26

CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go, pkg/scalers/nats_jetstream_scaler_test.go, tests/scalers/nats_jetstream/nats_jetstream_cluster/nats_jetstream_cluster_test.go
=> find the stream leader the old way if nodes are not advertised

config/manager/manager.yaml
Unlike the webhooks and metrics API server deployment, the `POD_NAMESPACE` environment variable is not set by the manager deployment, which causes problems when the manager is deployed to a namespace other than `keda` and then tries to create a secret containing its self-signed certs for the gRPC service (but attempts to create it in the `keda` namespace).
=> fix: Set POD_NAMESPACE env var on manager deployment

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_oauth_token_provider.go, pkg/scalers/kafka_scaler_test.go
Add support for OAuth extensions for Kafka Scaler. This is required for using OAuth with a Confluent Kafka Server ([KIP-342](https://cwiki.apache.org/confluence/display/KAFKA/KIP-342%3A+Add+support+for+Custom+SASL+extensions+in+OAuthBearer+authentication)).
Fixes https://github.com/kedacore/keda/issues/4544
Relates to https://github.com/kedacore/keda-docs/pull/1121
=> feat: Add OAuth extensions for kafka scaler

CHANGELOG.md, pkg/scalers/azure_queue_scaler.go, pkg/scalers/external_scaler.go, pkg/scalers/external_scaler_test.go, pkg/util/tls_config.go, pkg/util/tls_config_test.go
Hi team,
This PR will fix the issue #3565
Relates: https://github.com/kedacore/keda/issues/4549
=> External Scaler: Add tls options in TriggerAuth metadata

SECURITY.md
We use a combo of Renovate + Dependabot
- [x Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
=> docs(security): Add Dependabot to security policy

CHANGELOG.md, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go
Hi team,
This PR add support for `unsafeSsl` as currently the default option for RabbitMQ scaler is hard coded to be `unsafeSsl` = false. This PR will make the RabbitMQ consistent with other scalers
I also do minor refactoring of the method `parseRabbitMQMetadata` due to high cyclomatic complexity flagged in the CI check [link](https://github.com/kedacore/keda/actions/runs/5070027312/jobs/9104458445?pr=4571)
Fixes #4448
=> Support `unsafeSsl` for RabbitMQ scaler

.github/workflows/pr-validation.yml, Makefile, config/e2e/kustomization.yaml, hack/verify-manifests.sh
This PR adds a manifest up-to-date verification and also deploys the CRDs using `server-side` as part of e2e deployment
=> chore: add manifest verification and use server-side for CRDs

CHANGELOG.md, tests/helper/helper.go, tests/internals/min_replica_sj/min_replica_sj_test.go, tests/scalers/external_push_scaler/external_push_scaler_test.go, tests/scalers/external_scaler_sj/external_scaler_sj_test.go, tests/scalers/external_scaler_so/external_scaler_so_test.go, tests/scalers/mongodb/mongodb_test.go
=> chore: Add external-push scaler e2e tests

tests/scalers/azure/azure_pipelines_adv/azure_pipelines_adv_test.go
Fixed image ref of azure agent to use keda, not eldarrin
Fixes #
Relates to #
=> Fixed azure agent image ref

pkg/scalers/redis_streams_scaler_test.go
Follow convention of **assert.Equal**.
**Expected** should be go ahead before **actual**.
=> Follow convention of assert

.github/workflows/pr-e2e.yml
Introduce `/skip-e2e` comment to add label to skip e2e test
=> chore: Introduce /skip-e2e to add label to skip e2e test

.github/workflows/pr-welcome.yml
PR Welcome bot fails with resource not accessible by integration for external contributors and is lacking permissions, let's find out which ones!
Relates to #4640
=> fix: PR Welcome bot fails with resource not accessible by integration

.github/workflows/pr-e2e-checker.yml, .github/workflows/pr-e2e-creator.yml
Improve E2E GitHub Action Names as the current ones are confusing:
=> test: Improve E2E GitHub Action Names

.pre-commit-config.yaml, CHANGELOG.md, pkg/scalers/gcp_common.go, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_storage_scaler.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go, tests/scalers/gcp/gcp_prometheus_workload_identity/gcp_prometheus_workload_identity_test.go
This PR adds Google's authentication in order to access metrics from [Google Managed Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus).
Fixes https://github.com/kedacore/keda/issues/4674
Relates to https://github.com/kedacore/keda-docs/pull/1153
=> feat(scaler/prometheus): support authentication for Google Managed Prometheus

CHANGELOG.md, pkg/scalers/aws_dynamodb_scaler.go, pkg/scalers/aws_dynamodb_scaler_test.go
Fixes #4680
Relates to https://github.com/kedacore/keda-docs/pull/1154
=> feat: support `indexName` in dynamodb scaler

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
Hi team, 
This PR aims to fix https://github.com/kedacore/keda/issues/4689. Not sure it could be backported to 2.10. Please advise me on this matter. :pray:
=> Kafka Scaler: add back `strings.TrimSpace()` function for saslAuthType

CHANGELOG.md, apis/keda/v1alpha1/condition_types.go, apis/keda/v1alpha1/scaledobject_types.go, config/crd/bases/keda.sh_scaledobjects.yaml, controllers/keda/hpa.go, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_controller_test.go, pkg/scaling/executor/scale_scaledobjects.go, tests/internals/pause_scaling/pause_scaling_test.go
In the controller in the reconcile loop, when a scaledObject is paused (annotated with ), this fix stops the scaling logic (to prevent attempt to connect the to scalers), and deletes the generated HPA (so it is not querying KEDA Metric Server for metrics)
Fixes #4253
=> fix: stop scale loop for pause Scaledbject (issue #4253)

CHANGELOG.md, apis/keda/v1alpha1/scaletriggers_types.go
Exclude Azure Monitor scaler from `metricName` deprecation.
`metricName` in AzureMonitor scaler refers to the actual name of the underlying metric in Azure.
Relates to https://github.com/kedacore/keda-docs/issues/1152
Relates to https://github.com/kedacore/keda-docs/pull/1158
=> fix: exclude Azure Monitor scaler from metricName deprecation

CHANGELOG.md, pkg/scalers/solace_scaler.go, pkg/scalers/solace_scaler_test.go, tests/scalers/solace/solace_test.go
Added new metric: **messageReceiveRateTarget** to Solace Scaler
Fixes #4665
=> Add metric to Solace Scaler

CHANGELOG.md, pkg/util/welcome.go
Supported Kubernetes versions will be v1.25 - v1.27 in KEDA v2.11
Relates to https://github.com/kedacore/keda/issues/4710 (release)
Relates to https://github.com/kedacore/keda-docs/pull/1162 (docs)
=> feat: Supported Kubernetes versions will be v1.25 - v1.27 in KEDA v2.11

.github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/template-main-e2e-test.yml, Dockerfile, Dockerfile.adapter, Dockerfile.webhooks
Relates to https://github.com/kedacore/keda/issues/4517
=> bump Go to 1.20.5

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_webhook.go, apis/keda/v1alpha1/scaledobject_webhook_test.go, tests/internals/scaled_object_validation/scaled_object_validation_test.go
=> Support ScaledObject taking over existing HPAs with the same name while they are not managed by other ScaledObject

CHANGELOG.md, apis/keda/v1alpha1/condition_types.go, apis/keda/v1alpha1/scaledjob_types.go, config/crd/bases/keda.sh_scaledjobs.yaml, controllers/keda/scaledjob_controller.go, controllers/keda/util/predicate.go, tests/internals/pause_scaledjob/pause_scaledjob_test.go, tests/internals/pause_scaledobject/pause_scaledobject_test.go
--- Accreditation ---
Original PR: https://github.com/kedacore/keda/pull/3828
Borrows from the work originally implemented by: https://github.com/keegancwinchester
Note: I would have loved to have pulled the commit from the original branch, but I could not be able to.
Documentation MR by original implementor: https://github.com/kedacore/keda-docs/pull/932
--- Fixes ---
Fixes https://github.com/kedacore/keda/issues/3303
--- PR Notes ---
Introduce annotation to pause ScaledJobs.
=> feat: Provide support for explicitly pausing autoscaling of ScaledJobs

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/4710
=> prepare release 2.11.0

CHANGELOG.md, pkg/scalers/prometheus_scaler.go
The prometheus scaler should expect a value of "none" to determine
that no pod identity provider is set.
Fixes #4695
=> Bug: Check for "none" when checking pod identity provider

CHANGELOG.md, pkg/scalers/authentication/authentication_types.go, pkg/scalers/pulsar_scaler.go, pkg/scalers/pulsar_scaler_test.go, pkg/scalers/scaler.go
Hi team,
This PR aims to ix `msgBacklogThreshold` field being named wrongly as `msgBacklog` . I pass down the logger into the method  `parsePulsarMetadata` as well
Fixes #4681
=> Pulsar Scaler: fix `msgBacklogThreshold` field being named wrongly as `msgBacklog`

CHANGELOG.md
IDK why, we missed this breaking change in the changelog (we did all the other stuff like deprecation announce and so on)
=> fix: Changelog refects breaking changes properly

pkg/scaling/executor/scale_scaledobjects.go, pkg/scaling/executor/scale_scaledobjects_test.go
1. Fix typo: then => than
2. Use predefined variable to increase consistency.
Fixes #
Relates to #
=> Fix typo and reuse predefined value

CHANGELOG.md, pkg/scaling/resolver/scale_resolvers.go, tests/scalers/aws/aws_cloudwatch_pod_identity/aws_cloudwatch_pod_identity_test.go, tests/scalers/aws/aws_dynamodb_pod_identity/aws_dynamodb_pod_identity_test.go, tests/scalers/aws/aws_dynamodb_streams_pod_identity/aws_dynamodb_streams_pod_identity_test.go, tests/scalers/aws/aws_kinesis_stream_pod_identity/aws_kinesis_stream_pod_identity_test.go, tests/scalers/aws/aws_sqs_queue_pod_identity/aws_sqs_queue_pod_identity_test.go
Fixes https://github.com/kedacore/keda/issues/4767
=> fix: AWS Pod Identity uses default service account if not provided

.github/workflows/pr-e2e.yml
Use dedicated PAT for skipping e2e instead of GITHUB_TOKEN which does not support triggering other workflows
https://github.com/actions/github-script#using-a-separate-github-token
=> fix(automation): Use dedicated PAT for skipping e2e

CHANGELOG.md, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_controller_test.go
Fix typo at controller (Unknow -> Unknown)
Fixes #
Relates to #
=> Fix typo at controller

tests/scalers/solr/solr_test.go
=> fix(solr e2e): remove '-' from status command

.github/workflows/template-smoke-tests.yml
Reverts kedacore/keda#4838
After this bump, the smoke tests on ARM64 are failing: https://github.com/kedacore/keda/actions/runs/5743980509/job/15570101840
Something looks wrong with kind version
=> Revert "chore(deps): bump helm/kind-action from 1.7.0 to 1.8.0"

.devcontainer/Dockerfile
Hi team,
This MR fixes the following two errors when I break down the `RUN` command line by line
- The first error is about installing `docker-ce-cli`
```
142.7 Package docker-ce-cli is not available, but is referred to by another package.
142.7 This may mean that the package is missing, has been obsoleted, or
142.7 is only available from another source
142.7 
142.8 E: Package 'docker-ce-cli' has no installation candidate
```
- The second error happens when we try to install `pre-commit` python package with `pip`
```
161.2 error: externally-managed-environment
161.2 
161.2 × This environment is externally managed
161.2 ╰─> To install Python packages system-wide, try apt install
161.2     python3-xyz, where xyz is the package you are trying to
161.2     install.
161.2     
161.2     If you …
```
=> Fix docker build error for go 1.20.5 version

README.md, TESTING.md, tests/README.md
I have ported the documentation that we provided during graduation DD to the repository in order to make it publicly accessible and easy to find
Fixes https://github.com/kedacore/keda/issues/4173
=> chore: Add testing documentation

CHANGELOG.md, CONTRIBUTING.md
Update golangci-lint version documented in CONTRIBUTING.md since old version doesn't support go 1.20
Fixes #
Relates to #
=> docs: Update golang-ci in contribution guide 

ROADMAP.md
KEDA v2.12 is targeted for September 26th, instead of 12th, to ensure we have enough time to incorporate all open contributions after summer vacation.
=> chore: KEDA v2.12 is targeted for September 26th, instead of 12th

CHANGELOG.md, pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_scaler_test.go
This pull request introduces an option to include delayed messages when calculating the message count with the AWS SQS scaler.
Fixes https://github.com/kedacore/keda/issues/4377
Relates to and supersedes https://github.com/kedacore/keda/pull/4383
Documentation https://github.com/kedacore/keda-docs/pull/1213
=> feat(aws-sqs): Support for scaling to include delayed messages

.github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, CHANGELOG.md
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo ::set-output name=mod_cache::$(go env GOMODCACHE)
echo ::set-output name=build_cache::$(go env GOCACHE)
```
**TO-BE**
```yaml
echo "mod_cache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
echo "build_cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
```
Fixes #4914
=> chore: Replace deprecated command with environment file

CHANGELOG.md, pkg/scalers/solace_scaler.go, pkg/scalers/solace_scaler_test.go
Hi team,
This PR aims to fix a bug where `queueName` is not properly escaped before adding to `endpointURL`
Fixes https://github.com/kedacore/keda/issues/4936
=> Add Fix to solace `endpointURL` to query escape special character from `queueName`

renovate.json
https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
=> Update renovate.json to use pinned commits

CHANGELOG.md, pkg/scalers/authentication/authentication_helpers.go, pkg/scalers/prometheus_scaler_test.go
Added strings.TrimSuffix to customAuth interpreter to avoid auth failure.
*TrimSuffix was used rather than TrimSpace to avoid unwanted removal of randomly generated strings with "\n" 
Relates to #
https://kubernetes.slack.com/archives/CKZJ36A5D/p1694069463138859
Fixes #4960
=> Prometheus Scaler: Remove trailing whitespaces in customAuthHeader and customAuthValue

CHANGELOG.md, config/metrics-server/deployment.yaml
Signed-off-by: Adarsh-verma-14 [t_adarsh.verma@india.nec.com](mailto:t_adarsh.verma@india.nec.com)
In the logs of keda-metrics-apiserver, show only printing errors, but errors should go to stderr.
Fixes #4049
=> Show only logs with a severity level of ERROR or higher in the stderr

.devcontainer/Dockerfile, .github/workflows/pr-validation.yml, .golangci.yml
- disable depguard check because it reports errors in main on `pre-commit run --all-files` in newer versions 1.53 and 1.54 - probably needs to be configured.
- update golangci-lint version to 1.54.2
see issue below for output
Relates to #4980
=> disable depguard temporarily & update golangci-lint

CHANGELOG.md
I merged a commit with the changelog entry in the wrong section
=> chore: update the changelog to reflect the breaking change

CHANGELOG.md, pkg/scalers/redis_scaler.go, pkg/scalers/redis_scaler_test.go, pkg/scalers/redis_streams_scaler.go, pkg/scalers/redis_streams_scaler_test.go
Allow defining TLS config in `TriggerAuthentication` for Redis scaler.
Fixes #4917
Relates to #
=> Add tls authentication for redis scaler

CHANGELOG.md, cmd/adapter/main.go, cmd/operator/main.go, cmd/webhooks/main.go, go.mod, go.sum, vendor/go.uber.org/automaxprocs/.codecov.yml, vendor/go.uber.org/automaxprocs/.gitignore, vendor/go.uber.org/automaxprocs/CHANGELOG.md, vendor/go.uber.org/automaxprocs/CODE_OF_CONDUCT.md, vendor/go.uber.org/automaxprocs/CONTRIBUTING.md, vendor/go.uber.org/automaxprocs/LICENSE, vendor/go.uber.org/automaxprocs/Makefile, vendor/go.uber.org/automaxprocs/README.md, vendor/go.uber.org/automaxprocs/automaxprocs.go, vendor/go.uber.org/automaxprocs/glide.yaml, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go, vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go, vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go, vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go, vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go, vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go, vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go, vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go, vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go, vendor/go.uber.org/automaxprocs/maxprocs/version.go, vendor/modules.txt
=> Automatically set `GOMAXPROCS` to match Linux container CPU quota

CHANGELOG.md, cmd/operator/main.go, pkg/certificates/certificate_manager.go
Default is `cluster.local`, users have a possibility to overwrite via parameter `--k8s-cluster-domain` on KEDA operator 
Fixes #4861
=> feat: configurable K8s cluster domain for Cert Manager

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Prepare 2.12 release:
- Improve changelog for 2.12
- Provide new unreleased section
- Add 2.12 to bug template
Relates to https://github.com/kedacore/keda/issues/4994
=> chore: Prepare KEDA v2.12 release

CHANGELOG.md, pkg/scalers/authentication/authentication_helpers.go, pkg/scalers/authentication/authentication_types.go, pkg/scalers/pulsar_scaler.go, pkg/scalers/pulsar_scaler_test.go
Support endpointParams in pulsar oauth and parameters including audience could be set after this PR.
Fixes https://github.com/kedacore/keda/issues/5069
Relates to https://github.com/kedacore/keda-docs/pull/1243
=> support endpointParams in pulsar oauth

CHANGELOG.md, pkg/scaling/resolver/scale_resolvers.go
=> chore: add info about aad-pod-identity deprecation

.github/workflows/main-build.yml, .github/workflows/release-build.yml
As the image build generates multi-arch output, we can use our own runners instead of GH hosted runners. As our runners are more power, this change can improve build times
=> chore: use ARM64 runner for main/release build

README.md
Currently, already existing links to workflows on readme.md are broken
=> fix: Update workflow badges on readme.md

CHANGELOG.md, pkg/scaling/scale_handler.go, tests/sequential/broken_scaledobject_tolerancy/broken_scaledobject_tolerancy_test.go
Fixes https://github.com/kedacore/keda/issues/5083
=> fix: Prevented stuck status due to timeouts during scalers generation

CHANGELOG.md, pkg/metricscollector/opentelemetry.go
- wrong logger
- removing some `fmt.Printl()` commands
Fixes #5094
=> Fix logger in OTEL collector

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go
Previously, having a space in the pool name would cause HTTP 400 responses from ADO which lead to metadata parsing errors from KEDA. This should no longer happen now that the pool name is escaped.
Fixes #5107 
I've added a test to the existing file (fails before, passes now) but I'm not properly set up to integration test this - I hadn't written any Go since <100 lines 5 years ago so I had to do a bunch of setup already. Should work, it's not exactly complicated.
Also changed `url` vars in the file to `urlString`.
=> fix: URL encode poolName in azure-pipelines

config/webhooks/service.yaml
This addresses the issue https://github.com/kedacore/charts/issues/500
Only webhook's svc name is http, others are fine
Fixes #
Relates to #
=> Fix the svc name of webhook to avoid breaking istio

Makefile
The 3rd party tool that we use for testing workload identity for GCP has introduced some changes. This PR applies them
=> fix: use new injection appoach for gcp e2e tests

CHANGELOG.md, pkg/scalers/apache_kafka_scaler.go, pkg/scalers/kafka_scaler.go
Relates to https://github.com/kedacore/keda/issues/5102
=> Add more logs to debug the output of Sarama `DescribeTopics` method

CHANGELOG.md, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/hashicorpvault_handler_test.go
Hi team,
This PR fixes the issue where the operator panics when `spec.hashiCorpVault.credential.serviceAccount` is not set
There are two ways we can fix this:
- One way is to throw out error
- Another way is to set a default value to `spec.hashiCorpVault.credential.serviceAccount=/var/run/secrets/kubernetes.io/serviceaccount/token`
Personally I prefer the second option. Please let me know your preference so that I can make changes to the documentation repo accordingly.
Fixes https://github.com/kedacore/keda/issues/4964
=> Fix operator panic when spec.hashiCorpVault.credential.serviceAccount is not set

CHANGELOG.md, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_pubsub_scaler_test.go
Fix that the default value of `value` is used when default value of `mode` is used for GCP pubsub scaler.
- [N/A] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
Fixes #5093
Relates to #
=> gcp_pubsub: fix scaled object default value (#5093)

CHANGELOG.md, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/hashicorpvault_handler_test.go
This PR fixes the issue where keda operator throwing panic error while using `ScaledObject` with `TriggerAuthentication` that use hashicorp vault provider authenticated using root token.
Fixes #5192
=> fix: safely parse renewable field from vault response

CHANGELOG.md, pkg/scaling/resolver/hashicorpvault_handler.go, pkg/scaling/resolver/hashicorpvault_handler_test.go
=> Add unit tests to hashicorpvault handler

CHANGELOG.md, pkg/metricsservice/client.go, pkg/scalers/external_scaler.go, pkg/scalers/external_scaler_test.go, pkg/scalers/liiklus_scaler.go
Use Client-side grpc round-robin load balancing to better spread the load when using the external scaler;
**Scenario A:**
keda operator makes a grpc call to a Service with a clusterIP. There's only 1 clusterIP. This PR won't affect this setup. Load balancing (within k8s/iptables) only happens when new connections or a connection failure. Requests are hitting the same underlying pod; Users should migrate to headless service.
**Scenario B:**
Keda operator makes a grpc call to a headless service & DNS randomizes the pod IP order. load balancing happens whenever there's a connection failure or if the server set a MaxConnectionAge, otherwise 1 pod is going to be receiving the all of the load. This PR fixes this
**Scenario C:**
Keda operator makes a grpc call to a headless service & DNS doesn't …
=> General: use client-side round-robin load balancing for grpc

CHANGELOG.md, pkg/scalers/aws_common.go
AWS session token authentication was inadvertently broken in a refactor of AWS auth handling. Restoring support for session tokens. This fixes a regression that broke the feature introduced in #2573.
Fixes #5156
=> Fix AWS session token support

.golangci.yml
update the depguard linter in .golangci so that linter is enabled but the specific rule that is troublesome is disabled.
Fixes: #4980
=> depguard linter update to rule deny

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_webhook.go, apis/keda/v1alpha1/scaledobject_webhook_test.go, controllers/keda/hpa.go, controllers/keda/scaledobject_controller.go
Validates replica counts with the validating webhook to ensure users dont misconfigure this setting when creating/updating scaledObjects;
also moved the validation logic to `v1alpha1` so that it could be reused in the controller & webhook 
Fixes https://github.com/kedacore/keda/issues/5288
=> General: validate replica counts when creating scaled objects

CHANGELOG.md, go.mod, go.sum, pkg/scalers/scaler.go, pkg/scalers/scaler_test.go, vendor/github.com/spf13/cast/.gitignore, vendor/github.com/spf13/cast/.travis.yml, vendor/github.com/spf13/cast/LICENSE, vendor/github.com/spf13/cast/Makefile, vendor/github.com/spf13/cast/README.md, vendor/github.com/spf13/cast/cast.go, vendor/github.com/spf13/cast/caste.go, vendor/modules.txt
Hi team,
As mentioned in the reply https://github.com/kedacore/keda/pull/5228#issuecomment-1868382916, I created this PR to recover dropped commits when rebasing. This commit would enable us to take in value of any type and convert to any other type
Relates to https://github.com/kedacore/keda/pull/5228 and https://github.com/kedacore/keda/issues/5037
=> Recover dropped commit utility function from `pkg/scalers/scaler.go`

controllers/keda/scaledobject_controller.go
[As the OP reported by Slack](https://kubernetes.slack.com/archives/CKZJ36A5D/p1702842214573499), during the migration process from v2.8 to v2.12, `.status.scaleTargetGVKR` has become inconsistent and KEDA didn't reconcile it but shows an error related with missing status files. 
This PR adds a check to validate the section and reconcile it in case of mismatch
=> fix: Reconcile SO's status.GVKR if there is any mismatch

CHANGELOG.md, Dockerfile, Dockerfile.adapter, Dockerfile.webhooks
Add build cache for incremental builds.
As per this [guide](https://www.docker.com/blog/containerize-your-go-developer-environment-part-2/) we get significant performance boost for incremental builds.
Since the docker files are already in one place, I suspect that the cache is being shared. Anyway we will get a huge performance boost while building locally. Personal observations show around 5x improvements for minute changes although this may vary.
Relates to #5313
=> Improve docker image build time through caches

apis/keda/v1alpha1/scaledobject_webhook.go
The webhook's `isRemovingFinalizer` func should check whether the change is **less** finalizers, obviously, and not specifically check whether the old Scaledobject has **exactly** 1 finalizer AND the new Scaled object has exactly 0.
This is to fix a use case in which ArgoCD performs cascading deletion which translates to a `foregroundDeletion` finalizer being added to the object, causing the current webhook implementation enter a loop of update-validate ("if not isRemovingFinalizer then update") instead of proceeding with deletion.
=> Fix Finalization when other finalizers are in place

CHANGELOG.md, pkg/scalers/gcp_cloud_tasks_scaler.go, pkg/scalers/gcp_stackdriver_client.go, pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_stackdriver_scaler_test.go
Context: it's pretty common to see metric that have no value during some period that can be interpretate by 0.
So this pulling request adding an optional metadata `valueIfNull`. This value (if not empty) that will be used if there is no timeseries return by the gcp monitoring query.
Fixes #
Relates to #
https://github.com/kedacore/keda-docs/pull/1285
=> feat(gcp-stackdriver): handling value if no timeseries is return

CHANGELOG.md, pkg/scalers/azure/azure_eventhub_checkpoint.go, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/azure_eventhub_scaler_test.go
This PR improves the Event Hub unprocessed event count calculation to prevent negative and large values.
There are two issues in the current implementation:
1. Stale partition runtime information results in very large values:
The scaling calculation uses the **SequenceNumber** from the partition runtime information and the checkpoint store.
Partition information could be stale compared to the checkpoint, for example when the partition runtime information is **10** and the checkpoint is **15**. This should result in **0** and not in **9223372036854775802**.
2. When the sum of all unprocessed events per partition is greater than the Int64 max value the result is negative:
When there are a lot of unprocessed events (mostly caused by the first issue), the sum of all unprocessed events per …
=> Improve Azure Event Hub scaling

controllers/keda/scaledobject_controller.go, pkg/eventemitter/cloudevent_http_handler.go, pkg/eventemitter/eventemitter.go, pkg/eventemitter/eventtypes.go, tests/internals/cloudevent_source/cloudevent_source_test.go
Update CloudEventType to correct format
Fixes (https://github.com/kedacore/keda/issues/3533)
=> Fix: Update CloudEventType to correct format

CHANGELOG.md, pkg/scaling/modifiers/formula.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_test.go
Fixes https://github.com/kedacore/keda/issues/5276
=> feat: Request all ScaledObject/ScaledJob triggers in parallel

.github/stale.yml
Automatically close stale PRs to aim for 0 open PRs
=> chore: Automatically close stale PRs

CHANGELOG.md, pkg/scalers/apache_kafka_scaler_test.go, pkg/scalers/kafka_scaler_test.go
Hi team,
I'm adding a new test case from my investigation [here](https://github.com/kedacore/keda/issues/5354#issuecomment-1883974677).
Relates to https://github.com/kedacore/keda/issues/5354
=> chore: add large lag threshold test for Kafka scalers

pkg/scalers/nats_jetstream_scaler_test.go
=> chore: fix jetstream flaky test

.github/workflows/pr-welcome.yml
PR bot fails due to mixing action triggers and it needs to consider the event trigger types.
Example: https://github.com/kedacore/keda/actions/runs/7527912865/job/20489030768
=> fix: PR bot fails due to mixing action triggers

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Preparing changelog and bug template for 2.13.0 release
Relates to https://github.com/kedacore/keda/issues/5275
=> docs: Changelog & bug template for 2.13.0 release

.github/workflows/pr-welcome.yml
Tweak PR bot logic further to be more precise.
=> chore: Tweak PR bot logic

CHANGELOG.md, pkg/metricscollector/metricscollectors.go, pkg/metricscollector/opentelemetry.go, pkg/metricscollector/prommetrics.go, pkg/scaling/scale_handler.go, tests/sequential/opentelemetry_metrics/opentelemetry_metrics_test.go, tests/sequential/prometheus_metrics/prometheus_metrics_test.go
Fixes https://github.com/kedacore/keda/issues/4798
Relates to https://github.com/kedacore/keda-docs/pull/1263
=> Expose prometheus metrics for ScaledJob resources

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go, tests/scalers/azure/azure_pipelines_aad_wi/azure_pipelines_aad_wi_test.go
Support of PodIdentityProvider for azure pipelines scaler.
(https://github.com/kedacore/governance/blob/main/SCALERS.md)
Fixes #
- ([#5013](https://github.com/kedacore/keda/issues/5013))
Relates to #
- doc [#1206](https://github.com/kedacore/keda-docs/pull/1206)
=> ADD support for PodIdentityProvider config in azure pipeline trigger

pkg/scaling/resolver/aws_secretmanager_handler.go, pkg/scaling/resolver/scale_resolvers.go
Relates to https://github.com/kedacore/keda/issues/5385
=> fix: AWS EKS doesn't fail if missing annotation

.github/ISSUE_TEMPLATE/4_release_tracker.md
Document a reminder about dependency version bumps before releases in the release tracker issue template.
=> doc: remind about dependency version bumps before releases

ROADMAP.md
Introduce KEDA v2.13 and estimate v2.16 in roadmap.
Relates to https://github.com/kedacore/keda/issues/5275
=> chore: Introduce KEDA v2.13 and estimate v2.16 in roadmap

CHANGELOG.md
Improve new features in v2.13.0 changelog
Relates to https://github.com/kedacore/keda/issues/5275
=> chore: Improve new features in v2.13.0 changelog

CHANGELOG.md, pkg/scalers/aws/aws_sigv4.go
Fixes https://github.com/kedacore/keda/issues/5419
=> fix(prometheus-scaler): AWS signv4 parses region if provided

Makefile
Fixes #
Relates to #
During dive deep onto build file, I found a small typo.
=> Fix typo on makefile

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_webhook.go
all in the title :)
intending to merge after 2.13.0 release so keeping as draft for now
Fixes #5397
=> chore: minor refactor to reduce copy/paste code in ScaledObject webhook

CHANGELOG.md, pkg/scalers/scaler.go, pkg/scalers/scaler_test.go
From the [slack discussion](https://kubernetes.slack.com/archives/C01JGDP8MB8/p1705413854296079?thread_ts=1705333570.247929&cid=C01JGDP8MB8), we should make some improvements to the `getParameterFromConfigV2` util function to make it more readable.
I create a new PR instead of adding on to  https://github.com/kedacore/keda/pull/5319 as I want to make this change modular, just showcasing the alternative without refactoring hundreds of lines on the other PR.
How we use the function would be something like 
```golang
getParameterFromConfigV2(
&scalersconfig.ScalerConfig{TriggerMetadata: testData.metadata, AuthParams: testData.authParams, ResolvedEnv: testData.resolvedEnv},
testData.parameter,
testData.targetType,
UseMetadata(testData.useMetadata), …
```
=> Make improvement to `getParameterFromConfigV2`

CHANGELOG.md, pkg/scalers/gcp/gcp_stackdriver_client.go, pkg/scalers/gcp/gcp_stackdriver_client_test.go, pkg/scalers/gcp_cloud_tasks_scaler.go, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_stackdriver_scaler.go
Before changes in v2.13 related with GCP client, the time horizon for queries was 2m. We changed it by mistake and this PR restores the previous behaviour.
As customizing the value could make sense for different scenarios, I've created another issue to track supporting it (for next version): https://github.com/kedacore/keda/issues/5453
Fixes https://github.com/kedacore/keda/issues/5429
Fixes https://github.com/kedacore/keda/issues/5448
=> fix(gcp scalers): Restore previous time horizon to fix missing metrics and properly close the connecctions

.github/ISSUE_TEMPLATE/4_release_tracker.md, RELEASE-PROCESS.md
=> add KEDA OLM release tracker step

config/samples/keda_v1alpha1_triggerauthentication.yaml, pkg/fallback/fallback_test.go, pkg/metricscollector/opentelemetry.go, pkg/metricscollector/prommetrics.go
=> typo: fix some typo

Makefile
Add explicit steps to initialize go mod in building guide
Fixes #5477 
Relates to #
=> Add explicit steps to initialize go mod in building guide

CHANGELOG.md, apis/keda/v1alpha1/triggerauthentication_types.go, apis/keda/v1alpha1/triggerauthentication_webhook.go, apis/keda/v1alpha1/triggerauthentication_webhook_test.go, apis/keda/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/keda.sh_clustertriggerauthentications.yaml, config/crd/bases/keda.sh_triggerauthentications.yaml, pkg/scalers/azure/azure_aad_workload_identity.go, pkg/scalers/azure/azure_app_insights.go, pkg/scalers/azure/azure_azidentity_chain.go, pkg/scalers/azure/azure_data_explorer.go, pkg/scalers/azure/azure_eventhub.go, pkg/scalers/azure/azure_managed_prometheus_http_round_tripper.go, pkg/scalers/azure/azure_monitor.go, pkg/scalers/azure/azure_storage.go, pkg/scalers/azure_log_analytics_scaler.go, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/rabbitmq_scaler.go, pkg/scaling/resolver/aws_secretmanager_handler.go, pkg/scaling/resolver/azure_keyvault_handler.go, pkg/scaling/resolver/scale_resolvers.go
Enable cross-tenant and cross-cloud authentication when using the `azure-workload` PodIdentityProvider within TriggerAuthentication.
Fixes #5441 
Relates to #
- keda-docs PR [#1320](https://github.com/kedacore/keda-docs/pull/1320)
=> Add support for cross tenant authentication azure workload identity TriggerAuthentication 

CHANGELOG.md, tests/utils/cleanup_test.go
If running e2e tests without `ENABLE_OPENTELEMETRY=true`, the tests fail during teardown when it tries to remove opentelemetry-related test items. This PR skips the removal when the setup was skipped.
Relates to #5375, #5436
=> Fix e2e test in non-opentelemetry case

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
The current GSSAPI configuration for Kafka scaler has a hard coded service name. The service name can be different in some Kafka configurations, hence exposing it to be configurable. 
Fixes [#5474](https://github.com/kedacore/keda/issues/5474)
=> Expose GSSAPI Service name configuration of Kafka Scaler

.devcontainer/Dockerfile
[golang.org/x/tools/cmd/guru is deprecated](https://pkg.go.dev/golang.org/x/tools/cmd/guru@v0.1.1-deprecated) and raises error during devcontainer generation
=> fix: Remove deprecated dependency from devcontainer's Dockerfile

CHANGELOG.md, tests/helper/helper.go, tests/utils/cleanup_test.go, tests/utils/setup_test.go
Allow the test setup to skip the installation of KEDA and/or Kafka so that tests can run even if they were installed via other methods, such as OLM operators.
=> chore: Add more granular control to E2E test setup

apis/keda/v1alpha1/triggerauthentication_types.go, config/crd/bases/keda.sh_clustertriggerauthentications.yaml, config/crd/bases/keda.sh_triggerauthentications.yaml
As a user reported in helm chart repo, `none` is a valid value (although it's the default value "by omission") but the CRDs don't it
=> fix: TriggerAuthentication.podIdentity validation allows 'none'

CHANGELOG.md, pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go
I added a scheme field to support the SRV record in this PR.
If it is not set, the default value is `mongodb`.
(https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
Fixes #5544
Relates to [keda-docs #1326](https://github.com/kedacore/keda-docs/pull/1326)
=> MongoDB Scaler - Scheme field support

CHANGELOG.md, pkg/scaling/scale_handler.go
=> Fix: Prometheus error metrics are correctly exposed

CHANGELOG.md, pkg/scalers/newrelic_scaler.go
Handle empty results set returned by New Relic query executor.
Fixes #5619
=> fix: consider empty results set from new relic

CHANGELOG.md, cmd/operator/main.go, pkg/metricsservice/client.go, pkg/metricsservice/server.go, vendor/google.golang.org/grpc/health/client.go, vendor/google.golang.org/grpc/health/logging.go, vendor/google.golang.org/grpc/health/server.go, vendor/modules.txt
This PR adds a GRPC healthcheck server to the operator and returns `SERVING` status only if the server is the leader elected instance.
To do this, I refactored the GRPCServer class to be a non-leader elected runnable (returning `false` for `NeedsLeaderElection`) and instead listen to the `Elected` channel from the manager in the select statement to set the server state to serving.
This also needed the addition client-side health checking to ensure that the GRPC client checks the health of the endpoint its connected to and ensure it is connected to the serving client. Additionally, this required changing the load balancing behavior of the client from `pick_first` to `round_robin` so that the client internally watches the state of the health checks and selects a server that is in the …
=> Add GRPC Healthchecks

CHANGELOG.md, pkg/scalers/gcp/gcp_stackdriver_client.go
Add new alignment parameters 'rate' and 'count' for GCP Stackdriver Scaler alignment
Fixes #
Relates to #5633
=> feat: Add new alignment parameters 'rate' and 'count' for GCP Stackdriver Scaler

CHANGELOG.md, pkg/scalers/azure/azure_eventhub_checkpoint.go, pkg/scalers/azure/azure_eventhub_test.go, pkg/scalers/azure_eventhub_scaler.go, pkg/scalers/azure_eventhub_scaler_test.go, vendor/github.com/Azure/azure-event-hubs-go/v3/amqp_mgmt.go
This PR removes or replaces uses of Event Hub offsets, as this is no longer a supported metric to use for determining consumer locations within a partition.
Fixes #5574
Relates to https://github.com/Azure/azure-sdk-for-net/issues/42409
=> Event Hub Scaler: Remove or replace usages of Event Hub offsets

CHANGELOG.md, pkg/scalers/rabbitmq_scaler.go
Update RabbitMQ Scaler to support TLS Configuration for HTTP Connections
- N/A When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- N/A A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- N/A A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
Fixes #5668
=> Update RabbitMQ Scaler to support TLS Configuration for HTTP Connections

CHANGELOG.md, pkg/scalers/stan_scaler.go, pkg/scalers/stan_scaler_test.go
Add tls authentication for NATS Streaming scaler.
Fixes #2296
=> add tls authentication for NATS Streaming

apis/keda/v1alpha1/scaledobject_types.go, pkg/eventemitter/eventemitter.go, pkg/scalers/datadog_scaler.go
fix function names in comment
Fixes #
Relates to #
=> chore: fix function names in comment

CHANGELOG.md, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_pubsub_scaler_test.go
- [] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
Fixes #5693 
Relates to https://github.com/kedacore/keda-docs/pull/1377
=> Resolve Pub/Sub resources from scale target's environment

tests/utils/helper/helper.go
There is a potential breaking change that requires this change during the dep installation (just for testing, nothing to users)
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0880-to-0890
=> fix: Use correct otel-collector distro

CHANGELOG.md, go.mod, go.sum, pkg/scalers/kafka/kafka_scaler_oauth_token_provider.go, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go, pkg/scaling/scalers_builder.go, vendor/github.com/aws/aws-msk-iam-sasl-signer-go/LICENSE, vendor/github.com/aws/aws-msk-iam-sasl-signer-go/NOTICE, vendor/github.com/aws/aws-msk-iam-sasl-signer-go/signer/msk_auth_token_provider.go, vendor/github.com/aws/aws-msk-iam-sasl-signer-go/signer/version.go, vendor/modules.txt
Following the discussion in #5531 and #5540, this adds the support for SASL OAuthBearer with MSK token provider to the Kafka scaler using sarama library.
I've added two new fields, `saslTokenProvider` (authParams or TriggerMetadata) and `awsRegion` (TriggerMetadata).
It is currently functional, to make it work, here's an example:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
name: keda-kafka-secrets
namespace: default
data:
sasl: "oauthbearer"
saslTokenProvider: "aws_msk_iam"
tls: "enable"
---
kind: TriggerAuthentication
metadata:
name: keda-trigger-auth-kafka-credential
namespace: default
spec:
secretTargetRef:
- parameter: sasl
name: keda-kafka-secrets
key: sasl
- parameter: saslTokenProvider
name: keda-kafka-secrets
key: saslTokenProvider
- parameter: …
```
=> Add AWS MSK IAM authentication to Kafka scaler

CHANGELOG.md, pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go
This commit fixs issue #5760. where OP was facing problem with +srv schema
Fixes #5760
=> fix: `+srv` mongodb url scheme parsing bug

CHANGELOG.md, pkg/scalers/authentication/authentication_types.go, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go, pkg/scalers/scalersconfig/typed_config.go, pkg/scalers/scalersconfig/typed_config_test.go
Various scaler configurations are inconsistent in implementation as discussed in https://github.com/kedacore/keda/issues/5037. There has been a great effort in improving the situation with `getParameterFromConfigV2()` in https://github.com/kedacore/keda/pull/5228 (with further enhancements in https://github.com/kedacore/keda/pull/5319 and https://github.com/kedacore/keda/pull/5314).
There are likely always going to be some situations that require imperative parsing of the provided configs and the helper `getParameterFromConfigV2()`, but for the majority of cases, I believe we can implement an even more generic, more convenient and declarative algorithm, similar for example to the API of well known `json.Unmarshal()`.
My desired goal is to allow each scaler to define the configuration …
=> Declarative scaler config

CHANGELOG.md, pkg/scalers/apache_kafka_scaler.go, pkg/scalers/kafka_scaler.go, tests/scalers/apache_kafka/apache_kafka_test.go, tests/scalers/kafka/kafka_test.go
Fixes https://github.com/kedacore/keda/issues/4910
=> Add logic to scale to zero on invalid offset even with earliest offsetResetPolicy

CHANGELOG.md, pkg/scalers/activemq_scaler.go, pkg/scalers/activemq_scaler_test.go
Refactor activemq scaler config using declarative parser from https://github.com/kedacore/keda/pull/5676
Relates to 
https://github.com/kedacore/keda/issues/5797
=> Refactor ActiveMQ scaler config

.github/workflows/template-arm64-smoke-tests.yml, .github/workflows/template-versions-smoke-tests.yml, CHANGELOG.md
Run e2e tests against Kubernetes v1.28-v1.30.
Fixes https://github.com/kedacore/keda/issues/5828
=> test: Run e2e tests against Kubernetes v1.28-v1.30

Makefile
https://github.com/kedacore/keda/pull/5783 has introduced validation on e2e trigger regex. In the `Makefile` label, it executes go with invalid tag resulting in failed e2e tests
* https://github.com/kedacore/keda/pull/5804#issuecomment-2134660847
```
$ make e2e-regex-check
go run -tags e2e-regex ./tests/run-all.go regex-check
package command-line-arguments
imports github.com/kedacore/keda/v2/tests/helper: build constraints exclude all Go files in /home/wozy/projects/go/src/github.com/kedacore/keda/tests/helper
make: *** [Makefile:103: e2e-regex-check] Error
```
Fixes #5783
=> fix: e2e test regex check tag

pkg/scalers/apache_kafka_scaler.go, pkg/scalers/apache_kafka_scaler_test.go, pkg/scalers/scalersconfig/typed_config.go, pkg/scalers/scalersconfig/typed_config_test.go
Refactor Apache Kafka scaler config using declarative parser from https://github.com/kedacore/keda/pull/5676. This PR also introduces a new field tag option `range`. This tag helps with config options that don't want to enumerate all of the values but instead generate as range (or multiple ranges) bounded by from and to (or multiple from's and to's).
Example usage:
https://github.com/kedacore/keda/blob/f905adda2df16b23f58333b3154273cbfaf0d3b6/pkg/scalers/scalersconfig/typed_config_test.go#L523-L537
=> Refactor Apache Kafka scaler config

CHANGELOG.md, cmd/operator/main.go, pkg/util/certificates.go, pkg/util/certificates_test.go
Add `--ca-dir` flag to KEDA operator to specify directories with CA certificates for scalers to authenticate TLS connections (defaults to /custom/ca)
Fixes #5860
See https://github.com/kedacore/charts/pull/650
See https://github.com/kedacore/keda-docs/pull/1402
=> Allow CA dirs to be specified beyond /custom/ca/

CHANGELOG.md, pkg/fallback/fallback.go
Minor perf improvement, let's reduce the load.
Relates to #5624
=> chore: fallback - patch ScaledObject.Status only when there is a difference

CHANGELOG.md, config/default/kustomization.yaml, config/minimal/kustomization.yaml, config/rbac/kustomization.yaml
Signed-off-by: Daniel Wright <dan@dwright.io>
Remove `commonLabels` in favour of the more modern kustomize approach.
Fixes #5887
=> remove kustomize commonLabels

CHANGELOG.md, pkg/scalers/cassandra_scaler.go, pkg/scalers/cassandra_scaler_test.go
=> Add support for cassandra tls

.github/workflows/pr-validation.yml, CHANGELOG.md, config/samples/keda_v1alpha1_clustertriggerauthentication.yaml, config/samples/keda_v1alpha1_triggerauthentication.yaml, config/samples/kustomization.yaml, hack/verify-manifests.sh
This PR has three parts:
1. Add additional PR checks to make sure that every CRD is listed in the CRD `kustomize.yaml` file and that every CRD also has a sample CR for each of its API versions and is similarly listed in the `kustomize.yaml` file for sample CR files.
2. Add missing sample CRs, CRDs and references.
3. Update existing sample CR for `triggerauthentication` which had the old API group of `keda.k8s.io` instead of the new `keda.sh`
Fixes #5920
=> Add additional manifest checks to detect missing CRDs & CRs

CHANGELOG.md, pkg/scalers/mysql_scaler.go, pkg/scalers/mysql_scaler_test.go, pkg/scalers/scaler.go
Fixes #5883 
Relates to #5883 
Docs PR: https://github.com/kedacore/keda-docs/pull/1419
=> Add username from env mysql scaler

pkg/scalers/rabbitmq_scaler.go
It should return the error if the TLS configuration returns an error, to prevent further nil pointer dereference on the `conn` variable.
=> Return the error if TLS config fails in Rabbitmq scaler

CHANGELOG.md, pkg/scalers/ibmmq_scaler.go, pkg/scalers/ibmmq_scaler_test.go
IBM MQ scaler does not support authentication with TLS certs. This contributing adds support to enable authentication with TLS certs within the existing IBM MQ scaler by extending it, possibly with additional optional parameters.
Currently, MQ appliance is expecting the Basic Auth credentials as well along with certificates. The change is therefore made in such a way that Basic Auth remains necessary if you also provide a TLS certificate.
The change has been tested against our own IBM MQ appliances.
Fixes #5974 
Docs: [1433](https://github.com/kedacore/keda-docs/pull/1433)
=> feat: add TLS support for IBM MQ scaler

CHANGELOG.md, pkg/scalers/gcp/gcp_stackdriver_client.go, pkg/scalers/gcp_pubsub_scaler.go
Added an optional valueIfNull configuration value to the GCP Pub/Sub as also found in the older GCP Stackdriver scaler. This allows for a default fallback value when GCP returns no value for a given metric. This prevents excessive error logging especially when using multiple pubsub scalers with low subscription traffic. 
Relates to #
https://github.com/kedacore/keda/issues/5896
[Documentation update](https://github.com/kedacore/keda-docs/pull/1410)
=> feat: GCP Pub/Sub scaler add configurable fallback value when no metric value found

tests/internals/scaled_job_validation/scaled_job_validation_test.go
This scaledjob test template was missing its namespace.
- It doesn't generally matter for the test -- the test is just checking if the webhook works. It doesn't care where the scaledjob ends up
- It _does_ matter though if you run this test in a more restrictive environment where you can't write to the default namespace  --  it fails with a namespace-related creation error instead of the expected _no triggers defined in the ScaledObject/ScaledJob_ error 
This just adds the namespace to the template so it's consistent with the other ones in the test suite.
=> Add missing TestNamespace to ScaledJob validation test template

Makefile, pkg/util/welcome.go
Add missing changes to officially support v1.30
- Updated welcome messages
- update envtests
Fixes https://github.com/kedacore/keda/issues/5828
=> chore: Update supported versions

CHANGELOG.md, pkg/scalers/azure_queue_scaler.go
This PR is an attempt to solve https://github.com/kedacore/keda/issues/4478
It adds a new configuration option `queueLengthStrategy` to the Azure Storage Queue scaler, where you can set the value of `default` or `visibleonly`.
`default`: Considers both visible and invisible messages.
`visibleonly`: Uses Peek to count only visible messages. If the count of visible messages is 32 or higher, it falls back to the default strategy, counting both visible and invisible messages.
`visibleonly` will, in practice, use the previous behaviour, as before https://github.com/kedacore/keda/pull/4003 was merged.
Docs PR: https://github.com/kedacore/keda-docs/pull/1406.
I've created this change to the best of my ability. However, it hasn't been tested. I would appreciate if someone could help with testing, …
=> Update GetAzureQueueLength in azure queue scaler, to support different queue length strategies.

.github/workflows/pr-e2e.yml
In order to execute the e2e tests with go 1.22 we need to use 1.22 during the execution
=> chore: Update e2e image

CHANGELOG.md, cmd/adapter/main.go
keda metrics adapter doesn't actually use leader election, but the code reads in unused environment variables that configure leader election. This commit is to remove that. 
Relates to https://github.com/kedacore/keda/issues/5959, https://github.com/kedacore/keda-docs/pull/1434
=> remove unused leader election parameters of metrics adapter

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/6002
=> chore: Prepare main branch for v2.14.1

CHANGELOG.md, pkg/scalers/prometheus_scaler.go, pkg/scalers/prometheus_scaler_test.go
Fixes https://github.com/kedacore/keda/issues/5538
=> Remove deprecated cortexOrgId in prometheus scaler

CHANGELOG.md, pkg/provider/provider.go
Here in the the KedaProvider https://github.com/openshift/kedacore-keda/blob/be1b1737c53f708a62a6a7386b27f5f208bf7094/pkg/provider/provider.go#L92. The GetExternalMetric function can return nil,nil in the wait for the connection to be ready since it does not reassign the err variable.
The nil,nil gets dereferenced here: https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/1e7ed5df24ef39898861260b002d9400f2d09300/pkg/registry/external_metrics/reststorage.go#L87 and hence panics in the code.
This fix reassigns the `err` so that an invalid `nil,nil` return can not happen. 
Fixes #6009
=> fix: reassign err to prevent invalid return in KedaProvider `GetExternalMetric`

tests/helper/helper.go, tests/scalers/nats_jetstream/nats_jetstream_cluster/nats_jetstream_cluster_test.go
=> fix: Jetstream e2e test uses the right config value

.golangci.yml
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
```
=> chore: golangci-lint: `run.skip-dirs` is deprecated

CHANGELOG.md, pkg/scaling/resolver/hashicorpvault_handler.go
Read the issue to get the full context 😄 
Fixes https://github.com/kedacore/keda/issues/6028
=> fix: Hashicorp Vault PKI doesn't fail with due to KeyPair mismatch

.github/workflows/pr-e2e.yml
=> chore: Use CNCF runner for e2e tests

CHANGELOG.md, pkg/scalers/nats_jetstream_scaler.go, pkg/scalers/nats_jetstream_scaler_test.go, tests/scalers/nats_jetstream/helper/nats_helper.go, tests/scalers/nats_jetstream/nats_jetstream_cluster/nats_jetstream_cluster_test.go
=> fix: JetSteam scaler detects leader changes correctly

tests/scalers/azure/azure_event_hub_blob_metadata_wi/azure_event_hub_blob_metadata_wi_test.go, tests/scalers/azure/azure_event_hub_dapr_wi/azure_event_hub_dapr_wi_test.go
This PR adds pod identity e2e tests for more use cases
Fixes #
Relates to #
=> chore: Improve azure e2e coverage

pkg/scalers/cron_scaler.go
=> Refactor cron scaler config

CHANGELOG.md, pkg/scalers/pulsar_scaler.go, pkg/scalers/pulsar_scaler_test.go
This commit removes the deprecated trigger name `msgBacklog` in Pulsar scaler. `msgBacklogThreshold` should be used instead.
Fixes #6059
(The original issue was intended to introduce a scaler to non-persistent Pulsar topics. But after some research, I found out that the proposed metric is infeasible)
Relates to #
=> Pulsar: remove deprecated trigger name

CHANGELOG.md, apis/eventing/v1alpha1/cloudevent_types.go, cmd/operator/main.go, config/crd/bases/eventing.keda.sh_cloudeventsources.yaml, config/crd/bases/eventing.keda.sh_clustercloudeventsources.yaml, controllers/keda/clustertriggerauthentication_controller.go, controllers/keda/triggerauthentication_controller.go, controllers/keda/util/finalizer.go, pkg/common/message/message.go, pkg/eventreason/eventreason.go, tests/internals/events/events_test.go
Provide ClusterCloudEventSource around the management of TriggerAuthentication/ClusterTriggerAuthentication resources
Relates to # **https://github.com/kedacore/keda/issues/3524**
=> Provide ClusterCloudEventSource around the management of TriggerAuthentication/ClusterTriggerAuthentication resources

BUILD.md
Remote Containers in VS code are called `Dev Containers`. Updated the BUILD.md to reflect that nuance. Particularly helpful for the command palate walkthrough of setting up Dev Container during local dev work.
Fixes #
Relates to #
=> Update Remote Container references to Dev Containers

tests/internals/initial_delay_cooldownperiod/initial_delay_cooldownperiod_test.go
I think that after moving the cron scaler to the declarative parsing, 0 is treated as error and this test failed because during errors, the scaling to 0 doesn't apply. This PR changes the scaler to other that returns 0 without errors
=> fix: Initial delay e2e test use a scaler without failures

pkg/scalers/elasticsearch_scaler.go, pkg/scalers/elasticsearch_scaler_test.go, pkg/scalers/kafka_scaler.go, pkg/scalers/scalersconfig/typed_config.go, pkg/scalers/scalersconfig/typed_config_test.go
- Because i deleted `const defaultUnsafeSsl = false` in the `elasticseach_scaler.go`, `kafka_scaler.go` is giving error `pkg/scalers/kafka_scaler.go:354:19: undefined: defaultUnsafeSsl`. That's why I added the `const` in `kafka_scaler.go`.
- Extra check if both `username` and `password` are provided when `addresses` is used (also test added).
- Made a new `splitWithSeparator` function so the separator is configurable.
- The documentation states that the field index is comma separated. In the code it is semicolon. There is a separate PR created in the keda-docs repo ([1465](https://github.com/kedacore/keda-docs/pull/1465)).
Docs: …
=> Refactor elasticsearch scaler config

pkg/scalers/aws_dynamodb_scaler_test.go, pkg/scalers/scalersconfig/typed_config.go, pkg/scalers/scalersconfig/typed_config_test.go
@rickbrouwer noticed that https://github.com/kedacore/keda/pull/5997 introduced a small side effect with how `TypedConfig` returns errors for missing trigger metadata parameter names.
```
error parsing XYZ metadata: unable to set param ["abc"] value
```
This PR improves the readability of the error by going back to
```
error parsing XYZ metadata: unable to set param "abc" value
```
and alternatively listing multiple parameter names as just comma-separated
```
error parsing XYZ metadata: unable to set param "Abc,abc" value
```
=> scaler typed config: simplify missing parameter error

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
This PR adds the ability to configure Basic Authentication for the Selenium Grid Scaler by setting the username and password directly, instead of embedding them in the URL. This enhances security and flexibility when configuring authentication for the scaler.
Fixes #
Relates to #
=> Add Username and Password for Selenium Grid Basic Auth

.github/workflows/auto-add-issues-to-project.yml, .github/workflows/fossa.yml, .github/workflows/main-build.yml, .github/workflows/pr-e2e-checker.yml, .github/workflows/pr-e2e-creator.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/pr-welcome.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/static-analysis-semgrep.yml, .github/workflows/template-arm64-smoke-tests.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-versions-smoke-tests.yml, .github/workflows/v1-build.yml
=> Use CNCF Runners

.github/workflows/main-build.yml, .github/workflows/release-build.yml
ARM64 machines are failing with multi-platform docker build. I thope that AMD64 machines do it better 🤞
=> fix: Use AMD64 machine to generate docker images

.github/workflows/pr-e2e.yml
CNCF runners are missing gh:
```
/home/runner/_work/_temp/3f017fe0-a33c-4dc3-bc3e-aae743e5300e.sh: line 8: gh: command not found
```
=> e2e test checker - use keda-tools container for dependencies (gh)

.github/workflows/auto-add-issues-to-project.yml, .github/workflows/fossa.yml, .github/workflows/main-build.yml, .github/workflows/pr-e2e-checker.yml, .github/workflows/pr-e2e-creator.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/pr-welcome.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/static-analysis-semgrep.yml, .github/workflows/template-arm64-smoke-tests.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-versions-smoke-tests.yml, .github/workflows/v1-build.yml
CNCF Runners aren't ready, so this PR Removes all the usages of them
=> fix: Revert changes to not use CNCF runners

.github/workflows/template-trivy-scan.yml
=> fix: Use the the GH TOKEN to pull trivy's DB

.github/workflows/template-trivy-scan.yml
https://github.com/orgs/kedacore/packages/container/package/trivy-db
for now, synced manually by:
```
$ oras pull ghcr.io/aquasecurity/trivy-db:2
$ oras push ghcr.io/kedacore/trivy-db:2
```
I will followup with some automation later
=> chore: use kedacore cached trivy image

.github/workflows/template-trivy-scan.yml
=> fix: Trivy template doesn't have duplicated env

pkg/scalers/cpu_memory_scaler.go, pkg/scalers/cpu_memory_scaler_test.go
- The parameter `type` is already from release 2.7 deprecated. I think it's time to announce the removal  and remove the deprecated code in version 2.18.
Docs: https://github.com/kedacore/keda-docs/pull/1484
=> Refactor CPU/Memory scaler config

CHANGELOG.md, pkg/scalers/kafka_scaler.go, pkg/scalers/kafka_scaler_test.go
This:
- adds a `kerberosDisableFAST` field to the kafka scaler metadata, which can be used to disable sarama's/gokrb5's FAST negotiation for kerberos connections
- populates said field from a `kerberosDisableFAST` field in the AuthConfig 
Which will let a user disable FAST as part of their Kerberos configuration.
I'm not attached to any of the naming here, I just want the plumbing, right now we just can't manipulate this at all. :smile: 
Fixes #6188
=> kafka: allow disabling kerberos FAST in sarama client

pkg/scalers/influxdb_scaler.go, pkg/scalers/influxdb_scaler_test.go
Refactor the scaler to match the new metadata guidelines.
Fixes #
Related: https://github.com/kedacore/keda/pull/5797
=> Refactor InfluxDB scaler config

CHANGELOG.md, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go, tests/scalers/rabbitmq/rabbitmq_helper.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp_auth/rabbitmq_queue_amqp_auth_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http_auth/rabbitmq_queue_http_auth_test.go
rabbitmq using separate username and password, supports obtaining from environment variables or obtaining from TriggerAuthentication, and remains compatible with previous usage.
Fixes #2513
Relates to https://github.com/kedacore/keda-docs/pull/1472
=> RabbitMQ: provide separate paremeters for user and password

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_webhook.go, tests/internals/scaled_object_validation/scaled_object_validation_test.go
Prevent multiple ScaledObjects managing one HPA
Fixes #6130 
Relates to #
=> Prevent multiple ScaledObjects managing one HPA

pkg/scalers/loki_scaler.go, pkg/scalers/loki_scaler_test.go, pkg/scalers/prometheus_scaler.go
- Removed some prometheus const because of error in `Static Checks`:
`
pkg/scalers/prometheus_scaler.go:29:2: const promServerAddress is unused (unused)
pkg/scalers/prometheus_scaler.go:30:2: const promQuery is unused (unused)
pkg/scalers/prometheus_scaler.go:31:2: const promQueryParameters is unused (unused)
pkg/scalers/prometheus_scaler.go:32:2: const promThreshold is unused (unused)
pkg/scalers/prometheus_scaler.go:33:2: const promActivationThreshold is unused (unused)
pkg/scalers/prometheus_scaler.go:34:2: const promNamespace is unused (unused)
pkg/scalers/prometheus_scaler.go:35:2: const promCustomHeaders is unused (unused)
pkg/scalers/prometheus_scaler.go:36:2: const ignoreNullValues is unused (unused) …
=> Refactor Loki scaler

pkg/scalers/postgresql_scaler.go, pkg/scalers/postgresql_scaler_test.go
=> Refactor postgresql scaler config

.github/workflows/pr-e2e.yml, .github/workflows/template-main-e2e-test.yml, pkg/scalers/kubernetes_workload_scaler.go, tests/helper/helper.go, tests/internals/cache_metrics/cache_metrics_test.go, tests/internals/eventemitter/azureeventgridtopic/azureeventgridtopic_test.go, tests/internals/idle_replicas/idle_replicas_test.go, tests/internals/restore_original/restore_original_test.go, tests/internals/scaled_job_validation/scaled_job_validation_test.go, tests/internals/scaling_strategies/eager_scaling_strategy_test.go, tests/internals/value_metric_type/value_metric_type_test.go, tests/run-all.go, tests/scalers/artemis/artemis_test.go, tests/scalers/azure/azure_event_hub_dapr_wi/azure_event_hub_dapr_wi_test.go, tests/scalers/azure/azure_service_bus_queue_regex/azure_service_bus_queue_regex_test.go, tests/scalers/azure/azure_service_bus_topic_regex/azure_service_bus_topic_regex_test.go, tests/scalers/elasticsearch/elasticsearch_test.go, tests/scalers/external_scaler_sj/external_scaler_sj_test.go, tests/scalers/github_runner/github_runner_test.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp/rabbitmq_queue_amqp_test.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp_auth/rabbitmq_queue_amqp_auth_test.go, tests/scalers/rabbitmq/rabbitmq_queue_amqp_vhost/rabbitmq_queue_amqp_vhost_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http/rabbitmq_queue_http_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http_aad_wi/rabbitmq_queue_http_aad_wi_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http_auth/rabbitmq_queue_http_auth_test.go, tests/scalers/rabbitmq/rabbitmq_queue_http_vhost/rabbitmq_queue_http_vhost_test.go, tests/scalers/solace/solace_test.go, tests/sequential/datadog_dca/datadog_dca_test.go, tests/utils/helper/helper.go
This PR solves:
- Small bug introduced during Kubernetes workload refactor related with using scaler as source
- Deprecation of the logging exporter in opentelemetry collector 
- Reorder the solace test to not cleanup resources not deployed yet
- Solace test use helm wait instead of sleep
- Add internal retries checking event hub message during event emiter tests
- Azure Event Hub dapr test use different namespace for regular auth and pod identity
- RabbitMQ AMQP Auth test use different namespace for regular auth and pod identity
- Increased scaling out timeouts in some test cases
- Datadog Cluster Agent e2e moved to standalone as the agent generates (datadog) metrics from other e2e tests in progress (@arapulido is checking this on their side)
- Eager scaling strategy test checks the …
=> e2e test issues solved

pkg/scalers/couchdb_scaler.go, pkg/scalers/couchdb_scaler_test.go
=> Refactor couchdb scaler

pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go
=> Refactor mongo scaler

.github/workflows/main-build.yml, .github/workflows/pr-e2e.yml, .github/workflows/release-build.yml
Currently, `GH_AUTOMATION_PAT ` has the same values as `GHCR_AUTH_PAT`, this PR unifies both envs
EDIT: I'm @JorTurFer and I didn't notice that I was logged in with the wrong account
=> chore: Use the same secret for the PAT

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go
**Azure Pipelines Scalar**
- Write log entry when Azure DevOps API Rate Limit is (nearly) reached
Fixes #6284
Not related to other PRs
=> Write log entry when Azure DevOps API Rate Limit is (nearly) reached

CHANGELOG.md, config/rbac/role.yaml, controllers/eventing/cloudeventsource_controller.go, controllers/eventing/clustercloudeventsource_controller.go, controllers/keda/clustertriggerauthentication_controller.go, controllers/keda/scaledjob_controller.go, controllers/keda/scaledobject_controller.go, controllers/keda/triggerauthentication_controller.go
According to Kubernetes documentation and various k8s security guidelines, wildcards in resource and verb entries should be avoided:
> [!WARNING]
> Using wildcards in resource and verb entries could result in overly permissive access being granted to sensitive resources. For instance, if a new resource type is added, or a new subresource is added, or a new custom verb is checked, the wildcard entry automatically grants access, which may be undesirable. The [principle of least privilege](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#least-privilege) should be employed, using specific resources and verbs to ensure only the permissions required for the workload to function correctly are applied.
Refs: 
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebin …
=> fix: Replace wildcards in RBAC objects with explicit resources and verbs

pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/azure_queue_scaler.go, pkg/scalers/azure_queue_scaler_test.go
- In #5875 the contributor indicated that he needed help with making the tests. These were not there yet, so I added them during the refactoring
=> Refactor azure queue scaler

CHANGELOG.md, pkg/scaling/cache/scalers_cache.go
To prevent unexpected accesses to the scalers inside the scalers cache, this PR adds a mutex that blocks operating over the cache meanwhile it's modified,
Fixes https://github.com/kedacore/keda/issues/6273
=> fix: Use mutex in the scaler cache to prevent concurrent refreshings

CHANGELOG.md, pkg/scalers/github_runner_scaler.go, pkg/scalers/github_runner_scaler_test.go
Add new option to not scale GitHub runner on default runner labels
- [N/A] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
Fixes #6127
Relates https://github.com/kedacore/keda-docs/pull/1492
=> feat: add support to not scale GitHub runner on default runner labels

pkg/scalers/newrelic_scaler.go, pkg/scalers/newrelic_scaler_test.go, pkg/scalers/scalersconfig/typed_config.go
- The New Relic test showed that "0" and "1" are also valid values ​​for a boolean, but TypedConfig only accepts "true" and "false". Therefore, in the `setConfigValueHelper`, the function of typed_config.go has been adjusted for boolean parsing.
=> Refactor New Relic scaler

CHANGELOG.md, controllers/keda/scaledobject_controller.go
Fixes https://github.com/kedacore/keda/issues/6321
=> fix: Paused ScaledObject count is reported correctly after operator restart

CHANGELOG.md, cmd/adapter/main.go, cmd/operator/main.go, cmd/webhooks/main.go, pkg/util/maxprocs.go
Configures automaxprocs to use the application logger instead of default console logging to maintain consistent JSON format across all log output.
output:
```
keda-admission-webhooks:
 ~/ k logs deployments.apps/keda-admission-webhooks -n keda
2024-11-15T18:39:05Z	INFO	setup	maxprocs: Updating GOMAXPROCS=1: determined from CPU quota	{"system": "automaxprocs"}
2024-11-15T18:39:05Z	INFO	setup	Starting admission webhooks
2024-11-15T18:39:05Z	INFO	setup	KEDA Version: main
2024-11-15T18:39:05Z	INFO	setup	Git Commit: c2a6df04230e1f62d335127e0a02694015c79fa6
2024-11-15T18:39:05Z	INFO	setup	Go Version: go1.23.3
2024-11-15T18:39:05Z	INFO	setup	Go OS/Arch: linux/arm64
2024-11-15T18:39:05Z	INFO	setup	Running on Kubernetes 1.30	{"version": "v1.30.0"}
2024-11-15T18:39:05Z	INFO …
```
=> fix: ensure consistent JSON log format for automaxprocs

CHANGELOG.md, pkg/scaling/executor/scale_jobs.go
Since code was missing for setting a scaledjob as ready it was stuck as unready if there ever was a problem
This is a fix for a regression in #5916
=> fix: scaledjobs stuck as not ready

CHANGELOG.md, pkg/scalers/stan_scaler.go
Deprecate the NATS Streaming Server (aka Stan)
Fixes #6362 
Docs  https://github.com/kedacore/keda-docs/pull/1503
=> Deprecate Stan scaler

.github/workflows/scorecards.yml, CHANGELOG.md, README.md, SECURITY.md
This is continuing work from #5947.
Original text from @harshitasao:
> PR to add the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action)
Related: https://github.com/kedacore/keda/issues/5913
=> Add Scorecard GitHub Action

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
> As KEDA exposes a metric to the HPA Controller, KEDA has to expose the raw value of the queue including all the jobs in-progress and pending, because it's the HPA controller the one which will calculate the right value based on the metric type (Value or AverageValue).
Selenium Grid scaler exposes the the sum of the in-progress sessions plus the pending sessions (after counting `nodeMaxSessions` to KEDA.
Fixes https://github.com/SeleniumHQ/docker-selenium/issues/2464
Relates to https://github.com/kedacore/keda/discussions/6331
=> fix: Selenium Grid scaler exposes sum of pending and ongoing sessions to KDEA

.github/workflows/auto-add-issues-to-project.yml, .github/workflows/fossa.yml, .github/workflows/main-build.yml, .github/workflows/nightly-e2e.yml, .github/workflows/pr-e2e.yml, .github/workflows/pr-validation.yml, .github/workflows/release-build.yml, .github/workflows/static-analysis-codeql.yml, .github/workflows/template-main-e2e-test.yml, .github/workflows/template-smoke-tests.yml, .github/workflows/template-trivy-scan.yml, .github/workflows/v1-build.yml
I'm fixing semgrep detections and this is one of them as not using versions pinned by commit sha is vulnerable to tampering
=> fix: Use pinned version for all the pending tasks

CHANGELOG.md, cmd/operator/main.go, pkg/certificates/certificate_manager.go
Includes a flag in the operator to the webhook patching 
Fixes #6184
=> add: enable webhook patching with flag

.github/workflows/template-trivy-scan.yml
This PR solves the issue pushing sarif report
=> fix: Add required permissions for trivy in the token

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md, pkg/scalers/azure/azure_aad_workload_identity.go
=> chore: Prepare v2.16.1

pkg/scalers/gcp_cloud_tasks_scaler.go, pkg/scalers/gcp_cloud_tasks_scaler_test.go
Refactored the GCP Cloud Tasks scaler and enhanced the unit tests for greater coverage and reliability.
Fixes #
Relates to #5797
=> refactor gcp cloud tasks scaler

apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_webhook.go, tests/internals/events/events_test.go
1. Change variableName in code or annotation.
2. Fix test case log bug.
3. upgrade crypto to v0.31.0 to pass code check in GitHub.
Fixes #
Relates to #
=> Fix testLogBug and changeSomeVariableName

CHANGELOG.md, pkg/scaling/executor/scale_scaledobjects.go
The format message is missing two verbs (or has two extra arguments) resulting in slightly broken event text
```
Warning  KEDAScaleTargetDeactivationFailed  8m14s                  keda-operator            Failed to deactivated apps/v1.Deployment default/http-server%!(EXTRA int32=1, int32=0)
```
=> fix: correct warning event text format when deactivation fails

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go, pkg/scalers/selenium_grid_scaler_test.go
When Node stereotype set `"platformName": ""` (empty), node started up and registered to Hub with converting to `"platformName": "windows"`. Similarly, the same behavior in session capabilities. This unexpected behavior impacts the scaler in counting the pending and ongoing sessions.
This issue is fixed in Grid core https://github.com/SeleniumHQ/selenium/pull/15036 (`platformName` is empty should be considered as enum ANY instead of WINDOWS). Available from 4.28.0 onwards.
The incoming request with setting capability `"platformName": "any"` or not set. It will be assigned to any Node with the stereotype `platformName: any` or not set.
So, updating the scaler condition to be aligned with the same behavior.
Fixes #
Relates to #
=> fix: Selenium Grid scaler logic on platformName is set empty or `any`

CHANGELOG.md, pkg/scalers/ibmmq_scaler.go, pkg/scalers/ibmmq_scaler_test.go
- Restructured response validation using switch statement for different HTTP status codes
- Renamed maxDepth to maxDepths for naming consistency with other depth calculation functions
- Added calculateDepth helper function
- Improved error handling in IBM MQ scaler:
If you configure something wrong, for example a small typo in the `host` param, an error will occur like:
`error inspecting IBM MQ queue depth: failed to parse response from REST call for queue MY_QUEUE.LQ`
You can easily overlook this and not know exactly what the error is.
To solve this I add a `http.StatusNotFound` that reads the `message` and presents it. This gives you a clearer message, like:
`error inspecting IBM MQ queue depth: MQWB0009E: Could not query the queue manager 'MQMGRR'.`
=> Handling StatusNotFound in IBMMQ scaler

CHANGELOG.md, pkg/scalers/redis_streams_scaler.go, pkg/scalers/redis_streams_scaler_test.go
This PR was created due to a bug found and reported as an issue #6478.
The documentation Redis Streams states that a default of 0 is allowed. In version `v2.15.1` seems that be possible.
In `v2.16` a check is applied with a refactoring where the value 0 is not allowed:
```
if r.ActivationLagCount == 0 {
err := errors.New("activationLagCount required for Redis lag")
return err
}
```
The code contains the following line:
```
return []external_metrics.ExternalMetricValue{metric}, metricCount > s.metadata.ActivationLagCount, nil
```
The second return value (the boolean) determines whether the scaler is active. This becomes `true` if `metricCount > ActivationLagCount`.
Because `ActivationLagCount` cannot be 0, this means that there must be at least 2 messages before scaling is activated. This …
=> fix(Redis Streams): Allow default value of 0 for activationLagCount

pkg/scalers/liiklus_scaler.go, pkg/scalers/liiklus_scaler_test.go
refactor liiklus scaler metadata parsing
Relates to #5797
=> refactor liklus scaler

.github/ISSUE_TEMPLATE/3_bug_report.yml, .github/workflows/template-arm64-smoke-tests.yml, .github/workflows/template-versions-smoke-tests.yml, Makefile, pkg/util/welcome.go
=> Update k8s support to 1.32

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go
This PR adds an extra option `requireAllDemandsAndIgnoreOthers` (name tbd) to the azure pipeline scaler which ensures that all demands in the scaler definition is present in the incoming job, while ignoring any other demands the job may have.
This is different from `requireAllDemands` which requires all demands to be an exact match.
https://github.com/kedacore/keda-docs/pull/1496
Fixes #5579
=> Add requireAllDemandsAndIgnoreOthers flag

pkg/fallback/fallback.go
The original PR didn't check implicit (default) metricType for Scaling Modifiers.
Relates to https://github.com/kedacore/keda/pull/6521
=> fix: enhance fallback condition checks for ScalingModifiers with default metricType

CHANGELOG.md, pkg/scalers/elasticsearch_scaler.go, pkg/scalers/elasticsearch_scaler_test.go
This PR is for support `IgnoreNullValues` at Elasticsearch scaler.
This is also used in the Prometheus scaler for example. However I chose to set the default value to `false` so you have to explicitly turn this on so as not to disrupt current behavior.
Our use case is that we work with an Elasticsearch trigger with APM and an Elasticsearch trigger with forecast prediction for autoscaling. However, if someone looks too far into the future or the prediction has not yet been made, a Null value is returned. That is why I want to have an `IgnoreNullValues` on, for example, the forecast prediction if it does not get any data back.
Relates to https://github.com/kedacore/keda-docs/pull/1546
=> Support IgnoreNullValues at Elasticsearch scaler

controllers/eventing/reconciler.go
Since we have already checked err before and returned != nil, err must be nil here. In fact, it should return  `RequestEventLoop(ctx, reqLogger, r, cloudEventSource)`.
=> fix: fix incorrect nil return value

CHANGELOG.md, pkg/scalers/mongo_scaler.go, pkg/scalers/mongo_scaler_test.go
Support float queryValue for MongoDB scaler
Fixes #6574 
Relates to https://github.com/kedacore/keda-docs/pull/1553
=> Support float queryValue for MongoDB scaler

CHANGELOG.md, go.mod, go.sum, vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md, vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md, vendor/github.com/go-jose/go-jose/v4/README.md, vendor/github.com/go-jose/go-jose/v4/crypter.go, vendor/github.com/go-jose/go-jose/v4/jwe.go, vendor/github.com/go-jose/go-jose/v4/jwk.go, vendor/github.com/go-jose/go-jose/v4/jws.go, vendor/github.com/go-jose/go-jose/v4/opaque.go, vendor/github.com/go-jose/go-jose/v4/shared.go, vendor/github.com/go-jose/go-jose/v4/signing.go, vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go, vendor/golang.org/x/oauth2/google/default.go, vendor/golang.org/x/oauth2/google/externalaccount/aws.go, vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go, vendor/golang.org/x/oauth2/jws/jws.go, vendor/golang.org/x/oauth2/oauth2.go, vendor/golang.org/x/oauth2/pkce.go, vendor/modules.txt
```
$ go get github.com/go-jose/go-jose/v4@v4.0.5
$ go get golang.org/x/oauth2@v0.27.0
$ go mod tidy
$ go mod vendor
```
Fixes #6613
=> Update go-jose for CVE-2025-27144 & oauth2 for CVE-2025-22868

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_webhook_test.go
This fixes the `CheckFallbackValid` logic used in the admission webhook. The way it should go is:
- If we are using `ScalingModifiers` and `ScaledObject.Spec.Advanced.ScalingModifiers.MetricType` is not `AverageValue`, then this is invalid. So, this becomes inline with the change in #6521 
- If we are not using `ScalingModifiers`
1. If only cpu and memory are used, then fallback is invalid.
2. If some other triggers are used (solely or in addition to cpu/memory), and not one of them has `AverageValue` type, then fallback is invalid.
3. If some other triggers are used (solely or in addition to cpu/memory), and **_at least_** one of them has `AverageValue` type, then fallback **is** valid. This is actually inline with the code logic with the function `doFallback`, where it is called for …
=> fix!: fix CheckFallbackValid logic

pkg/metricscollector/prommetrics.go
use correct err for log.Error
and the code should be 
```
log.Error(errscaledjob, "Unable to write to metrics to Prometheus Server", "labels", labels)
```
but I'm not sure.
Fixes #
Relates to #
=> fix call log.Error with nil value error

.github/ISSUE_TEMPLATE/3_bug_report.yml, CHANGELOG.md
Relates to https://github.com/kedacore/keda/issues/6502
=> prepare release 2.17

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_types_test.go, tests/internals/fallback/fallback_test.go
In scaler.go there is a function [GetMetricTargetType](https://github.com/kedacore/keda/blob/main/pkg/scalers/scaler.go#L114-L124) which helps get the metric target type of the scaler. If no metric type is provided then the AverageValue is used.
In v2.17 is a check in the webhook admission that if at least one trigger is of the type `AverageValue`, then having fallback is valid. A `metricType` is optional and often not supplied. As a result, many scaledObjects now give errors when supplying a fallback without `metricType`.
Adding an extra check if the `trigger.MetricType` is empty will fix this issue. This check is also in the [scaler.go](https://github.com/kedacore/keda/blob/main/pkg/scalers/scaler.go#L114-L124).
Any feedback regarding the chosen solution is okay.
Fixes #6696
=> fix: Admission Webhook blocks ScaledObject without metricType with fallback

CHANGELOG.md, pkg/scalers/aws_sqs_queue_scaler.go, pkg/scalers/aws_sqs_queue_scaler_test.go
Modified the tag configuration for the `QueueURL` field in `awsSqsQueueMetadata` struct to correctly handle environment variable resolution:
The issue was that the previous tag definition caused double application of the "FromEnv" suffix when resolving environment variables.
Fixes #6712
=> fix: AWS SQS Queue queueURLFromEnv not working

pkg/scalers/gcp_stackdriver_scaler.go, pkg/scalers/gcp_stackdriver_scaler_test.go, tests/scalers/gcp/gcp_stackdriver_workload_identity/gcp_stackdriver_workload_identity_test.go
=> refactor gcp stackdriver scaler

pkg/scalers/datadog_scaler.go, pkg/scalers/datadog_scaler_test.go
Refactoring the datadog scaler. It a little bit more complicated than I have imagined. There are a few TODO that I will resolve before marking this PR ready
=> Add refactoring for datadog scaler

CHANGELOG.md, pkg/scalers/temporal.go, pkg/scalers/temporal_test.go
The Temporal scaler was failing with a "connection reset by peer" error when an API key was provided for authentication without explicitly configuring TLS.
This change modifies the getTemporalClient function to enforce a default TLS configuration when an API key is present in the trigger metadata. This aligns with the Temporal client's requirement for TLS when using API key authentication.
Also, a new test case has been added to TestParseTemporalMetadata to ensure the apiKey is correctly parsed.
Fixes #6703
=> fix: Enable TLS when using API Key for Temporal scaler

CHANGELOG.md, pkg/scalers/metrics_api_scaler.go, pkg/scalers/metrics_api_scaler_test.go
Support multiple auth methods simultaneously in Metrics API scaler. Multiple authentication methods can be used simultaneously by providing a comma-separated list in the `authMode` parameter, for example `authMode: "apiKey,tls"` enables both API key and TLS certificate authentication in a single request.
Docs https://github.com/kedacore/keda-docs/pull/1558
Fixes #6642
=> Support multiple auth methods simultaneously in Metrics API scaler

CHANGELOG.md
When I merged this PR https://github.com/kedacore/keda/pull/6645 I didn't realize that it wasn't update and the changelog was modified in the wrong section
Relates to https://github.com/kedacore/keda/pull/6645
=> chore: Move the changelog record to the right place

CHANGELOG.md, pkg/scalers/azure_servicebus_scaler.go, pkg/scalers/azure_servicebus_scaler_test.go
There was recently a refactor done in Azure Servicebus scaler released in 2.17 that appears to have accidentally removed the logic setting a default value for operation when it is not provided.
This PR should fix this.
Fixes #6730
=> fix: add default Operation in Azure Service Bus scaler

pkg/scalers/external_scaler_test.go, pkg/scalers/predictkube_scaler_test.go
Fix race conditions in tests external scaler and predictkube scaler
Relates to #6760 #6761
=> Fix race conditions in tests external scaler and predictkube scaler

.github/workflows/pr-validation.yml, Makefile, pkg/scaling/cache/scalers_cache_test.go
This PR adds an option to run unit tests with race detection enabled. Also adding a trivial test for the scalers cache which discovers existing race condition.
```
WARNING: DATA RACE
Write at 0x00c000b25ec8 by goroutine 73:
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).Close()
/home/projects/go/src/github.com/kedacore/keda/pkg/scaling/cache/scalers_cache.go:94 +0xa4
github.com/kedacore/keda/v2/pkg/scaling/cache.TestEmptyScalersCache.func5()
/home/projects/go/src/github.com/kedacore/keda/pkg/scaling/cache/scalers_cache_test.go:55 +0x3c
Previous read at 0x00c000b25ec8 by goroutine 70:
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetPushScalers()
/home/projects/go/src/github.com/kedacore/keda/pkg/scaling/cache/scalers_cache.go:82 +0x49 …
```
=> enable race condition check for unit tests

CHANGELOG.md, pkg/scalers/selenium_grid_scaler.go
Update the metric name generated from Grid scaler, since it is combined from trigger param `browserName`, `browserVersion`, and `platformName`. However, version and platform are optional and might be empty.
Sometimes the name shown in the log was `selenium-grid-chrome--`, which might cause confusion.
With this change, this helps make the metric name meaningful, only appending non-empty values.
Fixes #
Relates to #
=> Selenium Grid: Update metric name generated without part of empty

CHANGELOG.md, pkg/scaling/cache/scalers_cache.go
With the current implementation, a race condition can happen because we check the scalers size before signaling the lock, so hypothetically, the value of `c.Scalers` can change between the line when it's checked and the line when is accessed, allowing the case where `c.Scalers` is cleaned and then the index is accessed, generating a panic because of accessing out of the array length.
Checking the code and considering the original problem of [the issue](https://github.com/kedacore/keda/issues/6725), my hypothesis is that the scaler fails during the HPA metric request. It calls to [GetScaledObjectMetrics](https://github.com/kedacore/keda/blob/8e6a985a730ec5b171d2d55309d6a14ad475e764/pkg/scaling/scale_handler.go#L423) and there, after the scaler failure, [the whole ScaledObject is …
=> fix: ScalerCache gets the lock before operate the scalers

CHANGELOG.md, pkg/scaling/resolver/scale_resolvers.go, pkg/scaling/resolver/scale_resolvers_test.go
When envFrom includes a prefix setting, the scale resolver ignores this prefix and adds environment variable keys to the ScalerConfig without the prefix.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kafka-config
data:
BOOTSTRAP_SERVERS: "kafka.example.com"
PORT: "9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: dummy-app
labels:
app: dummy-app
spec:
selector:
matchLabels:
app: dummy-app
template:
metadata:
labels:
app: dummy-app
spec:
containers:
- name: app-container
image: nginx:latest
envFrom:
- configMapRef:
name: kafka-config
prefix: "KAFKA_" # Having PREFIX
```
`resolveEnv` is ignoring the `prefix` setting and loading envs without `prefix`:
Actual:
```
BOOTSTRAP_SERVERS
PORT
```
Desired:
```
KAFKA_BOOTSTRAP_SERVERS
KAFKA_PORT
```
_Provide a description of …
=> Fix: Prefixes in envFrom within deployment specs are being ignored

CHANGELOG.md, pkg/scalers/temporal.go
After seeing `connection reset by peer` errors in my Temporal KEDA scaler, I started digging and found out about #6724, which was released earlier today. I deployed the new v2.17.1 Helm chart to my K8S cluster and still kept seeing the same errors, then decided to dig into the scaler code to see what I could find. 
@rickbrouwer and I connected to explore options, and we realized that the TLS settings from #6707 were being overwritten, thus causing the error previously mentioned. This change fixed the main issue for good by rearranging the *tls.config variable, and it is already validated against a production K8S cluster.
Fixes #
Relates to #
=> fix: temporal scaler was not setting up tls for apikey auth

.github/workflows/pr-validation.yml
https://github.com/kedacore/keda/pull/6760 enabled the race condition detector for unit tests but not required to pass for PRs to merge. Since it currently reports no failures, I would like to propose this to be a binding requirement for PR to merge.
closes: https://github.com/kedacore/keda/issues/6761
=> require race condition check for PRs to pass

CHANGELOG.md, apis/eventing/v1alpha1/cloudeventsource_webhook.go, apis/keda/v1alpha1/scaledjob_webhook.go, apis/keda/v1alpha1/scaledobject_webhook.go, apis/keda/v1alpha1/triggerauthentication_webhook.go
As suggested in #6660, this PR replaces the deprecated `webhook.Validator` with `webhook.CustomValidator`.
The controller-runtime has not been updated yet, as the current version already supports `webhook.CustomValidator`.
Fixes #6660
=> Replace deprecated webhook.Validator with webhook.CustomValidator

go.mod, vendor/modules.txt
hey yall!  We recently took a dependency on `github.com/kedacore/keda/v2`
But that's now causing all our IDEs to break with
```
go list -modfile=go.mod -m -json -mod=mod all
go: [github.com/prometheus/prometheus@v0.0.0-00010101000000-000000000000](http://github.com/prometheus/prometheus@v0.0.0-00010101000000-000000000000): invalid version: unknown revision 000000000000
```
seems like it's due to this line here https://github.com/kedacore/keda/blob/e23ef462abb5948802d303a56aebe53adbabbcde/go.mod#L80
I asked that ^ question in Slack and @JorTurFer asked that I open this PR
So this just changes the require line to match what we're replacing so that when downstream projects take a dependency on keda, they don't import a bad version.
Relates to …
=> Require the same version we replace for prometheus

CHANGELOG.md, controllers/keda/hpa.go, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_controller_test.go
When the ScaledObject adopts an HPA or if the hpaName in the ScaledObject status is removed for any reason, the hpaName status will no longer get set. It is only set when the HPA is created by the ScaledObject.
We add setting the HPA name in the ScaledObject status to the regular reconciliation loop for the ScaledObject.
See https://github.com/kedacore/keda/issues/6336
Fixes #6336
=> Update hpaName in ScaledObject status when HPA already exists

pkg/scalers/nsq_scaler_test.go
The `TestNSQAggregateDepth` and `TestNSQGetTopicProducers` tests were failing intermittently due to a race condition in the mock HTTP server setup. The tests were using `atomic.NewInt32(-1)` followed by `callCount.Inc()` and multiple `callCount.Load()` calls, which could result in inconsistent values when accessed concurrently.
This happens in de amd64 test in PR #6834 and #6546
=> fix: resolve race condition in NSQ scaler test

tests/helper/helper.go, tests/sequential/opentelemetry_metrics/opentelemetry_metrics_test.go, tests/sequential/prometheus_metrics/prometheus_metrics_test.go
As we don't check otel metrics directly but exported via Prometheus in collector, we are affected by posible changes in how the labels are generated, for example, with the collector v1.128.0, the metrics is:
```bash
keda_cloudeventsource_events_emitted_count_total{
cloudEventSource="opentelemetry-metrics-test-ce",
eventsink="http",
job="unknown_service:keda",
namespace="opentelemetry-metrics-test-ns",
otel_scope_name="keda-open-telemetry-metrics",
otel_scope_schema_url="",
otel_scope_version="",
state="emitted"
} 1
```
And the same metric from the collector v1.127.0 is:
```bash
keda_cloudeventsource_events_emitted_count_total{
cloudEventSource="opentelemetry-metrics-test-ce",
eventsink="http",
job="unknown_service:keda",
namespace="opentelemetry-metrics-test-ns",
state="emitted"
} 1
``` …
=> fix: e2e test checks label value by name and not by index

pkg/scalers/nsq_scaler_test.go
Replaced shared atomic counter with dedicated mock servers per response to prevent race conditions in concurrent test execution. Each test case now creates individual servers instead of relying on request ordering with shared state.
=> fix: eliminate race conditions in NSQ scaler tests by using separate mock servers

CHANGELOG.md, pkg/scalers/gcp/gcp_stackdriver_client.go, pkg/scalers/gcp/gcp_stackdriver_client_test.go, pkg/scalers/gcp_pubsub_scaler.go, pkg/scalers/gcp_pubsub_scaler_test.go
refactor gcp pubsub scaler to use typed config
=> refactor gcp pubsub scaler

CHANGELOG.md, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/rabbitmq_scaler_test.go
This fixes the incorrect URL encoding in RabbitMQ vhosts by passing the `RawPath` to `getVhostAndPathFromURL` (which is sometimes empty, e.g. when there would be no difference with `Path`).
I've added testcases for vhosts containing `%2F`.
I've removed the check for `//` in `getVhostAndPathFromURL` because it is no longer necessary.
Fixes #6963
=> Fix incorrect URL encoding in RabbitMQ vhosts containing %2f

.github/workflows/pr-e2e-checker.yml
Adding any label (like `ok-to-merge`) to a PR triggers the e2e-checker workflow, which resets successful e2e test status from green to queued. This PR ensures that the e2e-checker only trigger the workflow when the `skip-e2e` label is added or removed, ignoring all other label changes.
I think this is very useful so we can use labels like `ok-to-merge` so we have an overview of which PRs have two approvals for example and the tests have passed to know which ones can continue.
=> fix: prevent e2e test reset when adding non-skip labels

.github/workflows/pr-e2e.yml
As we are building images for (PR) e2e tests using buildx to test also ARM64 and s390x arch, this PR changes the runner that we use to generate the images because the ARM64 runner is significantly more powerful than the GH hosted runner for AMD64. This should improve the generation time (I hope it so)
=> chore: use ARM64 machine to build e2e test images

tests/README.md, tests/internals/fallback/fallback_test.go, tests/internals/global_custom_ca/global_custom_ca_test.go, tests/internals/polling_cooldown_so/polling_cooldown_so_test.go, tests/internals/replica_update_so/replica_update_so_test.go, tests/internals/scaling_modifiers/scaling_modifiers_test.go, tests/internals/trigger_update_so/trigger_update_so_test.go, tests/internals/update_ta/update_ta_test.go, tests/scalers/aws/aws_managed_prometheus/aws_managed_prometheus_test.go, tests/scalers/aws/aws_managed_prometheus_pod_identity/aws_managed_prometheus_pod_identity_test.go, tests/scalers/beanstalkd/beanstalkd_test.go, tests/scalers/cron/cron_test.go, tests/scalers/datadog/datadog_api/datadog_api_test.go, tests/scalers/dynatrace/dynatrace_test.go, tests/scalers/gcp/gcp_cloud_tasks/gcp_cloud_tasks_test.go, tests/scalers/gcp/gcp_cloud_tasks_workload_identity/gcp_cloud_tasks_workload_identity_test.go, tests/scalers/gcp/gcp_prometheus_workload_identity/gcp_prometheus_workload_identity_test.go, tests/scalers/gcp/gcp_pubsub/gcp_pubsub_test.go, tests/scalers/kubernetes_workload/kubernetes_workload_test.go, tests/scalers/metrics_api/metrics_api_test.go, tests/scalers/mysql/mysql_test.go, tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go, tests/scalers/splunk/splunk_test.go, tests/scalers/sumologic/sumologic_test.go, tests/secret-providers/trigger_auth_bound_service_account_token/trigger_auth_bound_service_account_token_test.go, tests/sequential/datadog_dca/datadog_dca_test.go
Updated test logs to reflect the amount of time the assertion actually takes, only changed the ones using https://github.com/kedacore/keda/blob/main/tests/helper/helper.go#L466
Time for the assertion to fail is `iterations * intervalSeconds`
NOTE: no test changed, only the logging. Because of this Im not sure if most of the checklist bellow make sense for this PR
Fixes #6972
=> Fix waitfordeploymentreplicareadycount duration logs

CHANGELOG.md, pkg/scalers/prometheus_scaler.go, pkg/scalers/rabbitmq_scaler.go, pkg/scalers/scalersconfig/typed_config.go, pkg/scalers/scalersconfig/typed_config_test.go
When refactoring the `Timeout` field from `int` to `time.Duration` (#6650), the parsing logic incorrectly interprets numeric configuration values as seconds instead of milliseconds. This changes the behavior of existing timeout configurations.
Thanks @arapulido for informing me about this issue.
=> fix: parse timeout config as milliseconds instead of seconds

config/metrics-server/deployment.yaml
Currently the way the config is for the  written metrics-apiserver is both out of sync with how the other two deployments are structured but it also produces a somewhat spurious start command.  If you inspect the running process you see that the start command is the following:
```
/keda-adapter --secure-port=6443 --logtostderr=true --v=0 /usr/local/bin/keda-adapter --secure-port=6443 --logtostderr=true --stderrthreshold=ERROR --v=0 --client-ca-file=/certs/ca.crt --tls-cert-file=/certs/tls.crt --tls-private-key-file=/certs/tls.key --cert-dir=/certs
```
=> Aligns command structure across all deployments

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, apis/keda/v1alpha1/scaledobject_types_test.go, controllers/keda/scaledobject_controller.go
There is race condition when removing the `autoscaling.keda.sh/paused-replicas` annotation. The ScaledObject sometimes remains `Paused=True`, even though the annotation is gone. `NeedToBePausedByAnnotation()` checked `Status.PausedReplicaCount` instead of just annotation presence.
I have modified the `NeedToBePausedByAnnotation()` to check only annotation, not status. Also removed the unnecessary `HasPausedReplicaAnnotation()` function.
I have also changed the test. The "old" `NeedToBePausedByAnnotation()` implementation checked both annotation presence and status field. The "new" implementation only checks annotation presence.
The test case previously expected `false` because the annotation existed but the status field was nil. Now it correctly returns `true` because the annotation …
=> fix: resolve race condition when removing paused-replicas annotation from ScaledObject

tests/helper/helper.go, tests/sequential/prometheus_metrics/prometheus_metrics_test.go
Refactors the prometheus_metrics sequential e2e test to rely on polling with a conditional instead of sleeping. We've noticed flakes with this test where the magic sleep timings don't play well on certain machines and platforms.
Also adds KedaEventually which acts like ginkgo.Eventually, which allows to poll a condition until it is true.
Relates to https://github.com/kedacore/keda/pull/6759
=> test: refactor prometheus_metrics_test.go

CHANGELOG.md, Makefile, cmd/adapter/main.go, pkg/metricsservice/api/metrics.pb.go, pkg/metricsservice/api/metrics.proto, pkg/metricsservice/api/metrics_grpc.pb.go, pkg/metricsservice/client.go, pkg/metricsservice/server.go, pkg/mock/mock_scaling/mock_interface.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_raw_metrics.go, pkg/scaling/scale_handler_test.go
Fixes [#7094](https://github.com/kedacore/keda/issues/7094)
Relates to #
=> Add gRPC service that allows subscribing to a raw metric values for given ns,SO&triggerName

CHANGELOG.md, apis/keda/v1alpha1/scaledobject_types.go, controllers/keda/hpa.go, controllers/keda/scaledobject_controller.go, controllers/keda/scaledobject_controller_test.go, controllers/keda/util/predicate.go, pkg/scaling/executor/scale_scaledobjects.go, pkg/scaling/executor/scale_scaledobjects_test.go, tests/internals/pause_scale_out/pause_scale_out_test.go
This PR adds the converse annotation to #6902, pause-scale-out. Implementation is similar to the pause-scale-in annotation, except in this case:
- HPA ScaleUp Policy is disabled when annotation is set
- ScaleUp from Min or Idle is blocked when the annotation is set.
This PR adds complementary Unit Tests and an e2e test like the other change added.
Fixes #7022 
Relates to #[1619](https://github.com/kedacore/keda-docs/pull/1619)
=> Add support for pause scale out annotation

pkg/metricsservice/server.go, pkg/scaling/scale_handler.go, pkg/scaling/scale_handler_raw_metrics.go
I found a bug in my previous [PR](https://github.com/kedacore/keda/pull/7093) (only after it got merged ;), sry)
=> fix: raw metrics over gRPC (sending to closed channel)

.github/workflows/pr-validation.yml
**tl;dr**: this prolongs the step execution by ~4 minutes but frees up ~13 GB space, which means tests don't run out of disk space.
___
There is a number of PRs that fail the PR validation step on amd64 runner due to low disk space
```
compile: writing output: write $WORK/b2581/_pkg_.a: no space left on device
FAIL	github.com/kedacore/keda/v2/controllers/keda [build failed]
vet: failed to export analysis facts: write $WORK/b2588/vet.out: no space left on device
github.com/kedacore/keda/v2/pkg/mock/mock_eventemitter: mkdir /tmp/go-build1683534545/b2594/: no space left on device
```
* https://github.com/kedacore/keda/actions/runs/18184713554/job/51770792105?pr=6534
* https://github.com/kedacore/keda/actions/runs/18134343508/job/51609166097?pr=7115
For a quick fix to unblock PRs from …
=> ci: clear some disk space for PR validation step

.github/ISSUE_TEMPLATE/4_release_tracker.md
Follow up on https://github.com/kedacore/keda/pull/7157
I realised there are some things that could be improved
=> fix: update release tracker checklist for changelog preparation

Makefile, go.mod
- Bumping envtest to match k8s deps
- Moving the `replace` block in the go.mod to the top, so `go mod tidy` works on 2 blocks below (require and indirect require)
Relates: https://github.com/kedacore/keda/issues/6853
=> chore: bump envtest to 1.33 and clean go.mod

CHANGELOG.md, pkg/scalers/azure_pipelines_scaler.go, pkg/scalers/azure_pipelines_scaler_test.go, schema/generated/scalers-metadata-schema.json, schema/generated/scalers-metadata-schema.yaml
feat(azure_pipelines_scaler): add an option to enable demands to be case insensitive
Azure Devops is case insensitive, scaler is not
When you have an Azure DevOps job with demands written in uppercase, Azure Pipelines tends to ignore them if they are configured in lowercase, and vice versa.
Fixes #7111
Relates to #
=> feat(azure_pipelines_scaler): add an option to enable demands to be case insensitive

tests/internals/cloudevent_source/cloudevent_source_test.go, tests/internals/fallback/fallback.go, tests/internals/global_custom_ca/global_custom_ca_test.go, tests/internals/min_replica_sj/min_replica_sj_test.go, tests/internals/polling_cooldown_so/polling_cooldown_so_test.go, tests/internals/replica_update_so/replica_update_so_test.go, tests/internals/scaling_modifiers/scaling_modifiers_test.go, tests/internals/scaling_strategies/eager_scaling_strategy_test.go, tests/internals/trigger_update_so/trigger_update_so_test.go, tests/scalers/couchdb/couchdb_test.go, tests/scalers/external_push_scaler/external_push_scaler_test.go, tests/scalers/external_push_scaler_old_proto/external_push_scaler_old_proto_test.go, tests/scalers/external_scaler_sj/external_scaler_sj_test.go, tests/scalers/external_scaler_so/external_scaler_so_test.go, tests/scalers/ibmmq/ibmmq_test.go, tests/scalers/metrics_api/metrics_api_test.go, tests/scalers/prometheus/prometheus_helper.go, tests/scalers/rabbitmq/rabbitmq_helper.go, tests/secret-providers/trigger_auth_bound_service_account_token/trigger_auth_bound_service_account_token_test.go, tests/sequential/opentelemetry_metrics/opentelemetry_metrics_test.go, tests/sequential/prometheus_metrics/prometheus_metrics_test.go
Replaces some test image short names with their fully qualified domain names instead so the tests can be more explicit about which registry the image is pulled from.
=> chore(tests): replace test image short names with fqdn
